// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

using System.Net.Sockets;

namespace Osquery;

/// <summary>
/// Client for communicating with an osquery extension manager instance.
/// Connects via the osquery Thrift socket interface and provides methods
/// for executing SQL queries and managing extensions.
/// </summary>
public class OsqueryClient : IDisposable
{
    private readonly IOsqueryConnection _connection;
    private bool _disposed;

    /// <summary>
    /// Creates a new OsqueryClient using the specified socket path.
    /// </summary>
    /// <param name="socketPath">Path to the osquery extensions socket.</param>
    public OsqueryClient(string socketPath)
    {
        _connection = new OsquerySocketConnection(socketPath);
    }

    /// <summary>
    /// Creates a new OsqueryClient using a custom connection (for testing).
    /// </summary>
    internal OsqueryClient(IOsqueryConnection connection)
    {
        _connection = connection;
    }

    /// <summary>
    /// Executes a raw SQL query against osquery and returns the results.
    /// </summary>
    /// <param name="sql">The SQL query string.</param>
    /// <returns>A list of rows, each represented as a dictionary of column name to value.</returns>
    public async Task<QueryResult> QueryAsync(string sql)
    {
        await _connection.EnsureConnectedAsync();
        return await _connection.QueryAsync(sql);
    }

    /// <summary>
    /// Executes a raw SQL query against osquery synchronously.
    /// </summary>
    /// <param name="sql">The SQL query string.</param>
    /// <returns>A list of rows, each represented as a dictionary of column name to value.</returns>
    public QueryResult Query(string sql)
    {
        return QueryAsync(sql).GetAwaiter().GetResult();
    }

    /// <summary>
    /// Returns an IQueryable for the specified osquery table, enabling LINQ queries.
    /// </summary>
    /// <typeparam name="T">The table model type.</typeparam>
    /// <returns>An IQueryable that translates LINQ expressions into osquery SQL.</returns>
    public IQueryable<T> Table<T>() where T : class, new()
    {
        var provider = new OsqueryQueryProvider(this);
        return new OsqueryQueryable<T>(provider);
    }

    /// <summary>
    /// Executes a SQL query generated by the LINQ provider.
    /// </summary>
    internal async Task<IEnumerable<Dictionary<string, string>>> ExecuteQueryAsync(string sql)
    {
        var result = await QueryAsync(sql);
        if (result.Status.Code != 0)
        {
            throw new OsqueryException($"Query failed: {result.Status.Message}");
        }
        return result.Rows;
    }

    public void Dispose()
    {
        if (!_disposed)
        {
            _connection.Dispose();
            _disposed = true;
        }
        GC.SuppressFinalize(this);
    }
}
