// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Additional macOS user account data from the AccountPolicy section of OpenDirectory.
/// </summary>
[OsqueryTable("account_policy_data")]
public class AccountPolicyData
{
    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>When the account was first created</summary>
    [OsqueryColumn("creation_time")]
    public double CreationTime { get; set; }

    /// <summary>The number of failed login attempts using an incorrect password. Count resets after a correct password is entered.</summary>
    [OsqueryColumn("failed_login_count")]
    public long FailedLoginCount { get; set; }

    /// <summary>The time of the last failed login attempt. Resets after a correct password is entered</summary>
    [OsqueryColumn("failed_login_timestamp")]
    public double FailedLoginTimestamp { get; set; }

    /// <summary>The time the password was last changed</summary>
    [OsqueryColumn("password_last_set_time")]
    public double PasswordLastSetTime { get; set; }
}
