// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Firmware ACPI functional table common metadata and content.
/// </summary>
[OsqueryTable("acpi_tables")]
public class AcpiTable
{
    /// <summary>ACPI table name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Size of compiled table data</summary>
    [OsqueryColumn("size")]
    public int Size { get; set; }

    /// <summary>MD5 hash of table content</summary>
    [OsqueryColumn("md5")]
    public string Md5 { get; set; } = "";
}
