// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS application layer firewall (ALF) service details.
/// </summary>
[OsqueryTable("alf")]
public class Alf
{
    /// <summary>1 If allow signed mode is enabled else 0 (not supported on macOS 15+)</summary>
    [OsqueryColumn("allow_signed_enabled")]
    public int AllowSignedEnabled { get; set; }

    /// <summary>1 If firewall unloading enabled else 0 (not supported on macOS 15+)</summary>
    [OsqueryColumn("firewall_unload")]
    public int FirewallUnload { get; set; }

    /// <summary>1 If the firewall is enabled with exceptions, 2 if the firewall is configured to block all incoming connections, else 0</summary>
    [OsqueryColumn("global_state")]
    public int GlobalState { get; set; }

    /// <summary>1 If logging mode is enabled else 0</summary>
    [OsqueryColumn("logging_enabled")]
    public int LoggingEnabled { get; set; }

    /// <summary>Firewall logging option (not supported on macOS 15+)</summary>
    [OsqueryColumn("logging_option")]
    public int LoggingOption { get; set; }

    /// <summary>1 If stealth mode is enabled else 0</summary>
    [OsqueryColumn("stealth_enabled")]
    public int StealthEnabled { get; set; }

    /// <summary>Application Layer Firewall version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";
}
