// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// ALF services explicitly allowed to perform networking. Not supported on macOS 15+ (returns no results).
/// </summary>
[OsqueryTable("alf_explicit_auths")]
public class AlfExplicitAuth
{
    /// <summary>Process name that is explicitly allowed</summary>
    [OsqueryColumn("process")]
    public string Process { get; set; } = "";
}
