// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track active AppArmor profiles.
/// </summary>
[OsqueryTable("apparmor_profiles")]
public class ApparmorProfile
{
    /// <summary>Unique, aa-status compatible, policy identifier.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Policy name.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Which executable(s) a profile will attach to.</summary>
    [OsqueryColumn("attach")]
    public string Attach { get; set; } = "";

    /// <summary>How the policy is applied.</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>A unique hash that identifies this policy.</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>A unique hash that identifies this policy.</summary>
    [OsqueryColumn("sha256")]
    public string Sha256 { get; set; } = "";
}
