// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Application Compatibility shims are a way to persist malware. This table presents the AppCompat Shim information from the registry in a nice format. See http://files.brucon.org/2015/Tomczak_and_Ballenthin_Shims_for_the_Win.pdf for more details.
/// </summary>
[OsqueryTable("appcompat_shims")]
public class AppcompatShim
{
    /// <summary>Name of the executable that is being shimmed. This is pulled from the registry.</summary>
    [OsqueryColumn("executable")]
    public string Executable { get; set; } = "";

    /// <summary>This is the path to the SDB database.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Description of the SDB.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Install time of the SDB</summary>
    [OsqueryColumn("install_time")]
    public int InstallTime { get; set; }

    /// <summary>Type of the SDB database.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Unique GUID of the SDB.</summary>
    [OsqueryColumn("sdb_id")]
    public string SdbId { get; set; } = "";

}
