// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS application schemes and handlers (e.g., http, file, mailto).
/// </summary>
[OsqueryTable("app_schemes")]
public class AppScheme
{
    /// <summary>Name of the scheme/protocol</summary>
    [OsqueryColumn("scheme")]
    public string Scheme { get; set; } = "";

    /// <summary>Application label for the handler</summary>
    [OsqueryColumn("handler")]
    public string Handler { get; set; } = "";

    /// <summary>1 if this handler is the OS default, else 0</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>1 if this handler does NOT exist on macOS by default, else 0</summary>
    [OsqueryColumn("external")]
    public int External { get; set; }

    /// <summary>1 if this handler is protected (reserved) by macOS, else 0</summary>
    [OsqueryColumn("protected")]
    public int @Protected { get; set; }
}
