// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Current list of APT repositories or software channels.
/// </summary>
[OsqueryTable("apt_sources")]
public class AptSource
{
    /// <summary>Repository name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Source file</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Repository base URI</summary>
    [OsqueryColumn("base_uri")]
    public string BaseUri { get; set; } = "";

    /// <summary>Release name</summary>
    [OsqueryColumn("release")]
    public string Release { get; set; } = "";

    /// <summary>Repository source version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Repository maintainer</summary>
    [OsqueryColumn("maintainer")]
    public string Maintainer { get; set; } = "";

    /// <summary>Repository components</summary>
    [OsqueryColumn("components")]
    public string Components { get; set; } = "";

    /// <summary>Repository architectures</summary>
    [OsqueryColumn("architectures")]
    public string Architectures { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }
}
