// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Address resolution cache, both static and dynamic (from ARP, NDP).
/// </summary>
[OsqueryTable("arp_cache")]
public class ArpCache
{
    /// <summary>IPv4 address target</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";

    /// <summary>MAC address of broadcasted address</summary>
    [OsqueryColumn("mac")]
    public string Mac { get; set; } = "";

    /// <summary>Interface of the network for the MAC</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>1 for true, 0 for false</summary>
    [OsqueryColumn("permanent")]
    public string Permanent { get; set; } = "";
}
