// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Configuration files parsed by augeas.
/// </summary>
[OsqueryTable("augeas")]
public class Augea
{
    /// <summary>The node path of the configuration item</summary>
    [OsqueryColumn("node")]
    public string Node { get; set; } = "";

    /// <summary>The value of the configuration item</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>The label of the configuration item</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>The path to the configuration file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
