// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// File (executable, bundle, installer, disk) code signing status.
/// </summary>
[OsqueryTable("authenticode")]
public class Authenticode
{
    /// <summary>Must provide a path or directory</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The original program name that the publisher has signed</summary>
    [OsqueryColumn("original_program_name")]
    public string OriginalProgramName { get; set; } = "";

    /// <summary>The certificate serial number</summary>
    [OsqueryColumn("serial_number")]
    public string SerialNumber { get; set; } = "";

    /// <summary>The certificate issuer name</summary>
    [OsqueryColumn("issuer_name")]
    public string IssuerName { get; set; } = "";

    /// <summary>The certificate subject name</summary>
    [OsqueryColumn("subject_name")]
    public string SubjectName { get; set; } = "";

    /// <summary>The signature check result</summary>
    [OsqueryColumn("result")]
    public string Result { get; set; } = "";
}
