// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A line-delimited authorized_keys table.
/// </summary>
[OsqueryTable("authorized_keys")]
public class AuthorizedKey
{
    /// <summary>The local owner of authorized_keys file</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Key type</summary>
    [OsqueryColumn("algorithm")]
    public string Algorithm { get; set; } = "";

    /// <summary>Key encoded as base64</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Optional list of login options</summary>
    [OsqueryColumn("options")]
    public string Options { get; set; } = "";

    /// <summary>Optional comment</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";

    /// <summary>Path to the authorized_keys file</summary>
    [OsqueryColumn("key_file")]
    public string KeyFile { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
