// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS Authorization mechanisms database.
/// </summary>
[OsqueryTable("authorization_mechanisms")]
public class AuthorizationMechanism
{
    /// <summary>Label of the authorization right</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Authorization plugin name</summary>
    [OsqueryColumn("plugin")]
    public string Plugin { get; set; } = "";

    /// <summary>Name of the mechanism that will be called</summary>
    [OsqueryColumn("mechanism")]
    public string Mechanism { get; set; } = "";

    /// <summary>If privileged it will run as root, else as an anonymous user</summary>
    [OsqueryColumn("privileged")]
    public string Privileged { get; set; } = "";

    /// <summary>The whole string entry</summary>
    [OsqueryColumn("entry")]
    public string Entry { get; set; } = "";

}
