// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Azure instance tags.
/// </summary>
[OsqueryTable("azure_instance_tags")]
public class AzureInstanceTag
{
    /// <summary>Unique identifier for the VM</summary>
    [OsqueryColumn("vm_id")]
    public string VmId { get; set; } = "";

    /// <summary>The tag key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>The tag value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";
}
