// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Azure instance metadata.
/// </summary>
[OsqueryTable("azure_instance_metadata")]
public class AzureInstanceMetadata
{
    /// <summary>Azure Region the VM is running in</summary>
    [OsqueryColumn("location")]
    public string Location { get; set; } = "";

    /// <summary>Name of the VM</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Offer information for the VM image (Azure image gallery VMs only)</summary>
    [OsqueryColumn("offer")]
    public string Offer { get; set; } = "";

    /// <summary>Publisher of the VM image</summary>
    [OsqueryColumn("publisher")]
    public string Publisher { get; set; } = "";

    /// <summary>SKU for the VM image</summary>
    [OsqueryColumn("sku")]
    public string Sku { get; set; } = "";

    /// <summary>Version of the VM image</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Linux or Windows</summary>
    [OsqueryColumn("os_type")]
    public string OsType { get; set; } = "";

    /// <summary>Update domain the VM is running in</summary>
    [OsqueryColumn("platform_update_domain")]
    public string PlatformUpdateDomain { get; set; } = "";

    /// <summary>Fault domain the VM is running in</summary>
    [OsqueryColumn("platform_fault_domain")]
    public string PlatformFaultDomain { get; set; } = "";

    /// <summary>Unique identifier for the VM</summary>
    [OsqueryColumn("vm_id")]
    public string VmId { get; set; } = "";

    /// <summary>VM size</summary>
    [OsqueryColumn("vm_size")]
    public string VmSize { get; set; } = "";

    /// <summary>Azure subscription for the VM</summary>
    [OsqueryColumn("subscription_id")]
    public string SubscriptionId { get; set; } = "";

    /// <summary>Resource group for the VM</summary>
    [OsqueryColumn("resource_group_name")]
    public string ResourceGroupName { get; set; } = "";

    /// <summary>Placement group for the VM scale set</summary>
    [OsqueryColumn("placement_group_id")]
    public string PlacementGroupId { get; set; } = "";

    /// <summary>VM scale set name</summary>
    [OsqueryColumn("vm_scale_set_name")]
    public string VmScaleSetName { get; set; } = "";

    /// <summary>Availability zone of the VM</summary>
    [OsqueryColumn("zone")]
    public string Zone { get; set; } = "";
}
