// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Background Activities Moderator (BAM) tracks application execution.
/// </summary>
[OsqueryTable("background_activities_moderator")]
public class BackgroundActivitiesModerator
{
    /// <summary>Application file path.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Most recent time application was executed.</summary>
    [OsqueryColumn("last_execution_time")]
    public long LastExecutionTime { get; set; }

    /// <summary>User SID.</summary>
    [OsqueryColumn("sid")]
    public string Sid { get; set; } = "";

}
