// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve bitlocker status of the machine.
/// </summary>
[OsqueryTable("bitlocker_info")]
public class BitlockerInfo
{
    /// <summary>ID of the encrypted drive.</summary>
    [OsqueryColumn("device_id")]
    public string DeviceId { get; set; } = "";

    /// <summary>Drive letter of the encrypted drive.</summary>
    [OsqueryColumn("drive_letter")]
    public string DriveLetter { get; set; } = "";

    /// <summary>Persistent ID of the drive.</summary>
    [OsqueryColumn("persistent_volume_id")]
    public string PersistentVolumeId { get; set; } = "";

    /// <summary>The bitlocker conversion status of the drive.</summary>
    [OsqueryColumn("conversion_status")]
    public int ConversionStatus { get; set; }

    /// <summary>The bitlocker protection status of the drive.</summary>
    [OsqueryColumn("protection_status")]
    public int ProtectionStatus { get; set; }

    /// <summary>The encryption type of the device.</summary>
    [OsqueryColumn("encryption_method")]
    public string EncryptionMethod { get; set; } = "";

    /// <summary>The FVE metadata version of the drive.</summary>
    [OsqueryColumn("version")]
    public int Version { get; set; }

    /// <summary>The percentage of the drive that is encrypted.</summary>
    [OsqueryColumn("percentage_encrypted")]
    public int PercentageEncrypted { get; set; }

    /// <summary>The accessibility status of the drive from Windows.</summary>
    [OsqueryColumn("lock_status")]
    public int LockStatus { get; set; }

}
