// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Block (buffered access) device file nodes: disks, ramdisks, and DMG containers.
/// </summary>
[OsqueryTable("block_devices")]
public class BlockDevice
{
    /// <summary>Block device name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Block device parent name</summary>
    [OsqueryColumn("parent")]
    public string Parent { get; set; } = "";

    /// <summary>Block device vendor string</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Block device model string identifier</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>Disk serial number</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>Block device size in blocks</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Block size in bytes</summary>
    [OsqueryColumn("block_size")]
    public int BlockSize { get; set; }

    /// <summary>Block device Universally Unique Identifier</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Block device type string</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Block device label string</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";
}
