// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track time/action process executions.
/// </summary>
[OsqueryTable("bpf_process_events")]
public class BpfProcessEvent
{
    /// <summary>Thread ID</summary>
    [OsqueryColumn("tid")]
    public long Tid { get; set; }

    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Parent process ID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Cgroup ID</summary>
    [OsqueryColumn("cid")]
    public int Cid { get; set; }

    /// <summary>Exit code of the system call</summary>
    [OsqueryColumn("exit_code")]
    public string ExitCode { get; set; } = "";

    /// <summary>Set to 1 if one or more buffers could not be captured</summary>
    [OsqueryColumn("probe_error")]
    public int ProbeError { get; set; }

    /// <summary>System call name</summary>
    [OsqueryColumn("syscall")]
    public string Syscall { get; set; } = "";

    /// <summary>Binary path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Current working directory</summary>
    [OsqueryColumn("cwd")]
    public string Cwd { get; set; } = "";

    /// <summary>Command line arguments</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>How much time was spent inside the syscall (nsecs)</summary>
    [OsqueryColumn("duration")]
    public int Duration { get; set; }

    /// <summary>Command line arguments, in JSON format</summary>
    [OsqueryColumn("json_cmdline")]
    public string JsonCmdline { get; set; } = "";

    /// <summary>The nsecs uptime timestamp as obtained from BPF</summary>
    [OsqueryColumn("ntime")]
    public string Ntime { get; set; } = "";

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public int Eid { get; set; }

}
