// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track network socket opens and closes.
/// </summary>
[OsqueryTable("bpf_socket_events")]
public class BpfSocketEvent
{
    /// <summary>Thread ID</summary>
    [OsqueryColumn("tid")]
    public long Tid { get; set; }

    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Parent process ID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Cgroup ID</summary>
    [OsqueryColumn("cid")]
    public int Cid { get; set; }

    /// <summary>Exit code of the system call</summary>
    [OsqueryColumn("exit_code")]
    public string ExitCode { get; set; } = "";

    /// <summary>Set to 1 if one or more buffers could not be captured</summary>
    [OsqueryColumn("probe_error")]
    public int ProbeError { get; set; }

    /// <summary>System call name</summary>
    [OsqueryColumn("syscall")]
    public string Syscall { get; set; } = "";

    /// <summary>Path of executed file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The file description for the process socket</summary>
    [OsqueryColumn("fd")]
    public string Fd { get; set; } = "";

    /// <summary>The Internet protocol family ID</summary>
    [OsqueryColumn("family")]
    public int Family { get; set; }

    /// <summary>The socket type</summary>
    [OsqueryColumn("type")]
    public int Type { get; set; }

    /// <summary>The network protocol ID</summary>
    [OsqueryColumn("protocol")]
    public int Protocol { get; set; }

    /// <summary>Local address associated with socket</summary>
    [OsqueryColumn("local_address")]
    public string LocalAddress { get; set; } = "";

    /// <summary>Remote address associated with socket</summary>
    [OsqueryColumn("remote_address")]
    public string RemoteAddress { get; set; } = "";

    /// <summary>Local network protocol port number</summary>
    [OsqueryColumn("local_port")]
    public int LocalPort { get; set; }

    /// <summary>Remote network protocol port number</summary>
    [OsqueryColumn("remote_port")]
    public int RemotePort { get; set; }

    /// <summary>How much time was spent inside the syscall (nsecs)</summary>
    [OsqueryColumn("duration")]
    public int Duration { get; set; }

    /// <summary>The nsecs uptime timestamp as obtained from BPF</summary>
    [OsqueryColumn("ntime")]
    public string Ntime { get; set; } = "";

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public int Eid { get; set; }
}
