// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// All C/NPAPI browser plugin details for all users. C/NPAPI has been deprecated on all major browsers. To query for plugins on modern browsers, try: `chrome_extensions` `firefox_addons` `safari_extensions`.
/// </summary>
[OsqueryTable("browser_plugins")]
public class BrowserPlugin
{
    /// <summary>The local user that owns the plugin</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Plugin display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Plugin identifier</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Plugin short version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Build SDK used to compile plugin</summary>
    [OsqueryColumn("sdk")]
    public string Sdk { get; set; } = "";

    /// <summary>Plugin description text</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Plugin language-localization</summary>
    [OsqueryColumn("development_region")]
    public string DevelopmentRegion { get; set; } = "";

    /// <summary>Plugin requires native execution</summary>
    [OsqueryColumn("native")]
    public int Native { get; set; }

    /// <summary>Path to plugin bundle</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Is the plugin disabled. 1 = Disabled</summary>
    [OsqueryColumn("disabled")]
    public int Disabled { get; set; }
}
