// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Returns info about a Carbon Black sensor install.
/// </summary>
[OsqueryTable("carbon_black_info")]
public class CarbonBlackInfo
{
    /// <summary>Sensor ID of the Carbon Black sensor</summary>
    [OsqueryColumn("sensor_id")]
    public int SensorId { get; set; }

    /// <summary>Sensor group</summary>
    [OsqueryColumn("config_name")]
    public string ConfigName { get; set; } = "";

    /// <summary>If the sensor is configured to send back binaries to the Carbon Black server</summary>
    [OsqueryColumn("collect_store_files")]
    public int CollectStoreFiles { get; set; }

    /// <summary>If the sensor is configured to capture module loads</summary>
    [OsqueryColumn("collect_module_loads")]
    public int CollectModuleLoads { get; set; }

    /// <summary>If the sensor is configured to collect metadata of binaries</summary>
    [OsqueryColumn("collect_module_info")]
    public int CollectModuleInfo { get; set; }

    /// <summary>If the sensor is configured to collect file modification events</summary>
    [OsqueryColumn("collect_file_mods")]
    public int CollectFileMods { get; set; }

    /// <summary>If the sensor is configured to collect registry modification events</summary>
    [OsqueryColumn("collect_reg_mods")]
    public int CollectRegMods { get; set; }

    /// <summary>If the sensor is configured to collect network connections</summary>
    [OsqueryColumn("collect_net_conns")]
    public int CollectNetConns { get; set; }

    /// <summary>If the sensor is configured to process events</summary>
    [OsqueryColumn("collect_processes")]
    public int CollectProcesses { get; set; }

    /// <summary>If the sensor is configured to cross process events</summary>
    [OsqueryColumn("collect_cross_processes")]
    public int CollectCrossProcesses { get; set; }

    /// <summary>If the sensor is configured to EMET events</summary>
    [OsqueryColumn("collect_emet_events")]
    public int CollectEmetEvents { get; set; }

    /// <summary>If the sensor is configured to collect non binary file writes</summary>
    [OsqueryColumn("collect_data_file_writes")]
    public int CollectDataFileWrites { get; set; }

    /// <summary>If the sensor is configured to collect the user running a process</summary>
    [OsqueryColumn("collect_process_user_context")]
    public int CollectProcessUserContext { get; set; }

    /// <summary>Unknown</summary>
    [OsqueryColumn("collect_sensor_operations")]
    public int CollectSensorOperations { get; set; }

    /// <summary>Event file disk quota in MB</summary>
    [OsqueryColumn("log_file_disk_quota_mb")]
    public int LogFileDiskQuotaMb { get; set; }

    /// <summary>Event file disk quota in a percentage</summary>
    [OsqueryColumn("log_file_disk_quota_percentage")]
    public int LogFileDiskQuotaPercentage { get; set; }

    /// <summary>If the sensor is configured to report tamper events</summary>
    [OsqueryColumn("protection_disabled")]
    public int ProtectionDisabled { get; set; }

    /// <summary>IP address of the sensor</summary>
    [OsqueryColumn("sensor_ip_addr")]
    public string SensorIpAddr { get; set; } = "";

    /// <summary>Carbon Black server</summary>
    [OsqueryColumn("sensor_backend_server")]
    public string SensorBackendServer { get; set; } = "";

    /// <summary>Size in bytes of Carbon Black event files on disk</summary>
    [OsqueryColumn("event_queue")]
    public int EventQueue { get; set; }

    /// <summary>Size in bytes of binaries waiting to be sent to Carbon Black server</summary>
    [OsqueryColumn("binary_queue")]
    public int BinaryQueue { get; set; }

}
