// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Certificate Authorities installed in Keychains/ca-bundles. NOTE: osquery limits frequent access to keychain files on macOS. This limit is controlled by keychain_access_interval flag. On macOS, 'path' may point to either a keychain file or a DER/PEM-encoded certificate file; non-keychain files are parsed as DER/PEM.
/// </summary>
[OsqueryTable("certificates")]
public class Certificate
{
    /// <summary>Certificate CommonName</summary>
    [OsqueryColumn("common_name")]
    public string CommonName { get; set; } = "";

    /// <summary>Certificate distinguished name (deprecated, use subject2)</summary>
    [OsqueryColumn("subject")]
    public string Subject { get; set; } = "";

    /// <summary>Certificate issuer distinguished name (deprecated, use issuer2)</summary>
    [OsqueryColumn("issuer")]
    public string Issuer { get; set; } = "";

    /// <summary>1 if CA: true (certificate is an authority) else 0</summary>
    [OsqueryColumn("ca")]
    public int Ca { get; set; }

    /// <summary>1 if self-signed, else 0</summary>
    [OsqueryColumn("self_signed")]
    public int SelfSigned { get; set; }

    /// <summary>Lower bound of valid date</summary>
    [OsqueryColumn("not_valid_before")]
    public string NotValidBefore { get; set; } = "";

    /// <summary>Certificate expiration data</summary>
    [OsqueryColumn("not_valid_after")]
    public string NotValidAfter { get; set; } = "";

    /// <summary>Signing algorithm used</summary>
    [OsqueryColumn("signing_algorithm")]
    public string SigningAlgorithm { get; set; } = "";

    /// <summary>Key algorithm used</summary>
    [OsqueryColumn("key_algorithm")]
    public string KeyAlgorithm { get; set; } = "";

    /// <summary>Key size used for RSA/DSA, or curve name</summary>
    [OsqueryColumn("key_strength")]
    public string KeyStrength { get; set; } = "";

    /// <summary>Certificate key usage and extended key usage</summary>
    [OsqueryColumn("key_usage")]
    public string KeyUsage { get; set; } = "";

    /// <summary>SKID an optionally included SHA1</summary>
    [OsqueryColumn("subject_key_id")]
    public string SubjectKeyId { get; set; } = "";

    /// <summary>AKID an optionally included SHA1</summary>
    [OsqueryColumn("authority_key_id")]
    public string AuthorityKeyId { get; set; } = "";

    /// <summary>SHA1 hash of the raw certificate contents</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>Path to Keychain or PEM bundle</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Certificate serial number</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>SID</summary>
    [OsqueryColumn("sid")]
    public string Sid { get; set; } = "";

    /// <summary>Certificate system store location</summary>
    [OsqueryColumn("store_location")]
    public string StoreLocation { get; set; } = "";

    /// <summary>Certificate system store</summary>
    [OsqueryColumn("store")]
    public string Store { get; set; } = "";

    /// <summary>Username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Exists for service/user stores. Contains raw store id provided by WinAPI.</summary>
    [OsqueryColumn("store_id")]
    public string StoreId { get; set; } = "";

    /// <summary>Certificate issuer distinguished name</summary>
    [OsqueryColumn("issuer2")]
    public string Issuer2 { get; set; } = "";

    /// <summary>Certificate distinguished name</summary>
    [OsqueryColumn("subject2")]
    public string Subject2 { get; set; } = "";
}
