// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Display information pertaining to the chassis and its security status.
/// </summary>
[OsqueryTable("chassis_info")]
public class ChassisInfo
{
    /// <summary>If TRUE, the frame is equipped with an audible alarm.</summary>
    [OsqueryColumn("audible_alarm")]
    public string AudibleAlarm { get; set; } = "";

    /// <summary>If provided, gives a more detailed description of a detected security breach.</summary>
    [OsqueryColumn("breach_description")]
    public string BreachDescription { get; set; } = "";

    /// <summary>A comma-separated list of chassis types, such as Desktop or Laptop.</summary>
    [OsqueryColumn("chassis_types")]
    public string ChassisTypes { get; set; } = "";

    /// <summary>An extended description of the chassis if available.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>If TRUE, the frame is equipped with a lock.</summary>
    [OsqueryColumn("lock")]
    public string @Lock { get; set; } = "";

    /// <summary>The manufacturer of the chassis.</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>The model of the chassis.</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>The physical status of the chassis such as Breach Successful, Breach Attempted, etc.</summary>
    [OsqueryColumn("security_breach")]
    public string SecurityBreach { get; set; } = "";

    /// <summary>The serial number of the chassis.</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>The assigned asset tag number of the chassis.</summary>
    [OsqueryColumn("smbios_tag")]
    public string SmbiosTag { get; set; } = "";

    /// <summary>The Stock Keeping Unit number if available.</summary>
    [OsqueryColumn("sku")]
    public string Sku { get; set; } = "";

    /// <summary>If available, gives various operational or nonoperational statuses such as OK, Degraded, and Pred Fail.</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>If TRUE, the frame is equipped with a visual alarm.</summary>
    [OsqueryColumn("visible_alarm")]
    public string VisibleAlarm { get; set; } = "";
}
