// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Chocolatey packages installed in a system.
/// </summary>
[OsqueryTable("chocolatey_packages")]
public class ChocolateyPackage
{
    /// <summary>Package display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package-supplied version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package-supplied summary</summary>
    [OsqueryColumn("summary")]
    public string Summary { get; set; } = "";

    /// <summary>Optional package author</summary>
    [OsqueryColumn("author")]
    public string Author { get; set; } = "";

    /// <summary>License under which package is launched</summary>
    [OsqueryColumn("license")]
    public string License { get; set; } = "";

    /// <summary>Path at which this package resides</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
