// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Chrome browser extension content scripts.
/// </summary>
[OsqueryTable("chrome_extension_content_scripts")]
public class ChromeExtensionContentScript
{
    /// <summary>The browser type (Valid values: chrome, chromium, opera, yandex, brave)</summary>
    [OsqueryColumn("browser_type")]
    public string BrowserType { get; set; } = "";

    /// <summary>The local user that owns the extension</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Extension identifier</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Extension-supplied version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The content script used by the extension</summary>
    [OsqueryColumn("script")]
    public string Script { get; set; } = "";

    /// <summary>The pattern that the script is matched against</summary>
    [OsqueryColumn("match")]
    public string Match { get; set; } = "";

    /// <summary>The profile path</summary>
    [OsqueryColumn("profile_path")]
    public string ProfilePath { get; set; } = "";

    /// <summary>Path to extension folder</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>1 if this extension is referenced by the Preferences file of the profile</summary>
    [OsqueryColumn("referenced")]
    public long Referenced { get; set; }
}
