// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Chrome-based browser extensions.
/// </summary>
[OsqueryTable("chrome_extensions")]
public class ChromeExtension
{
    /// <summary>The browser type (Valid values: chrome, chromium, opera, yandex, brave, edge, edge_beta)</summary>
    [OsqueryColumn("browser_type")]
    public string BrowserType { get; set; } = "";

    /// <summary>The local user that owns the extension</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Extension display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The name of the Chrome profile that contains this extension</summary>
    [OsqueryColumn("profile")]
    public string Profile { get; set; } = "";

    /// <summary>The profile path</summary>
    [OsqueryColumn("profile_path")]
    public string ProfilePath { get; set; } = "";

    /// <summary>Extension identifier, as specified by the preferences file. Empty if the extension is not in the profile.</summary>
    [OsqueryColumn("referenced_identifier")]
    public string ReferencedIdentifier { get; set; } = "";

    /// <summary>Extension identifier, computed from its manifest. Empty in case of error.</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Extension-supplied version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Extension-optional description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Default locale supported by extension</summary>
    [OsqueryColumn("default_locale")]
    public string DefaultLocale { get; set; } = "";

    /// <summary>Current locale supported by extension</summary>
    [OsqueryColumn("current_locale")]
    public string CurrentLocale { get; set; } = "";

    /// <summary>Extension-supplied update URI</summary>
    [OsqueryColumn("update_url")]
    public string UpdateUrl { get; set; } = "";

    /// <summary>Optional extension author</summary>
    [OsqueryColumn("author")]
    public string Author { get; set; } = "";

    /// <summary>1 If extension is persistent across all tabs else 0</summary>
    [OsqueryColumn("persistent")]
    public int Persistent { get; set; }

    /// <summary>Path to extension folder</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The permissions required by the extension</summary>
    [OsqueryColumn("permissions")]
    public string Permissions { get; set; } = "";

    /// <summary>The JSON-encoded permissions required by the extension</summary>
    [OsqueryColumn("permissions_json")]
    public string PermissionsJson { get; set; } = "";

    /// <summary>The permissions optionally required by the extensions</summary>
    [OsqueryColumn("optional_permissions")]
    public string OptionalPermissions { get; set; } = "";

    /// <summary>The JSON-encoded permissions optionally required by the extensions</summary>
    [OsqueryColumn("optional_permissions_json")]
    public string OptionalPermissionsJson { get; set; } = "";

    /// <summary>The SHA256 hash of the manifest.json file</summary>
    [OsqueryColumn("manifest_hash")]
    public string ManifestHash { get; set; } = "";

    /// <summary>1 if this extension is referenced by the Preferences file of the profile</summary>
    [OsqueryColumn("referenced")]
    public long Referenced { get; set; }

    /// <summary>True if this extension was installed from the web store</summary>
    [OsqueryColumn("from_webstore")]
    public string FromWebstore { get; set; } = "";

    /// <summary>1 if this extension is enabled</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Extension install time, in its original Webkit format</summary>
    [OsqueryColumn("install_time")]
    public string InstallTime { get; set; } = "";

    /// <summary>Extension install time, converted to unix time</summary>
    [OsqueryColumn("install_timestamp")]
    public long InstallTimestamp { get; set; }

    /// <summary>The manifest file of the extension</summary>
    [OsqueryColumn("manifest_json")]
    public string ManifestJson { get; set; } = "";

    /// <summary>The extension key, from the manifest file</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";
}
