// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Provides the overall system's network state.
/// </summary>
[OsqueryTable("connectivity")]
public class Connectivity
{
    /// <summary>True if the all interfaces are not connected to any network</summary>
    [OsqueryColumn("disconnected")]
    public int Disconnected { get; set; }

    /// <summary>True if any interface is connected via IPv4, but has seen no traffic</summary>
    [OsqueryColumn("ipv4_no_traffic")]
    public int Ipv4NoTraffic { get; set; }

    /// <summary>True if any interface is connected via IPv6, but has seen no traffic</summary>
    [OsqueryColumn("ipv6_no_traffic")]
    public int Ipv6NoTraffic { get; set; }

    /// <summary>True if any interface is connected to the local subnet via IPv4</summary>
    [OsqueryColumn("ipv4_subnet")]
    public int Ipv4Subnet { get; set; }

    /// <summary>True if any interface is connected to a routed network via IPv4</summary>
    [OsqueryColumn("ipv4_local_network")]
    public int Ipv4LocalNetwork { get; set; }

    /// <summary>True if any interface is connected to the Internet via IPv4</summary>
    [OsqueryColumn("ipv4_internet")]
    public int Ipv4Internet { get; set; }

    /// <summary>True if any interface is connected to the local subnet via IPv6</summary>
    [OsqueryColumn("ipv6_subnet")]
    public int Ipv6Subnet { get; set; }

    /// <summary>True if any interface is connected to a routed network via IPv6</summary>
    [OsqueryColumn("ipv6_local_network")]
    public int Ipv6LocalNetwork { get; set; }

    /// <summary>True if any interface is connected to the Internet via IPv6</summary>
    [OsqueryColumn("ipv6_internet")]
    public int Ipv6Internet { get; set; }

}
