// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve cpu hardware info of the machine.
/// </summary>
[OsqueryTable("cpu_info")]
public class CpuInfo
{
    /// <summary>The DeviceID of the CPU.</summary>
    [OsqueryColumn("device_id")]
    public string DeviceId { get; set; } = "";

    /// <summary>The model of the CPU.</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>The manufacturer of the CPU.</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>The processor type, such as Central, Math, or Video.</summary>
    [OsqueryColumn("processor_type")]
    public string ProcessorType { get; set; } = "";

    /// <summary>The current operating status of the CPU.</summary>
    [OsqueryColumn("cpu_status")]
    public int CpuStatus { get; set; }

    /// <summary>The number of cores of the CPU.</summary>
    [OsqueryColumn("number_of_cores")]
    public string NumberOfCores { get; set; } = "";

    /// <summary>The number of logical processors of the CPU.</summary>
    [OsqueryColumn("logical_processors")]
    public int LogicalProcessors { get; set; }

    /// <summary>The width of the CPU address bus.</summary>
    [OsqueryColumn("address_width")]
    public string AddressWidth { get; set; } = "";

    /// <summary>The current frequency of the CPU.</summary>
    [OsqueryColumn("current_clock_speed")]
    public int CurrentClockSpeed { get; set; }

    /// <summary>The maximum possible frequency of the CPU.</summary>
    [OsqueryColumn("max_clock_speed")]
    public int MaxClockSpeed { get; set; }

    /// <summary>The assigned socket on the board for the given CPU.</summary>
    [OsqueryColumn("socket_designation")]
    public string SocketDesignation { get; set; } = "";

    /// <summary>The availability and status of the CPU.</summary>
    [OsqueryColumn("availability")]
    public string Availability { get; set; } = "";

    /// <summary>The current percentage of utilization of the CPU.</summary>
    [OsqueryColumn("load_percentage")]
    public int LoadPercentage { get; set; }

    /// <summary>The number of efficiency cores of the CPU. Only available on Apple Silicon</summary>
    [OsqueryColumn("number_of_efficiency_cores")]
    public int NumberOfEfficiencyCores { get; set; }

    /// <summary>The number of performance cores of the CPU. Only available on Apple Silicon</summary>
    [OsqueryColumn("number_of_performance_cores")]
    public int NumberOfPerformanceCores { get; set; }
}
