// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Useful CPU features from the cpuid ASM call.
/// </summary>
[OsqueryTable("cpuid")]
public class Cpuid
{
    /// <summary>Present feature flags</summary>
    [OsqueryColumn("feature")]
    public string Feature { get; set; } = "";

    /// <summary>Bit value or string</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>Register used to for feature value</summary>
    [OsqueryColumn("output_register")]
    public string OutputRegister { get; set; } = "";

    /// <summary>Bit in register value for feature value</summary>
    [OsqueryColumn("output_bit")]
    public int OutputBit { get; set; }

    /// <summary>Value of EAX used</summary>
    [OsqueryColumn("input_eax")]
    public string InputEax { get; set; } = "";
}
