// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Application, System, and Mobile App crash logs.
/// </summary>
[OsqueryTable("crashes")]
public class Crashe
{
    /// <summary>Type of crash log</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Process (or thread) ID of the crashed process</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Path to the crashed process</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Location of log file</summary>
    [OsqueryColumn("crash_path")]
    public string CrashPath { get; set; } = "";

    /// <summary>Identifier of the crashed process</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Version info of the crashed process</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Parent PID of the crashed process</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Process responsible for the crashed process</summary>
    [OsqueryColumn("responsible")]
    public string Responsible { get; set; } = "";

    /// <summary>User ID of the crashed process</summary>
    [OsqueryColumn("uid")]
    public int Uid { get; set; }

    /// <summary>Date/Time at which the crash occurred</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>Thread ID which crashed</summary>
    [OsqueryColumn("crashed_thread")]
    public long CrashedThread { get; set; }

    /// <summary>Most recent frame from the stack trace</summary>
    [OsqueryColumn("stack_trace")]
    public string StackTrace { get; set; } = "";

    /// <summary>Exception type of the crash</summary>
    [OsqueryColumn("exception_type")]
    public string ExceptionType { get; set; } = "";

    /// <summary>Exception codes from the crash</summary>
    [OsqueryColumn("exception_codes")]
    public string ExceptionCodes { get; set; } = "";

    /// <summary>Exception notes from the crash</summary>
    [OsqueryColumn("exception_notes")]
    public string ExceptionNotes { get; set; } = "";

    /// <summary>The value of the system registers</summary>
    [OsqueryColumn("registers")]
    public string Registers { get; set; } = "";

}
