// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Line parsed values from system and user cron/tab.
/// </summary>
[OsqueryTable("crontab")]
public class Crontab
{
    /// <summary>The job @event name (rare)</summary>
    [OsqueryColumn("event")]
    public string @Event { get; set; } = "";

    /// <summary>The exact minute for the job</summary>
    [OsqueryColumn("minute")]
    public string Minute { get; set; } = "";

    /// <summary>The hour of the day for the job</summary>
    [OsqueryColumn("hour")]
    public string Hour { get; set; } = "";

    /// <summary>The day of the month for the job</summary>
    [OsqueryColumn("day_of_month")]
    public string DayOfMonth { get; set; } = "";

    /// <summary>The month of the year for the job</summary>
    [OsqueryColumn("month")]
    public string Month { get; set; } = "";

    /// <summary>The day of the week for the job</summary>
    [OsqueryColumn("day_of_week")]
    public string DayOfWeek { get; set; } = "";

    /// <summary>Raw command string</summary>
    [OsqueryColumn("command")]
    public string Command { get; set; } = "";

    /// <summary>File parsed</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
