// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Returns all completed print jobs from cups.
/// </summary>
[OsqueryTable("cups_jobs")]
public class CupsJob
{
    /// <summary>Title of the printed job</summary>
    [OsqueryColumn("title")]
    public string Title { get; set; } = "";

    /// <summary>The printer the job was sent to</summary>
    [OsqueryColumn("destination")]
    public string Destination { get; set; } = "";

    /// <summary>The user who printed the job</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>The format of the print job</summary>
    [OsqueryColumn("format")]
    public string Format { get; set; } = "";

    /// <summary>The size of the print job</summary>
    [OsqueryColumn("size")]
    public int Size { get; set; }

    /// <summary>When the job completed printing</summary>
    [OsqueryColumn("completed_time")]
    public int CompletedTime { get; set; }

    /// <summary>How long the job took to process</summary>
    [OsqueryColumn("processing_time")]
    public int ProcessingTime { get; set; }

    /// <summary>When the print request was initiated</summary>
    [OsqueryColumn("creation_time")]
    public int CreationTime { get; set; }

}
