// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Inspect TLS certificates by connecting to input hostnames.
/// </summary>
[OsqueryTable("curl_certificate")]
public class CurlCertificate
{
    /// <summary>Hostname to CURL (domain[:port], e.g. osquery.io)</summary>
    [OsqueryColumn("hostname")]
    public string Hostname { get; set; } = "";

    /// <summary>Common name of company issued to</summary>
    [OsqueryColumn("common_name")]
    public string CommonName { get; set; } = "";

    /// <summary>Organization issued to</summary>
    [OsqueryColumn("organization")]
    public string Organization { get; set; } = "";

    /// <summary>Organization unit issued to</summary>
    [OsqueryColumn("organization_unit")]
    public string OrganizationUnit { get; set; } = "";

    /// <summary>Certificate serial number</summary>
    [OsqueryColumn("serial_number")]
    public string SerialNumber { get; set; } = "";

    /// <summary>Issuer common name</summary>
    [OsqueryColumn("issuer_common_name")]
    public string IssuerCommonName { get; set; } = "";

    /// <summary>Issuer organization</summary>
    [OsqueryColumn("issuer_organization")]
    public string IssuerOrganization { get; set; } = "";

    /// <summary>Issuer organization unit</summary>
    [OsqueryColumn("issuer_organization_unit")]
    public string IssuerOrganizationUnit { get; set; } = "";

    /// <summary>Period of validity start date</summary>
    [OsqueryColumn("valid_from")]
    public string ValidFrom { get; set; } = "";

    /// <summary>Period of validity end date</summary>
    [OsqueryColumn("valid_to")]
    public string ValidTo { get; set; } = "";

    /// <summary>SHA-256 fingerprint</summary>
    [OsqueryColumn("sha256_fingerprint")]
    public string Sha256Fingerprint { get; set; } = "";

    /// <summary>SHA1 fingerprint</summary>
    [OsqueryColumn("sha1_fingerprint")]
    public string Sha1Fingerprint { get; set; } = "";

    /// <summary>Version Number</summary>
    [OsqueryColumn("version")]
    public int Version { get; set; }

    /// <summary>Signature Algorithm</summary>
    [OsqueryColumn("signature_algorithm")]
    public string SignatureAlgorithm { get; set; } = "";

    /// <summary>Signature</summary>
    [OsqueryColumn("signature")]
    public string Signature { get; set; } = "";

    /// <summary>Subject Key Identifier</summary>
    [OsqueryColumn("subject_key_identifier")]
    public string SubjectKeyIdentifier { get; set; } = "";

    /// <summary>Authority Key Identifier</summary>
    [OsqueryColumn("authority_key_identifier")]
    public string AuthorityKeyIdentifier { get; set; } = "";

    /// <summary>Usage of key in certificate</summary>
    [OsqueryColumn("key_usage")]
    public string KeyUsage { get; set; } = "";

    /// <summary>Extended usage of key in certificate</summary>
    [OsqueryColumn("extended_key_usage")]
    public string ExtendedKeyUsage { get; set; } = "";

    /// <summary>Certificate Policies</summary>
    [OsqueryColumn("policies")]
    public string Policies { get; set; } = "";

    /// <summary>Subject Alternative Name</summary>
    [OsqueryColumn("subject_alternative_names")]
    public string SubjectAlternativeNames { get; set; } = "";

    /// <summary>Issuer Alternative Name</summary>
    [OsqueryColumn("issuer_alternative_names")]
    public string IssuerAlternativeNames { get; set; } = "";

    /// <summary>Authority Information Access</summary>
    [OsqueryColumn("info_access")]
    public string InfoAccess { get; set; } = "";

    /// <summary>Subject Information Access</summary>
    [OsqueryColumn("subject_info_access")]
    public string SubjectInfoAccess { get; set; } = "";

    /// <summary>Policy Mappings</summary>
    [OsqueryColumn("policy_mappings")]
    public string PolicyMappings { get; set; } = "";

    /// <summary>1 if the certificate has expired, 0 otherwise</summary>
    [OsqueryColumn("has_expired")]
    public int HasExpired { get; set; }

    /// <summary>Basic Constraints</summary>
    [OsqueryColumn("basic_constraint")]
    public string BasicConstraint { get; set; } = "";

    /// <summary>Name Constraints</summary>
    [OsqueryColumn("name_constraints")]
    public string NameConstraints { get; set; } = "";

    /// <summary>Policy Constraints</summary>
    [OsqueryColumn("policy_constraints")]
    public string PolicyConstraints { get; set; } = "";

    /// <summary>Set this value to '1' to dump certificate</summary>
    [OsqueryColumn("dump_certificate")]
    public int DumpCertificate { get; set; }

    /// <summary>Set this value to the timeout in seconds to complete the TLS handshake (default 4s, use 0 for no timeout)</summary>
    [OsqueryColumn("timeout")]
    public int Timeout { get; set; }

    /// <summary>Certificate PEM format</summary>
    [OsqueryColumn("pem")]
    public string Pem { get; set; } = "";

}
