// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// The installed DEB package database.
/// </summary>
[OsqueryTable("deb_packages")]
public class DebPackage
{
    /// <summary>Package name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package source</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Package size in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Package architecture</summary>
    [OsqueryColumn("arch")]
    public string Arch { get; set; } = "";

    /// <summary>Package revision</summary>
    [OsqueryColumn("revision")]
    public string Revision { get; set; } = "";

    /// <summary>Package status</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>Package maintainer</summary>
    [OsqueryColumn("maintainer")]
    public string Maintainer { get; set; } = "";

    /// <summary>Package section</summary>
    [OsqueryColumn("section")]
    public string Section { get; set; } = "";

    /// <summary>Package priority</summary>
    [OsqueryColumn("priority")]
    public string Priority { get; set; } = "";

    /// <summary>libdpkg admindir. Defaults to /var/lib/dpkg</summary>
    [OsqueryColumn("admindir")]
    public string Admindir { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";
}
