// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Installed files from DEB packages that are currently installed on the system.
/// </summary>
[OsqueryTable("deb_package_files")]
public class DebPackageFile
{
    /// <summary>DEB package name</summary>
    [OsqueryColumn("package")]
    public string Package { get; set; } = "";

    /// <summary>File path within the package</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>libdpkg admindir. Defaults to /var/lib/dpkg</summary>
    [OsqueryColumn("admindir")]
    public string Admindir { get; set; } = "";
}
