// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Default environment variables and values.
/// </summary>
[OsqueryTable("default_environment")]
public class DefaultEnvironment
{
    /// <summary>Name of the environment variable</summary>
    [OsqueryColumn("variable")]
    public string Variable { get; set; } = "";

    /// <summary>Value of the environment variable</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>1 if the variable needs expanding, 0 otherwise</summary>
    [OsqueryColumn("expand")]
    public int Expand { get; set; }
}
