// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Similar to the hash table, but use TSK and allow block address access.
/// </summary>
[OsqueryTable("device_hash")]
public class DeviceHash
{
    /// <summary>Absolute file path to device node</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>A partition number</summary>
    [OsqueryColumn("partition")]
    public string Partition { get; set; } = "";

    /// <summary>Filesystem inode number</summary>
    [OsqueryColumn("inode")]
    public long Inode { get; set; }

    /// <summary>MD5 hash of provided inode data</summary>
    [OsqueryColumn("md5")]
    public string Md5 { get; set; } = "";

    /// <summary>SHA1 hash of provided inode data</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>SHA256 hash of provided inode data</summary>
    [OsqueryColumn("sha256")]
    public string Sha256 { get; set; } = "";
}
