// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve DeviceGuard info of the machine.
/// </summary>
[OsqueryTable("deviceguard_status")]
public class DeviceguardStatus
{
    /// <summary>The version number of the Device Guard build.</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The instance ID of Device Guard.</summary>
    [OsqueryColumn("instance_identifier")]
    public string InstanceIdentifier { get; set; } = "";

    /// <summary>The status of the virtualization based security settings. Returns UNKNOWN if an error is encountered.</summary>
    [OsqueryColumn("vbs_status")]
    public string VbsStatus { get; set; } = "";

    /// <summary>The status of the code integrity policy enforcement settings. Returns UNKNOWN if an error is encountered.</summary>
    [OsqueryColumn("code_integrity_policy_enforcement_status")]
    public string CodeIntegrityPolicyEnforcementStatus { get; set; } = "";

    /// <summary>The list of configured Device Guard services. Returns UNKNOWN if an error is encountered.</summary>
    [OsqueryColumn("configured_security_services")]
    public string ConfiguredSecurityServices { get; set; } = "";

    /// <summary>The list of running Device Guard services. Returns UNKNOWN if an error is encountered.</summary>
    [OsqueryColumn("running_security_services")]
    public string RunningSecurityServices { get; set; } = "";

    /// <summary>The status of the User Mode Code Integrity security settings. Returns UNKNOWN if an error is encountered.</summary>
    [OsqueryColumn("umci_policy_status")]
    public string UmciPolicyStatus { get; set; } = "";
}
