// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Use TSK to enumerate details about partitions on a disk device.
/// </summary>
[OsqueryTable("device_partitions")]
public class DevicePartition
{
    /// <summary>Absolute file path to device node</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>A partition number or description</summary>
    [OsqueryColumn("partition")]
    public int Partition { get; set; }

    /// <summary>The partition name as stored in the partition table</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Filesystem type if recognized, otherwise, 'meta', 'normal', or 'unallocated'</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Byte offset from the start of the volume</summary>
    [OsqueryColumn("offset")]
    public long Offset { get; set; }

    /// <summary>Byte size of each block</summary>
    [OsqueryColumn("blocks_size")]
    public long BlocksSize { get; set; }

    /// <summary>Number of blocks</summary>
    [OsqueryColumn("blocks")]
    public long Blocks { get; set; }

    /// <summary>Number of meta nodes</summary>
    [OsqueryColumn("inodes")]
    public long Inodes { get; set; }

    /// <summary>Value that describes the partition (TSK_VS_PART_FLAG_ENUM)</summary>
    [OsqueryColumn("flags")]
    public int Flags { get; set; }

}
