// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Similar to the file table, but use TSK and allow block address access.
/// </summary>
[OsqueryTable("device_file")]
public class DeviceFile
{
    /// <summary>Absolute file path to device node</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>A partition number</summary>
    [OsqueryColumn("partition")]
    public string Partition { get; set; } = "";

    /// <summary>A logical path within the device node</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Name portion of file path</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>Filesystem inode number</summary>
    [OsqueryColumn("inode")]
    public long Inode { get; set; }

    /// <summary>Owning user ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Owning group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Permission bits</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Size of file in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Block size of filesystem</summary>
    [OsqueryColumn("block_size")]
    public int BlockSize { get; set; }

    /// <summary>Last access time</summary>
    [OsqueryColumn("atime")]
    public long Atime { get; set; }

    /// <summary>Last modification time</summary>
    [OsqueryColumn("mtime")]
    public long Mtime { get; set; }

    /// <summary>Creation time</summary>
    [OsqueryColumn("ctime")]
    public long Ctime { get; set; }

    /// <summary>Number of hard links</summary>
    [OsqueryColumn("hard_links")]
    public int HardLinks { get; set; }

    /// <summary>File status</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";
}
