// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Disk encryption status and information.
/// </summary>
[OsqueryTable("disk_encryption")]
public class DiskEncryption
{
    /// <summary>Disk name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Disk Universally Unique Identifier</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>1 If encrypted: true (disk is encrypted), else 0</summary>
    [OsqueryColumn("encrypted")]
    public int Encrypted { get; set; }

    /// <summary>Description of cipher type and mode if available</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Disk encryption status with one of following values: encrypted | not encrypted | undefined</summary>
    [OsqueryColumn("encryption_status")]
    public string EncryptionStatus { get; set; } = "";

    /// <summary>Currently authenticated user if available</summary>
    [OsqueryColumn("uid")]
    public string Uid { get; set; } = "";

    /// <summary>UUID of authenticated user if available</summary>
    [OsqueryColumn("user_uuid")]
    public string UserUuid { get; set; } = "";

    /// <summary>FileVault status with one of following values: on | off | unknown</summary>
    [OsqueryColumn("filevault_status")]
    public string FilevaultStatus { get; set; } = "";

}
