// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve basic information about the physical disks of a system.
/// </summary>
[OsqueryTable("disk_info")]
public class DiskInfo
{
    /// <summary>Number of detected partitions on disk.</summary>
    [OsqueryColumn("partitions")]
    public int Partitions { get; set; }

    /// <summary>Physical drive number of the disk.</summary>
    [OsqueryColumn("disk_index")]
    public int DiskIndex { get; set; }

    /// <summary>The interface type of the disk.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>The unique identifier of the drive on the system.</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>The unique identifier of the drive on the system.</summary>
    [OsqueryColumn("pnp_device_id")]
    public string PnpDeviceId { get; set; } = "";

    /// <summary>Size of the disk.</summary>
    [OsqueryColumn("disk_size")]
    public long DiskSize { get; set; }

    /// <summary>The manufacturer of the disk.</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>Hard drive model.</summary>
    [OsqueryColumn("hardware_model")]
    public string HardwareModel { get; set; } = "";

    /// <summary>The label of the disk object.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The serial number of the disk.</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>The OS's description of the disk.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

}
