// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track DMG disk image events (appearance/disappearance) when opened.
/// </summary>
[OsqueryTable("disk_events")]
public class DiskEvent
{
    /// <summary>Appear or disappear</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>Path of the DMG file accessed</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Disk event name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Disk event BSD name</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>UUID of the volume inside DMG if available</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Size of partition in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>1 if ejectable, 0 if not</summary>
    [OsqueryColumn("ejectable")]
    public int Ejectable { get; set; }

    /// <summary>1 if mountable, 0 if not</summary>
    [OsqueryColumn("mountable")]
    public int Mountable { get; set; }

    /// <summary>1 if writable, 0 if not</summary>
    [OsqueryColumn("writable")]
    public int Writable { get; set; }

    /// <summary>Disk event content</summary>
    [OsqueryColumn("content")]
    public string Content { get; set; } = "";

    /// <summary>Disk event media name string</summary>
    [OsqueryColumn("media_name")]
    public string MediaName { get; set; } = "";

    /// <summary>Disk event vendor string</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Filesystem if available</summary>
    [OsqueryColumn("filesystem")]
    public string Filesystem { get; set; } = "";

    /// <summary>UDIF Master checksum if available (CRC32)</summary>
    [OsqueryColumn("checksum")]
    public string Checksum { get; set; } = "";

    /// <summary>Time of appearance/disappearance in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";
}
