// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// DNS lookups performed through the Windows DNS stack.
/// </summary>
[OsqueryTable("dns_lookup_events")]
public class DnsLookupEvent
{
    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public int Eid { get; set; }

    /// <summary>Event timestamp in Unix format</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event timestamp in Windows format</summary>
    [OsqueryColumn("time_windows")]
    public long TimeWindows { get; set; }

    /// <summary>Event timestamp in DATETIME format</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>Process ID of process making the lookup</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Path to binary of process making the lookup (sometimes unavailable for very short-lived processes)</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>User rights - primary token username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Name being queried in lookup</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>DNS record type of lookup as string</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Integer type ID for record type</summary>
    [OsqueryColumn("type_id")]
    public int TypeId { get; set; }

    /// <summary>Response status code</summary>
    [OsqueryColumn("status")]
    public int Status { get; set; }

    /// <summary>Results returned by lookup</summary>
    [OsqueryColumn("response")]
    public string Response { get; set; } = "";
}
