// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker version information.
/// </summary>
[OsqueryTable("docker_version")]
public class DockerVersion
{
    /// <summary>Docker version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>API version</summary>
    [OsqueryColumn("api_version")]
    public string ApiVersion { get; set; } = "";

    /// <summary>Minimum API version supported</summary>
    [OsqueryColumn("min_api_version")]
    public string MinApiVersion { get; set; } = "";

    /// <summary>Docker build git commit</summary>
    [OsqueryColumn("git_commit")]
    public string GitCommit { get; set; } = "";

    /// <summary>Go version</summary>
    [OsqueryColumn("go_version")]
    public string GoVersion { get; set; } = "";

    /// <summary>Operating system</summary>
    [OsqueryColumn("os")]
    public string Os { get; set; } = "";

    /// <summary>Hardware architecture</summary>
    [OsqueryColumn("arch")]
    public string Arch { get; set; } = "";

    /// <summary>Kernel version</summary>
    [OsqueryColumn("kernel_version")]
    public string KernelVersion { get; set; } = "";

    /// <summary>Build time</summary>
    [OsqueryColumn("build_time")]
    public string BuildTime { get; set; } = "";

}
