// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker containers information.
/// </summary>
[OsqueryTable("docker_containers")]
public class DockerContainer
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Container name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Docker image (name) used to launch this container</summary>
    [OsqueryColumn("image")]
    public string Image { get; set; } = "";

    /// <summary>Docker image ID</summary>
    [OsqueryColumn("image_id")]
    public string ImageId { get; set; } = "";

    /// <summary>Command with arguments</summary>
    [OsqueryColumn("command")]
    public string Command { get; set; } = "";

    /// <summary>Time of creation as UNIX time</summary>
    [OsqueryColumn("created")]
    public long Created { get; set; }

    /// <summary>Container state (created, restarting, running, removing, paused, exited, dead)</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Container status information</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>Identifier of the initial process</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Container path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Container entrypoint(s)</summary>
    [OsqueryColumn("config_entrypoint")]
    public string ConfigEntrypoint { get; set; } = "";

    /// <summary>Container start time as string</summary>
    [OsqueryColumn("started_at")]
    public string StartedAt { get; set; } = "";

    /// <summary>Container finish time as string</summary>
    [OsqueryColumn("finished_at")]
    public string FinishedAt { get; set; } = "";

    /// <summary>Is the container privileged</summary>
    [OsqueryColumn("privileged")]
    public int Privileged { get; set; }

    /// <summary>List of container security options</summary>
    [OsqueryColumn("security_options")]
    public string SecurityOptions { get; set; } = "";

    /// <summary>Container environmental variables</summary>
    [OsqueryColumn("env_variables")]
    public string EnvVariables { get; set; } = "";

    /// <summary>Is the root filesystem mounted as read only</summary>
    [OsqueryColumn("readonly_rootfs")]
    public int ReadonlyRootfs { get; set; }

    /// <summary>cgroup namespace</summary>
    [OsqueryColumn("cgroup_namespace")]
    public string CgroupNamespace { get; set; } = "";

    /// <summary>IPC namespace</summary>
    [OsqueryColumn("ipc_namespace")]
    public string IpcNamespace { get; set; } = "";

    /// <summary>Mount namespace</summary>
    [OsqueryColumn("mnt_namespace")]
    public string MntNamespace { get; set; } = "";

    /// <summary>Network namespace</summary>
    [OsqueryColumn("net_namespace")]
    public string NetNamespace { get; set; } = "";

    /// <summary>PID namespace</summary>
    [OsqueryColumn("pid_namespace")]
    public string PidNamespace { get; set; } = "";

    /// <summary>User namespace</summary>
    [OsqueryColumn("user_namespace")]
    public string UserNamespace { get; set; } = "";

    /// <summary>UTS namespace</summary>
    [OsqueryColumn("uts_namespace")]
    public string UtsNamespace { get; set; } = "";
}
