// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Changes to files or directories on container's filesystem.
/// </summary>
[OsqueryTable("docker_container_fs_changes")]
public class DockerContainerFsChange
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>FIle or directory path relative to rootfs</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Type of change: C:Modified, A:Added, D:Deleted</summary>
    [OsqueryColumn("change_type")]
    public string ChangeType { get; set; } = "";
}
