// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker system information.
/// </summary>
[OsqueryTable("docker_info")]
public class DockerInfo
{
    /// <summary>Docker system ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Total number of containers</summary>
    [OsqueryColumn("containers")]
    public int Containers { get; set; }

    /// <summary>Number of containers currently running</summary>
    [OsqueryColumn("containers_running")]
    public int ContainersRunning { get; set; }

    /// <summary>Number of containers in paused state</summary>
    [OsqueryColumn("containers_paused")]
    public int ContainersPaused { get; set; }

    /// <summary>Number of containers in stopped state</summary>
    [OsqueryColumn("containers_stopped")]
    public int ContainersStopped { get; set; }

    /// <summary>Number of images</summary>
    [OsqueryColumn("images")]
    public int Images { get; set; }

    /// <summary>Storage driver</summary>
    [OsqueryColumn("storage_driver")]
    public string StorageDriver { get; set; } = "";

    /// <summary>1 if memory limit support is enabled. 0 otherwise</summary>
    [OsqueryColumn("memory_limit")]
    public int MemoryLimit { get; set; }

    /// <summary>1 if swap limit support is enabled. 0 otherwise</summary>
    [OsqueryColumn("swap_limit")]
    public int SwapLimit { get; set; }

    /// <summary>1 if kernel memory limit support is enabled. 0 otherwise</summary>
    [OsqueryColumn("kernel_memory")]
    public int KernelMemory { get; set; }

    /// <summary>1 if CPU Completely Fair Scheduler (CFS) period support is enabled. 0 otherwise</summary>
    [OsqueryColumn("cpu_cfs_period")]
    public int CpuCfsPeriod { get; set; }

    /// <summary>1 if CPU Completely Fair Scheduler (CFS) quota support is enabled. 0 otherwise</summary>
    [OsqueryColumn("cpu_cfs_quota")]
    public int CpuCfsQuota { get; set; }

    /// <summary>1 if CPU share weighting support is enabled. 0 otherwise</summary>
    [OsqueryColumn("cpu_shares")]
    public int CpuShares { get; set; }

    /// <summary>1 if CPU set selection support is enabled. 0 otherwise</summary>
    [OsqueryColumn("cpu_set")]
    public int CpuSet { get; set; }

    /// <summary>1 if IPv4 forwarding is enabled. 0 otherwise</summary>
    [OsqueryColumn("ipv4_forwarding")]
    public int Ipv4Forwarding { get; set; }

    /// <summary>1 if bridge netfilter iptables is enabled. 0 otherwise</summary>
    [OsqueryColumn("bridge_nf_iptables")]
    public int BridgeNfIptables { get; set; }

    /// <summary>1 if bridge netfilter ip6tables is enabled. 0 otherwise</summary>
    [OsqueryColumn("bridge_nf_ip6tables")]
    public int BridgeNfIp6Tables { get; set; }

    /// <summary>1 if Out-of-memory kill is disabled. 0 otherwise</summary>
    [OsqueryColumn("oom_kill_disable")]
    public int OomKillDisable { get; set; }

    /// <summary>Logging driver</summary>
    [OsqueryColumn("logging_driver")]
    public string LoggingDriver { get; set; } = "";

    /// <summary>Control groups driver</summary>
    [OsqueryColumn("cgroup_driver")]
    public string CgroupDriver { get; set; } = "";

    /// <summary>Kernel version</summary>
    [OsqueryColumn("kernel_version")]
    public string KernelVersion { get; set; } = "";

    /// <summary>Operating system</summary>
    [OsqueryColumn("os")]
    public string Os { get; set; } = "";

    /// <summary>Operating system type</summary>
    [OsqueryColumn("os_type")]
    public string OsType { get; set; } = "";

    /// <summary>Hardware architecture</summary>
    [OsqueryColumn("architecture")]
    public string Architecture { get; set; } = "";

    /// <summary>Number of CPUs</summary>
    [OsqueryColumn("cpus")]
    public int Cpus { get; set; }

    /// <summary>Total memory</summary>
    [OsqueryColumn("memory")]
    public long Memory { get; set; }

    /// <summary>HTTP proxy</summary>
    [OsqueryColumn("http_proxy")]
    public string HttpProxy { get; set; } = "";

    /// <summary>HTTPS proxy</summary>
    [OsqueryColumn("https_proxy")]
    public string HttpsProxy { get; set; } = "";

    /// <summary>Comma-separated list of domain extensions proxy should not be used for</summary>
    [OsqueryColumn("no_proxy")]
    public string NoProxy { get; set; } = "";

    /// <summary>Name of the docker host</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Server version</summary>
    [OsqueryColumn("server_version")]
    public string ServerVersion { get; set; } = "";

    /// <summary>Docker root directory</summary>
    [OsqueryColumn("root_dir")]
    public string RootDir { get; set; } = "";
}
