// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker networks information.
/// </summary>
[OsqueryTable("docker_networks")]
public class DockerNetwork
{
    /// <summary>Network ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Network name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Network driver</summary>
    [OsqueryColumn("driver")]
    public string Driver { get; set; } = "";

    /// <summary>Time of creation as UNIX time</summary>
    [OsqueryColumn("created")]
    public long Created { get; set; }

    /// <summary>1 if IPv6 is enabled on this network. 0 otherwise</summary>
    [OsqueryColumn("enable_ipv6")]
    public int EnableIpv6 { get; set; }

    /// <summary>Network subnet</summary>
    [OsqueryColumn("subnet")]
    public string Subnet { get; set; } = "";

    /// <summary>Network gateway</summary>
    [OsqueryColumn("gateway")]
    public string Gateway { get; set; } = "";
}
