// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker container processes.
/// </summary>
[OsqueryTable("docker_container_processes")]
public class DockerContainerProcess
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>The process path or shorthand argv[0]</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Complete argv</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>Process state</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Effective user ID</summary>
    [OsqueryColumn("euid")]
    public long Euid { get; set; }

    /// <summary>Effective group ID</summary>
    [OsqueryColumn("egid")]
    public long Egid { get; set; }

    /// <summary>Saved user ID</summary>
    [OsqueryColumn("suid")]
    public long Suid { get; set; }

    /// <summary>Saved group ID</summary>
    [OsqueryColumn("sgid")]
    public long Sgid { get; set; }

    /// <summary>Bytes of unpageable memory used by process</summary>
    [OsqueryColumn("wired_size")]
    public long WiredSize { get; set; }

    /// <summary>Bytes of private memory used by process</summary>
    [OsqueryColumn("resident_size")]
    public long ResidentSize { get; set; }

    /// <summary>Total virtual memory size</summary>
    [OsqueryColumn("total_size")]
    public long TotalSize { get; set; }

    /// <summary>Process start in seconds since boot (non-sleeping)</summary>
    [OsqueryColumn("start_time")]
    public long StartTime { get; set; }

    /// <summary>Process parent's PID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Process group</summary>
    [OsqueryColumn("pgroup")]
    public long Pgroup { get; set; }

    /// <summary>Number of threads used by process</summary>
    [OsqueryColumn("threads")]
    public int Threads { get; set; }

    /// <summary>Process nice level (-20 to 20, default 0)</summary>
    [OsqueryColumn("nice")]
    public int Nice { get; set; }

    /// <summary>User name</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>Cumulative CPU time. [DD-]HH:MM:SS format</summary>
    [OsqueryColumn("time")]
    public string Time { get; set; } = "";

    /// <summary>CPU utilization as percentage</summary>
    [OsqueryColumn("cpu")]
    public double Cpu { get; set; }

    /// <summary>Memory utilization as percentage</summary>
    [OsqueryColumn("mem")]
    public double Mem { get; set; }

}
