// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker images information.
/// </summary>
[OsqueryTable("docker_images")]
public class DockerImage
{
    /// <summary>Image ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Time of creation as UNIX time</summary>
    [OsqueryColumn("created")]
    public long Created { get; set; }

    /// <summary>Size of image in bytes</summary>
    [OsqueryColumn("size_bytes")]
    public long SizeBytes { get; set; }

    /// <summary>Comma-separated list of repository tags</summary>
    [OsqueryColumn("tags")]
    public string Tags { get; set; } = "";

}
