// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker container statistics. Queries on this table take at least one second.
/// </summary>
[OsqueryTable("docker_container_stats")]
public class DockerContainerStat
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Container name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Number of processes</summary>
    [OsqueryColumn("pids")]
    public int Pids { get; set; }

    /// <summary>UNIX time when stats were read</summary>
    [OsqueryColumn("read")]
    public long Read { get; set; }

    /// <summary>UNIX time when stats were last read</summary>
    [OsqueryColumn("preread")]
    public long Preread { get; set; }

    /// <summary>Difference between read and preread in nano-seconds</summary>
    [OsqueryColumn("interval")]
    public long Interval { get; set; }

    /// <summary>Total disk read bytes</summary>
    [OsqueryColumn("disk_read")]
    public long DiskRead { get; set; }

    /// <summary>Total disk write bytes</summary>
    [OsqueryColumn("disk_write")]
    public long DiskWrite { get; set; }

    /// <summary>Number of processors</summary>
    [OsqueryColumn("num_procs")]
    public int NumProcs { get; set; }

    /// <summary>Total CPU usage</summary>
    [OsqueryColumn("cpu_total_usage")]
    public long CpuTotalUsage { get; set; }

    /// <summary>CPU kernel mode usage</summary>
    [OsqueryColumn("cpu_kernelmode_usage")]
    public long CpuKernelmodeUsage { get; set; }

    /// <summary>CPU user mode usage</summary>
    [OsqueryColumn("cpu_usermode_usage")]
    public long CpuUsermodeUsage { get; set; }

    /// <summary>CPU system usage</summary>
    [OsqueryColumn("system_cpu_usage")]
    public long SystemCpuUsage { get; set; }

    /// <summary>Online CPUs</summary>
    [OsqueryColumn("online_cpus")]
    public int OnlineCpus { get; set; }

    /// <summary>Last read total CPU usage</summary>
    [OsqueryColumn("pre_cpu_total_usage")]
    public long PreCpuTotalUsage { get; set; }

    /// <summary>Last read CPU kernel mode usage</summary>
    [OsqueryColumn("pre_cpu_kernelmode_usage")]
    public long PreCpuKernelmodeUsage { get; set; }

    /// <summary>Last read CPU user mode usage</summary>
    [OsqueryColumn("pre_cpu_usermode_usage")]
    public long PreCpuUsermodeUsage { get; set; }

    /// <summary>Last read CPU system usage</summary>
    [OsqueryColumn("pre_system_cpu_usage")]
    public long PreSystemCpuUsage { get; set; }

    /// <summary>Last read online CPUs</summary>
    [OsqueryColumn("pre_online_cpus")]
    public int PreOnlineCpus { get; set; }

    /// <summary>Memory usage</summary>
    [OsqueryColumn("memory_usage")]
    public long MemoryUsage { get; set; }

    /// <summary>Memory cached</summary>
    [OsqueryColumn("memory_cached")]
    public long MemoryCached { get; set; }

    /// <summary>Memory inactive file</summary>
    [OsqueryColumn("memory_inactive_file")]
    public long MemoryInactiveFile { get; set; }

    /// <summary>Memory total inactive file</summary>
    [OsqueryColumn("memory_total_inactive_file")]
    public long MemoryTotalInactiveFile { get; set; }

    /// <summary>Memory maximum usage</summary>
    [OsqueryColumn("memory_max_usage")]
    public long MemoryMaxUsage { get; set; }

    /// <summary>Memory limit</summary>
    [OsqueryColumn("memory_limit")]
    public long MemoryLimit { get; set; }

    /// <summary>Total network bytes read</summary>
    [OsqueryColumn("network_rx_bytes")]
    public long NetworkRxBytes { get; set; }

    /// <summary>Total network bytes transmitted</summary>
    [OsqueryColumn("network_tx_bytes")]
    public long NetworkTxBytes { get; set; }
}
