// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker image history information.
/// </summary>
[OsqueryTable("docker_image_history")]
public class DockerImageHistory
{
    /// <summary>Image ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Time of creation as UNIX time</summary>
    [OsqueryColumn("created")]
    public long Created { get; set; }

    /// <summary>Size of instruction in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Created by instruction</summary>
    [OsqueryColumn("created_by")]
    public string CreatedBy { get; set; } = "";

    /// <summary>Comma-separated list of tags</summary>
    [OsqueryColumn("tags")]
    public string Tags { get; set; } = "";

    /// <summary>Instruction comment</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";
}
