// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker container ports.
/// </summary>
[OsqueryTable("docker_container_ports")]
public class DockerContainerPort
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Protocol (tcp, udp)</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Port inside the container</summary>
    [OsqueryColumn("port")]
    public int Port { get; set; }

    /// <summary>Host IP address on which public port is listening</summary>
    [OsqueryColumn("host_ip")]
    public string HostIp { get; set; } = "";

    /// <summary>Host port</summary>
    [OsqueryColumn("host_port")]
    public int HostPort { get; set; }
}
