// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker image layers information.
/// </summary>
[OsqueryTable("docker_image_layers")]
public class DockerImageLayer
{
    /// <summary>Image ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Layer ID</summary>
    [OsqueryColumn("layer_id")]
    public string LayerId { get; set; } = "";

    /// <summary>Layer Order (1 = base layer)</summary>
    [OsqueryColumn("layer_order")]
    public int LayerOrder { get; set; }

}
