// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Docker container networks.
/// </summary>
[OsqueryTable("docker_container_networks")]
public class DockerContainerNetwork
{
    /// <summary>Container ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Network name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Network ID</summary>
    [OsqueryColumn("network_id")]
    public string NetworkId { get; set; } = "";

    /// <summary>Endpoint ID</summary>
    [OsqueryColumn("endpoint_id")]
    public string EndpointId { get; set; } = "";

    /// <summary>Gateway</summary>
    [OsqueryColumn("gateway")]
    public string Gateway { get; set; } = "";

    /// <summary>IP address</summary>
    [OsqueryColumn("ip_address")]
    public string IpAddress { get; set; } = "";

    /// <summary>IP subnet prefix length</summary>
    [OsqueryColumn("ip_prefix_len")]
    public int IpPrefixLen { get; set; }

    /// <summary>IPv6 gateway</summary>
    [OsqueryColumn("ipv6_gateway")]
    public string Ipv6Gateway { get; set; } = "";

    /// <summary>IPv6 address</summary>
    [OsqueryColumn("ipv6_address")]
    public string Ipv6Address { get; set; } = "";

    /// <summary>IPv6 subnet prefix length</summary>
    [OsqueryColumn("ipv6_prefix_len")]
    public int Ipv6PrefixLen { get; set; }

    /// <summary>MAC address</summary>
    [OsqueryColumn("mac_address")]
    public string MacAddress { get; set; } = "";
}
