// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Details for in-use Windows device drivers. This does not display installed but unused drivers.
/// </summary>
[OsqueryTable("drivers")]
public class Driver
{
    /// <summary>Device ID</summary>
    [OsqueryColumn("device_id")]
    public string DeviceId { get; set; } = "";

    /// <summary>Device name</summary>
    [OsqueryColumn("device_name")]
    public string DeviceName { get; set; } = "";

    /// <summary>Path to driver image file</summary>
    [OsqueryColumn("image")]
    public string Image { get; set; } = "";

    /// <summary>Driver description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Driver service name, if one exists</summary>
    [OsqueryColumn("service")]
    public string Service { get; set; } = "";

    /// <summary>Driver service registry key</summary>
    [OsqueryColumn("service_key")]
    public string ServiceKey { get; set; } = "";

    /// <summary>Driver version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Associated inf file</summary>
    [OsqueryColumn("inf")]
    public string Inf { get; set; } = "";

    /// <summary>Device/driver class name</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>Driver provider</summary>
    [OsqueryColumn("provider")]
    public string Provider { get; set; } = "";

    /// <summary>Device manufacturer</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>Driver key</summary>
    [OsqueryColumn("driver_key")]
    public string DriverKey { get; set; } = "";

    /// <summary>Driver date</summary>
    [OsqueryColumn("date")]
    public long Date { get; set; }

    /// <summary>Whether the driver is signed or not</summary>
    [OsqueryColumn("signed")]
    public int Signed { get; set; }
}
