// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// EC2 instance metadata.
/// </summary>
[OsqueryTable("ec2_instance_metadata")]
public class Ec2InstanceMetadata
{
    /// <summary>EC2 instance ID</summary>
    [OsqueryColumn("instance_id")]
    public string InstanceId { get; set; } = "";

    /// <summary>EC2 instance type</summary>
    [OsqueryColumn("instance_type")]
    public string InstanceType { get; set; } = "";

    /// <summary>Hardware architecture of this EC2 instance</summary>
    [OsqueryColumn("architecture")]
    public string Architecture { get; set; } = "";

    /// <summary>AWS region in which this instance launched</summary>
    [OsqueryColumn("region")]
    public string Region { get; set; } = "";

    /// <summary>Availability zone in which this instance launched</summary>
    [OsqueryColumn("availability_zone")]
    public string AvailabilityZone { get; set; } = "";

    /// <summary>Private IPv4 DNS hostname of the first interface of this instance</summary>
    [OsqueryColumn("local_hostname")]
    public string LocalHostname { get; set; } = "";

    /// <summary>Private IPv4 address of the first interface of this instance</summary>
    [OsqueryColumn("local_ipv4")]
    public string LocalIpv4 { get; set; } = "";

    /// <summary>MAC address for the first network interface of this EC2 instance</summary>
    [OsqueryColumn("mac")]
    public string Mac { get; set; } = "";

    /// <summary>Comma separated list of security group names</summary>
    [OsqueryColumn("security_groups")]
    public string SecurityGroups { get; set; } = "";

    /// <summary>If there is an IAM role associated with the instance, contains instance profile ARN</summary>
    [OsqueryColumn("iam_arn")]
    public string IamArn { get; set; } = "";

    /// <summary>AMI ID used to launch this EC2 instance</summary>
    [OsqueryColumn("ami_id")]
    public string AmiId { get; set; } = "";

    /// <summary>ID of the reservation</summary>
    [OsqueryColumn("reservation_id")]
    public string ReservationId { get; set; } = "";

    /// <summary>AWS account ID which owns this EC2 instance</summary>
    [OsqueryColumn("account_id")]
    public string AccountId { get; set; } = "";

    /// <summary>SSH public key. Only available if supplied at instance launch time</summary>
    [OsqueryColumn("ssh_public_key")]
    public string SshPublicKey { get; set; } = "";

}
