// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// EC2 instance tag key value pairs.
/// </summary>
[OsqueryTable("ec2_instance_tags")]
public class Ec2InstanceTag
{
    /// <summary>EC2 instance ID</summary>
    [OsqueryColumn("instance_id")]
    public string InstanceId { get; set; } = "";

    /// <summary>Tag key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Tag value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

}
