// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// File integrity monitoring events from EndpointSecurity including process context.
/// </summary>
[OsqueryTable("es_process_file_events")]
public class EsProcessFileEvent
{
    /// <summary>Version of EndpointSecurity event</summary>
    [OsqueryColumn("version")]
    public int Version { get; set; }

    /// <summary>Per event sequence number</summary>
    [OsqueryColumn("seq_num")]
    public long SeqNum { get; set; }

    /// <summary>Global sequence number</summary>
    [OsqueryColumn("global_seq_num")]
    public long GlobalSeqNum { get; set; }

    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Parent process ID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Path of executed file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The source or target filename for the event</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>Destination filename for the event</summary>
    [OsqueryColumn("dest_filename")]
    public string DestFilename { get; set; } = "";

    /// <summary>Type of EndpointSecurity event</summary>
    [OsqueryColumn("event_type")]
    public string EventType { get; set; } = "";

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";
}
