// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Process execution events from EndpointSecurity.
/// </summary>
[OsqueryTable("es_process_events")]
public class EsProcessEvent
{
    /// <summary>Version of EndpointSecurity event</summary>
    [OsqueryColumn("version")]
    public int Version { get; set; }

    /// <summary>Per event sequence number</summary>
    [OsqueryColumn("seq_num")]
    public long SeqNum { get; set; }

    /// <summary>Global sequence number</summary>
    [OsqueryColumn("global_seq_num")]
    public long GlobalSeqNum { get; set; }

    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Process ID version</summary>
    [OsqueryColumn("pidversion")]
    public long Pidversion { get; set; }

    /// <summary>Path of executed file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Parent process ID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Original parent process ID in case of reparenting</summary>
    [OsqueryColumn("original_parent")]
    public long OriginalParent { get; set; }

    /// <summary>The identifier of the session that contains the process group.</summary>
    [OsqueryColumn("session_id")]
    public long SessionId { get; set; }

    /// <summary>The pid of the process responsible for this process.</summary>
    [OsqueryColumn("responsible_pid")]
    public long ResponsiblePid { get; set; }

    /// <summary>The pidversion of the process responsible for this process.</summary>
    [OsqueryColumn("responsible_pidversion")]
    public long ResponsiblePidversion { get; set; }

    /// <summary>The pidversion of the parent process.</summary>
    [OsqueryColumn("parent_pidversion")]
    public long ParentPidversion { get; set; }

    /// <summary>Command line arguments (argv)</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>Number of command line arguments</summary>
    [OsqueryColumn("cmdline_count")]
    public long CmdlineCount { get; set; }

    /// <summary>Environment variables delimited by spaces</summary>
    [OsqueryColumn("env")]
    public string Env { get; set; } = "";

    /// <summary>Number of environment variables</summary>
    [OsqueryColumn("env_count")]
    public long EnvCount { get; set; }

    /// <summary>The process current working directory</summary>
    [OsqueryColumn("cwd")]
    public string Cwd { get; set; } = "";

    /// <summary>User ID of the process</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Effective User ID of the process</summary>
    [OsqueryColumn("euid")]
    public long Euid { get; set; }

    /// <summary>Group ID of the process</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Effective Group ID of the process</summary>
    [OsqueryColumn("egid")]
    public long Egid { get; set; }

    /// <summary>Username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Signature identifier of the process</summary>
    [OsqueryColumn("signing_id")]
    public string SigningId { get; set; } = "";

    /// <summary>Team identifier of the process</summary>
    [OsqueryColumn("team_id")]
    public string TeamId { get; set; } = "";

    /// <summary>Codesigning hash of the process</summary>
    [OsqueryColumn("cdhash")]
    public string Cdhash { get; set; } = "";

    /// <summary>Indicates if the binary is Apple signed binary (1) or not (0)</summary>
    [OsqueryColumn("platform_binary")]
    public int PlatformBinary { get; set; }

    /// <summary>Exit code of a process in case of an exit event</summary>
    [OsqueryColumn("exit_code")]
    public int ExitCode { get; set; }

    /// <summary>Process ID of a child process in case of a fork event</summary>
    [OsqueryColumn("child_pid")]
    public long ChildPid { get; set; }

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Type of EndpointSecurity event</summary>
    [OsqueryColumn("event_type")]
    public string EventType { get; set; } = "";

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

    /// <summary>Codesigning flags matching one of these options, in a comma separated list: NOT_VALID, ADHOC, NOT_RUNTIME, INSTALLER. See kern/cs_blobs.h in XNU for descriptions.</summary>
    [OsqueryColumn("codesigning_flags")]
    public string CodesigningFlags { get; set; } = "";
}
