// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Line-parsed /etc/hosts.
/// </summary>
[OsqueryTable("etc_hosts")]
public class EtcHost
{
    /// <summary>IP address mapping</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";

    /// <summary>Raw hosts mapping</summary>
    [OsqueryColumn("hostnames")]
    public string Hostnames { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
