// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Line-parsed /etc/protocols.
/// </summary>
[OsqueryTable("etc_protocols")]
public class EtcProtocol
{
    /// <summary>Protocol name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Protocol number</summary>
    [OsqueryColumn("number")]
    public int Number { get; set; }

    /// <summary>Protocol alias</summary>
    [OsqueryColumn("alias")]
    public string Alias { get; set; } = "";

    /// <summary>Comment with protocol description</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";

}
