// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Line-parsed /etc/services.
/// </summary>
[OsqueryTable("etc_services")]
public class EtcService
{
    /// <summary>Service name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Service port number</summary>
    [OsqueryColumn("port")]
    public int Port { get; set; }

    /// <summary>Transport protocol (TCP/UDP)</summary>
    [OsqueryColumn("protocol")]
    public string Protocol { get; set; } = "";

    /// <summary>Optional space separated list of other names for a service</summary>
    [OsqueryColumn("aliases")]
    public string Aliases { get; set; } = "";

    /// <summary>Optional comment for a service.</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";

}
