// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Returns information about installed event taps.
/// </summary>
[OsqueryTable("event_taps")]
public class EventTap
{
    /// <summary>Is the Event Tap enabled</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>Unique ID for the Tap</summary>
    [OsqueryColumn("event_tap_id")]
    public int EventTapId { get; set; }

    /// <summary>The mask that identifies the set of events to be observed.</summary>
    [OsqueryColumn("event_tapped")]
    public string EventTapped { get; set; } = "";

    /// <summary>The process ID of the target application</summary>
    [OsqueryColumn("process_being_tapped")]
    public int ProcessBeingTapped { get; set; }

    /// <summary>The process ID of the application that created the event tap.</summary>
    [OsqueryColumn("tapping_process")]
    public int TappingProcess { get; set; }

}
