// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// This is an example table spec.
/// </summary>
[OsqueryTable("example")]
public class Example
{
    /// <summary>Description for name column</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>This is a signed SQLite int column</summary>
    [OsqueryColumn("points")]
    public int Points { get; set; }

    /// <summary>This is a signed SQLite bigint column</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Action performed in generation</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>An index of some sort</summary>
    [OsqueryColumn("id")]
    public int Id { get; set; }

    /// <summary>Path of example</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
