// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Returns the extended attributes for files (similar to Windows ADS).
/// </summary>
[OsqueryTable("extended_attributes")]
public class ExtendedAttribute
{
    /// <summary>Absolute file path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Directory of file(s)</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>Name of the value generated from the extended attribute</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>The parsed information from the attribute</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>1 if the value is base64 encoded else 0</summary>
    [OsqueryColumn("base64")]
    public int Base64 { get; set; }

}
