// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Fan speeds.
/// </summary>
[OsqueryTable("fan_speed_sensors")]
public class FanSpeedSensor
{
    /// <summary>Fan number</summary>
    [OsqueryColumn("fan")]
    public string Fan { get; set; } = "";

    /// <summary>Fan name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Actual speed</summary>
    [OsqueryColumn("actual")]
    public int Actual { get; set; }

    /// <summary>Minimum speed</summary>
    [OsqueryColumn("min")]
    public int Min { get; set; }

    /// <summary>Maximum speed</summary>
    [OsqueryColumn("max")]
    public int Max { get; set; }

    /// <summary>Target speed</summary>
    [OsqueryColumn("target")]
    public int Target { get; set; }

}
