// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Interactive filesystem attributes and metadata.
/// </summary>
[OsqueryTable("file")]
public class File
{
    /// <summary>Absolute file path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Directory of file(s)</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>Name portion of file path</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>Filesystem inode number</summary>
    [OsqueryColumn("inode")]
    public long Inode { get; set; }

    /// <summary>Owning user ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Owning group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Permission bits</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Device ID (optional)</summary>
    [OsqueryColumn("device")]
    public long Device { get; set; }

    /// <summary>Size of file in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Block size of filesystem</summary>
    [OsqueryColumn("block_size")]
    public int BlockSize { get; set; }

    /// <summary>Last access time</summary>
    [OsqueryColumn("atime")]
    public long Atime { get; set; }

    /// <summary>Last modification time</summary>
    [OsqueryColumn("mtime")]
    public long Mtime { get; set; }

    /// <summary>Last status change time</summary>
    [OsqueryColumn("ctime")]
    public long Ctime { get; set; }

    /// <summary>(B)irth or (cr)eate time</summary>
    [OsqueryColumn("btime")]
    public long Btime { get; set; }

    /// <summary>Number of hard links</summary>
    [OsqueryColumn("hard_links")]
    public int HardLinks { get; set; }

    /// <summary>1 if the path is a symlink, otherwise 0</summary>
    [OsqueryColumn("symlink")]
    public int Symlink { get; set; }

    /// <summary>File status</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Full path of the symlink target if any</summary>
    [OsqueryColumn("symlink_target_path")]
    public string SymlinkTargetPath { get; set; } = "";

    /// <summary>File attrib string. See: https://ss64.com/nt/attrib.html</summary>
    [OsqueryColumn("attributes")]
    public string Attributes { get; set; } = "";

    /// <summary>Volume serial number</summary>
    [OsqueryColumn("volume_serial")]
    public string VolumeSerial { get; set; } = "";

    /// <summary>file ID</summary>
    [OsqueryColumn("file_id")]
    public string FileId { get; set; } = "";

    /// <summary>File version</summary>
    [OsqueryColumn("file_version")]
    public string FileVersion { get; set; } = "";

    /// <summary>File product version</summary>
    [OsqueryColumn("product_version")]
    public string ProductVersion { get; set; } = "";

    /// <summary>(Executable files only) Original filename</summary>
    [OsqueryColumn("original_filename")]
    public string OriginalFilename { get; set; } = "";

    /// <summary>Full path to the file the shortcut points to</summary>
    [OsqueryColumn("shortcut_target_path")]
    public string ShortcutTargetPath { get; set; } = "";

    /// <summary>Display name for the target type</summary>
    [OsqueryColumn("shortcut_target_type")]
    public string ShortcutTargetType { get; set; } = "";

    /// <summary>Folder name where the shortcut target resides</summary>
    [OsqueryColumn("shortcut_target_location")]
    public string ShortcutTargetLocation { get; set; } = "";

    /// <summary>Full path to the working directory to use when executing the shortcut target</summary>
    [OsqueryColumn("shortcut_start_in")]
    public string ShortcutStartIn { get; set; } = "";

    /// <summary>Window mode the target of the shortcut should be run in</summary>
    [OsqueryColumn("shortcut_run")]
    public string ShortcutRun { get; set; } = "";

    /// <summary>Comment on the shortcut</summary>
    [OsqueryColumn("shortcut_comment")]
    public string ShortcutComment { get; set; } = "";

    /// <summary>The BSD file flags (chflags). Possible values: NODUMP, UF_IMMUTABLE, UF_APPEND, OPAQUE, HIDDEN, ARCHIVED, SF_IMMUTABLE, SF_APPEND</summary>
    [OsqueryColumn("bsd_flags")]
    public string BsdFlags { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";

}
