// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track time/action changes to files specified in configuration data.
/// </summary>
[OsqueryTable("file_events")]
public class FileEvent
{
    /// <summary>The path associated with the event</summary>
    [OsqueryColumn("target_path")]
    public string TargetPath { get; set; } = "";

    /// <summary>The category of the file defined in the config</summary>
    [OsqueryColumn("category")]
    public string Category { get; set; } = "";

    /// <summary>Change action (UPDATE, REMOVE, etc)</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>ID used during bulk update</summary>
    [OsqueryColumn("transaction_id")]
    public long TransactionId { get; set; }

    /// <summary>Filesystem inode number</summary>
    [OsqueryColumn("inode")]
    public long Inode { get; set; }

    /// <summary>Owning user ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Owning group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Permission bits</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Size of file in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Last access time</summary>
    [OsqueryColumn("atime")]
    public long Atime { get; set; }

    /// <summary>Last modification time</summary>
    [OsqueryColumn("mtime")]
    public long Mtime { get; set; }

    /// <summary>Last status change time</summary>
    [OsqueryColumn("ctime")]
    public long Ctime { get; set; }

    /// <summary>The MD5 of the file after change</summary>
    [OsqueryColumn("md5")]
    public string Md5 { get; set; } = "";

    /// <summary>The SHA1 of the file after change</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>The SHA256 of the file after change</summary>
    [OsqueryColumn("sha256")]
    public string Sha256 { get; set; } = "";

    /// <summary>1 if the file was hashed, 0 if not, -1 if hashing failed</summary>
    [OsqueryColumn("hashed")]
    public int Hashed { get; set; }

    /// <summary>Time of file event</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";
}
