// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Firefox browser extensions, webapps, and addons.
/// </summary>
[OsqueryTable("firefox_addons")]
public class FirefoxAddon
{
    /// <summary>The local user that owns the addon</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Addon display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Addon identifier</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Addon-supported creator string</summary>
    [OsqueryColumn("creator")]
    public string Creator { get; set; } = "";

    /// <summary>Extension, addon, webapp</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Addon-supplied version string</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Addon-supplied description string</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>URL that installed the addon</summary>
    [OsqueryColumn("source_url")]
    public string SourceUrl { get; set; } = "";

    /// <summary>1 If the addon is shown in browser else 0</summary>
    [OsqueryColumn("visible")]
    public int Visible { get; set; }

    /// <summary>1 If the addon is active else 0</summary>
    [OsqueryColumn("active")]
    public int Active { get; set; }

    /// <summary>1 If the addon is application-disabled else 0</summary>
    [OsqueryColumn("disabled")]
    public int Disabled { get; set; }

    /// <summary>1 If the addon applies background updates else 0</summary>
    [OsqueryColumn("autoupdate")]
    public int Autoupdate { get; set; }

    /// <summary>Global, profile location</summary>
    [OsqueryColumn("location")]
    public string Location { get; set; } = "";

    /// <summary>Path to plugin bundle</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
