// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS Gatekeeper Details.
/// </summary>
[OsqueryTable("gatekeeper")]
public class Gatekeeper
{
    /// <summary>1 If a Gatekeeper is enabled else 0</summary>
    [OsqueryColumn("assessments_enabled")]
    public int AssessmentsEnabled { get; set; }

    /// <summary>1 If a Gatekeeper allows execution from identified developers else 0</summary>
    [OsqueryColumn("dev_id_enabled")]
    public int DevIdEnabled { get; set; }

    /// <summary>Version of Gatekeeper's gke.bundle</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Version of Gatekeeper's gkopaque.bundle</summary>
    [OsqueryColumn("opaque_version")]
    public string OpaqueVersion { get; set; } = "";
}
