// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Gatekeeper apps a user has allowed to run.
/// </summary>
[OsqueryTable("gatekeeper_approved_apps")]
public class GatekeeperApprovedApp
{
    /// <summary>Path of executable allowed to run</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Code signing requirement language</summary>
    [OsqueryColumn("requirement")]
    public string Requirement { get; set; } = "";

    /// <summary>Last change time</summary>
    [OsqueryColumn("ctime")]
    public double Ctime { get; set; }

    /// <summary>Last modification time</summary>
    [OsqueryColumn("mtime")]
    public double Mtime { get; set; }
}
