// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Local system groups.
/// </summary>
[OsqueryTable("groups")]
public class Group
{
    /// <summary>Unsigned int64 group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>A signed int64 version of gid</summary>
    [OsqueryColumn("gid_signed")]
    public long GidSigned { get; set; }

    /// <summary>Canonical local group name</summary>
    [OsqueryColumn("groupname")]
    public string Groupname { get; set; } = "";

    /// <summary>Unique group ID</summary>
    [OsqueryColumn("group_sid")]
    public string GroupSid { get; set; } = "";

    /// <summary>Remarks or comments associated with the group</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";

    /// <summary>IsHidden attribute set in OpenDirectory</summary>
    [OsqueryColumn("is_hidden")]
    public int IsHidden { get; set; }

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
