// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Hardware (PCI/USB/HID) events from UDEV or IOKit.
/// </summary>
[OsqueryTable("hardware_events")]
public class HardwareEvent
{
    /// <summary>Remove, insert, change properties, etc</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>Local device path assigned (optional)</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Type of hardware and hardware event</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Driver claiming the device</summary>
    [OsqueryColumn("driver")]
    public string Driver { get; set; } = "";

    /// <summary>Hardware device vendor</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Hex encoded Hardware vendor identifier</summary>
    [OsqueryColumn("vendor_id")]
    public string VendorId { get; set; } = "";

    /// <summary>Hardware device model</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>Hex encoded Hardware model identifier</summary>
    [OsqueryColumn("model_id")]
    public string ModelId { get; set; } = "";

    /// <summary>Device serial (optional)</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>Device revision (optional)</summary>
    [OsqueryColumn("revision")]
    public string Revision { get; set; } = "";

    /// <summary>Time of hardware event</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";
}
