// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Filesystem hash data.
/// </summary>
[OsqueryTable("hash")]
public class Hash
{
    /// <summary>Must provide a path or directory</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Must provide a path or directory</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>MD5 hash of provided filesystem data</summary>
    [OsqueryColumn("md5")]
    public string Md5 { get; set; } = "";

    /// <summary>SHA1 hash of provided filesystem data</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>SHA256 hash of provided filesystem data</summary>
    [OsqueryColumn("sha256")]
    public string Sha256 { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";

}
