// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// The installed homebrew package database.
/// </summary>
[OsqueryTable("homebrew_packages")]
public class HomebrewPackage
{
    /// <summary>Package name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package install path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Current 'linked' version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package type ('formula' or 'cask')</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>1 if the cask auto-updates otherwise 0</summary>
    [OsqueryColumn("auto_updates")]
    public int AutoUpdates { get; set; }

    /// <summary>Name of the installed App (for Casks)</summary>
    [OsqueryColumn("app_name")]
    public string AppName { get; set; } = "";

    /// <summary>Homebrew install prefix</summary>
    [OsqueryColumn("prefix")]
    public string Prefix { get; set; } = "";
}
