// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Internet Explorer browser extensions.
/// </summary>
[OsqueryTable("ie_extensions")]
public class IeExtension
{
    /// <summary>Extension display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Extension identifier</summary>
    [OsqueryColumn("registry_path")]
    public string RegistryPath { get; set; } = "";

    /// <summary>Version of the executable</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Path to executable</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
