// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// IPv6 configuration and stats of network interfaces.
/// </summary>
[OsqueryTable("interface_ipv6")]
public class InterfaceIpv6
{
    /// <summary>Interface name</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>Current Hop Limit</summary>
    [OsqueryColumn("hop_limit")]
    public int HopLimit { get; set; }

    /// <summary>Enable IP forwarding</summary>
    [OsqueryColumn("forwarding_enabled")]
    public int ForwardingEnabled { get; set; }

    /// <summary>Accept ICMP redirect messages</summary>
    [OsqueryColumn("redirect_accept")]
    public int RedirectAccept { get; set; }

    /// <summary>Accept ICMP Router Advertisement</summary>
    [OsqueryColumn("rtadv_accept")]
    public int RtadvAccept { get; set; }

}
