// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Intel ME/CSE Info.
/// </summary>
[OsqueryTable("intel_me_info")]
public class IntelMeInfo
{
    /// <summary>Intel ME version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

}
