// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Detailed information and stats of network interfaces.
/// </summary>
[OsqueryTable("interface_details")]
public class InterfaceDetail
{
    /// <summary>Interface name</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>MAC of interface (optional)</summary>
    [OsqueryColumn("mac")]
    public string Mac { get; set; } = "";

    /// <summary>Interface type (includes virtual)</summary>
    [OsqueryColumn("type")]
    public int Type { get; set; }

    /// <summary>Network MTU</summary>
    [OsqueryColumn("mtu")]
    public int Mtu { get; set; }

    /// <summary>Metric based on the speed of the interface</summary>
    [OsqueryColumn("metric")]
    public int Metric { get; set; }

    /// <summary>Flags (netdevice) for the device</summary>
    [OsqueryColumn("flags")]
    public int Flags { get; set; }

    /// <summary>Input packets</summary>
    [OsqueryColumn("ipackets")]
    public long Ipackets { get; set; }

    /// <summary>Output packets</summary>
    [OsqueryColumn("opackets")]
    public long Opackets { get; set; }

    /// <summary>Input bytes</summary>
    [OsqueryColumn("ibytes")]
    public long Ibytes { get; set; }

    /// <summary>Output bytes</summary>
    [OsqueryColumn("obytes")]
    public long Obytes { get; set; }

    /// <summary>Input errors</summary>
    [OsqueryColumn("ierrors")]
    public long Ierrors { get; set; }

    /// <summary>Output errors</summary>
    [OsqueryColumn("oerrors")]
    public long Oerrors { get; set; }

    /// <summary>Input drops</summary>
    [OsqueryColumn("idrops")]
    public long Idrops { get; set; }

    /// <summary>Output drops</summary>
    [OsqueryColumn("odrops")]
    public long Odrops { get; set; }

    /// <summary>Packet Collisions detected</summary>
    [OsqueryColumn("collisions")]
    public long Collisions { get; set; }

    /// <summary>Time of last device modification (optional)</summary>
    [OsqueryColumn("last_change")]
    public long LastChange { get; set; }

    /// <summary>Interface speed in Mb/s</summary>
    [OsqueryColumn("link_speed")]
    public long LinkSpeed { get; set; }

    /// <summary>PCI slot number</summary>
    [OsqueryColumn("pci_slot")]
    public string PciSlot { get; set; } = "";

    /// <summary>The friendly display name of the interface.</summary>
    [OsqueryColumn("friendly_name")]
    public string FriendlyName { get; set; } = "";

    /// <summary>Short description of the object a one-line string.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Name of the network adapter's manufacturer.</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>Name of the network connection as it appears in the Network Connections Control Panel program.</summary>
    [OsqueryColumn("connection_id")]
    public string ConnectionId { get; set; } = "";

    /// <summary>State of the network adapter connection to the network.</summary>
    [OsqueryColumn("connection_status")]
    public string ConnectionStatus { get; set; } = "";

    /// <summary>Indicates whether the adapter is enabled or not.</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>Indicates whether the adapter is a physical or a logical adapter.</summary>
    [OsqueryColumn("physical_adapter")]
    public int PhysicalAdapter { get; set; }

    /// <summary>Estimate of the current bandwidth in bits per second.</summary>
    [OsqueryColumn("speed")]
    public int Speed { get; set; }

    /// <summary>The name of the service the network adapter uses.</summary>
    [OsqueryColumn("service")]
    public string Service { get; set; } = "";

    /// <summary>If TRUE, the dynamic host configuration protocol (DHCP) server automatically assigns an IP address to the computer system when establishing a network connection.</summary>
    [OsqueryColumn("dhcp_enabled")]
    public int DhcpEnabled { get; set; }

    /// <summary>Expiration date and time for a leased IP address that was assigned to the computer by the dynamic host configuration protocol (DHCP) server.</summary>
    [OsqueryColumn("dhcp_lease_expires")]
    public string DhcpLeaseExpires { get; set; } = "";

    /// <summary>Date and time the lease was obtained for the IP address assigned to the computer by the dynamic host configuration protocol (DHCP) server.</summary>
    [OsqueryColumn("dhcp_lease_obtained")]
    public string DhcpLeaseObtained { get; set; } = "";

    /// <summary>IP address of the dynamic host configuration protocol (DHCP) server.</summary>
    [OsqueryColumn("dhcp_server")]
    public string DhcpServer { get; set; } = "";

    /// <summary>Organization name followed by a period and an extension that indicates the type of organization, such as 'microsoft.com'.</summary>
    [OsqueryColumn("dns_domain")]
    public string DnsDomain { get; set; } = "";

    /// <summary>Array of DNS domain suffixes to be appended to the end of host names during name resolution.</summary>
    [OsqueryColumn("dns_domain_suffix_search_order")]
    public string DnsDomainSuffixSearchOrder { get; set; } = "";

    /// <summary>Host name used to identify the local computer for authentication by some utilities.</summary>
    [OsqueryColumn("dns_host_name")]
    public string DnsHostName { get; set; } = "";

    /// <summary>Array of server IP addresses to be used in querying for DNS servers.</summary>
    [OsqueryColumn("dns_server_search_order")]
    public string DnsServerSearchOrder { get; set; } = "";
}
