// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Network interfaces and relevant metadata.
/// </summary>
[OsqueryTable("interface_addresses")]
public class InterfaceAddress
{
    /// <summary>Interface name</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>Specific address for interface</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";

    /// <summary>Interface netmask</summary>
    [OsqueryColumn("mask")]
    public string Mask { get; set; } = "";

    /// <summary>Broadcast address for the interface</summary>
    [OsqueryColumn("broadcast")]
    public string Broadcast { get; set; } = "";

    /// <summary>PtP address for the interface</summary>
    [OsqueryColumn("point_to_point")]
    public string PointToPoint { get; set; } = "";

    /// <summary>Type of address. One of dhcp, manual, auto, other, unknown</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>The friendly display name of the interface.</summary>
    [OsqueryColumn("friendly_name")]
    public string FriendlyName { get; set; } = "";

}
