// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// The IOKit registry matching the DeviceTree plane.
/// </summary>
[OsqueryTable("iokit_devicetree")]
public class IokitDevicetree
{
    /// <summary>Device node name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Best matching device class (most-specific category)</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>IOKit internal registry ID</summary>
    [OsqueryColumn("id")]
    public long Id { get; set; }

    /// <summary>Parent device registry ID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Device tree path</summary>
    [OsqueryColumn("device_path")]
    public string DevicePath { get; set; } = "";

    /// <summary>1 if the device conforms to IOService else 0</summary>
    [OsqueryColumn("service")]
    public int Service { get; set; }

    /// <summary>1 if the device is in a busy state else 0</summary>
    [OsqueryColumn("busy_state")]
    public int BusyState { get; set; }

    /// <summary>The device reference count</summary>
    [OsqueryColumn("retain_count")]
    public int RetainCount { get; set; }

    /// <summary>Device nested depth</summary>
    [OsqueryColumn("depth")]
    public int Depth { get; set; }

}
