// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Linux IP packet filtering and NAT tool.
/// </summary>
[OsqueryTable("iptables")]
public class Iptable
{
    /// <summary>Packet matching filter table name.</summary>
    [OsqueryColumn("filter_name")]
    public string FilterName { get; set; } = "";

    /// <summary>Size of module content.</summary>
    [OsqueryColumn("chain")]
    public string Chain { get; set; } = "";

    /// <summary>Policy that applies for this rule.</summary>
    [OsqueryColumn("policy")]
    public string Policy { get; set; } = "";

    /// <summary>Target that applies for this rule.</summary>
    [OsqueryColumn("target")]
    public string Target { get; set; } = "";

    /// <summary>Protocol number identification.</summary>
    [OsqueryColumn("protocol")]
    public int Protocol { get; set; }

    /// <summary>Protocol source port(s).</summary>
    [OsqueryColumn("src_port")]
    public string SrcPort { get; set; } = "";

    /// <summary>Protocol destination port(s).</summary>
    [OsqueryColumn("dst_port")]
    public string DstPort { get; set; } = "";

    /// <summary>Source IP address.</summary>
    [OsqueryColumn("src_ip")]
    public string SrcIp { get; set; } = "";

    /// <summary>Source IP address mask.</summary>
    [OsqueryColumn("src_mask")]
    public string SrcMask { get; set; } = "";

    /// <summary>Input interface for the rule.</summary>
    [OsqueryColumn("iniface")]
    public string Iniface { get; set; } = "";

    /// <summary>Input interface mask for the rule.</summary>
    [OsqueryColumn("iniface_mask")]
    public string InifaceMask { get; set; } = "";

    /// <summary>Destination IP address.</summary>
    [OsqueryColumn("dst_ip")]
    public string DstIp { get; set; } = "";

    /// <summary>Destination IP address mask.</summary>
    [OsqueryColumn("dst_mask")]
    public string DstMask { get; set; } = "";

    /// <summary>Output interface for the rule.</summary>
    [OsqueryColumn("outiface")]
    public string Outiface { get; set; } = "";

    /// <summary>Output interface mask for the rule.</summary>
    [OsqueryColumn("outiface_mask")]
    public string OutifaceMask { get; set; } = "";

    /// <summary>Matching rule that applies.</summary>
    [OsqueryColumn("match")]
    public string Match { get; set; } = "";

    /// <summary>Number of matching packets for this rule.</summary>
    [OsqueryColumn("packets")]
    public int Packets { get; set; }

    /// <summary>Number of matching bytes for this rule.</summary>
    [OsqueryColumn("bytes")]
    public int Bytes { get; set; }
}
