// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// JetBrains IDEs plugins.
/// </summary>
[OsqueryTable("jetbrains_plugins")]
public class JetbrainsPlugin
{
    /// <summary>The product type (Valid values: CLion, DataGrip, GoLand, IntelliJIdea, IntelliJIdeaCommunityEdition, PhpStorm, PyCharm, PyCharmCommunityEdition, ReSharper, Rider, RubyMine, RustRover, WebStorm)</summary>
    [OsqueryColumn("product_type")]
    public string ProductType { get; set; } = "";

    /// <summary>The local user that owns the plugin</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Name of the plugin (Title Case)</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Version of the plugin</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The vendor name or organization id that authored the plugin</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>The path on the filesystem for the plugin. This may be a folder or a jar filename</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
