// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// List of security data, authentication keys and encryption keys.
/// </summary>
[OsqueryTable("kernel_keys")]
public class KernelKey
{
    /// <summary>The serial key of the key.</summary>
    [OsqueryColumn("serial_number")]
    public string SerialNumber { get; set; } = "";

    /// <summary>A set of flags describing the state of the key.</summary>
    [OsqueryColumn("flags")]
    public string Flags { get; set; } = "";

    /// <summary>the number of threads and open file references that refer to this key.</summary>
    [OsqueryColumn("usage")]
    public long Usage { get; set; }

    /// <summary>The amount of time until the key will expire, expressed in human-readable form. The string perm here means that the key is permanent (no timeout).  The string expd means that the key has already expired.</summary>
    [OsqueryColumn("timeout")]
    public string Timeout { get; set; } = "";

    /// <summary>The key permissions, expressed as four hexadecimal bytes containing, from left to right, the possessor, user, group, and other permissions.</summary>
    [OsqueryColumn("permissions")]
    public string Permissions { get; set; } = "";

    /// <summary>The user ID of the key owner.</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>The group ID of the key.</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>The key type.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>The key description.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

}
