// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Linux kernel modules both loaded and within the load search path.
/// </summary>
[OsqueryTable("kernel_modules")]
public class KernelModule
{
    /// <summary>Module name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Size of module content</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Module reverse dependencies</summary>
    [OsqueryColumn("used_by")]
    public string UsedBy { get; set; } = "";

    /// <summary>Kernel module status</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>Kernel module address</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";
}
