// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Basic active kernel information.
/// </summary>
[OsqueryTable("kernel_info")]
public class KernelInfo
{
    /// <summary>Kernel version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Kernel arguments</summary>
    [OsqueryColumn("arguments")]
    public string Arguments { get; set; } = "";

    /// <summary>Kernel path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Kernel device identifier</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";
}
