// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// System kernel panic logs.
/// </summary>
[OsqueryTable("kernel_panics")]
public class KernelPanic
{
    /// <summary>Location of log file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Formatted time of the event</summary>
    [OsqueryColumn("time")]
    public string Time { get; set; } = "";

    /// <summary>A space delimited line of register:value pairs</summary>
    [OsqueryColumn("registers")]
    public string Registers { get; set; } = "";

    /// <summary>Backtrace of the crashed module</summary>
    [OsqueryColumn("frame_backtrace")]
    public string FrameBacktrace { get; set; } = "";

    /// <summary>Modules appearing in the crashed module's backtrace</summary>
    [OsqueryColumn("module_backtrace")]
    public string ModuleBacktrace { get; set; } = "";

    /// <summary>Module dependencies existing in crashed module's backtrace</summary>
    [OsqueryColumn("dependencies")]
    public string Dependencies { get; set; } = "";

    /// <summary>Process name corresponding to crashed thread</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Version of the operating system</summary>
    [OsqueryColumn("os_version")]
    public string OsVersion { get; set; } = "";

    /// <summary>Version of the system kernel</summary>
    [OsqueryColumn("kernel_version")]
    public string KernelVersion { get; set; } = "";

    /// <summary>Physical system model, for example 'MacBookPro12,1 (Mac-E43C1C25D4880AD6)'</summary>
    [OsqueryColumn("system_model")]
    public string SystemModel { get; set; } = "";

    /// <summary>System uptime at kernel panic in nanoseconds</summary>
    [OsqueryColumn("uptime")]
    public long Uptime { get; set; }

    /// <summary>Last loaded module before panic</summary>
    [OsqueryColumn("last_loaded")]
    public string LastLoaded { get; set; } = "";

    /// <summary>Last unloaded module before panic</summary>
    [OsqueryColumn("last_unloaded")]
    public string LastUnloaded { get; set; } = "";

}
