// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Applications that have ACL entries in the keychain. NOTE: osquery limits frequent access to keychain files. This limit is controlled by keychain_access_interval flag.
/// </summary>
[OsqueryTable("keychain_acls")]
public class KeychainAcl
{
    /// <summary>The path of the keychain</summary>
    [OsqueryColumn("keychain_path")]
    public string KeychainPath { get; set; } = "";

    /// <summary>A space delimited set of authorization attributes</summary>
    [OsqueryColumn("authorizations")]
    public string Authorizations { get; set; } = "";

    /// <summary>The path of the authorized application</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The description included with the ACL entry</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>An optional label tag that may be included with the keychain entry</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

}
