// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Generic details about keychain items. NOTE: osquery limits frequent access to keychain files. This limit is controlled by keychain_access_interval flag.
/// </summary>
[OsqueryTable("keychain_items")]
public class KeychainItem
{
    /// <summary>Generic item name</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Optional item description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Optional keychain comment</summary>
    [OsqueryColumn("comment")]
    public string Comment { get; set; } = "";

    /// <summary>Optional item account</summary>
    [OsqueryColumn("account")]
    public string Account { get; set; } = "";

    /// <summary>Date item was created</summary>
    [OsqueryColumn("created")]
    public string Created { get; set; } = "";

    /// <summary>Date of last modification</summary>
    [OsqueryColumn("modified")]
    public string Modified { get; set; } = "";

    /// <summary>Keychain item type (class)</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Hash of associated public key (SHA1 of subjectPublicKey, see RFC 8520 4.2.1.2)</summary>
    [OsqueryColumn("pk_hash")]
    public string PkHash { get; set; } = "";

    /// <summary>Path to keychain containing item</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
