// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A line-delimited known_hosts table.
/// </summary>
[OsqueryTable("known_hosts")]
public class KnownHost
{
    /// <summary>The local user that owns the known_hosts file</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>parsed authorized keys line</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Path to known_hosts file</summary>
    [OsqueryColumn("key_file")]
    public string KeyFile { get; set; } = "";
}
