// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Display kernel virtual address and speculative execution information for the system.
/// </summary>
[OsqueryTable("kva_speculative_info")]
public class KvaSpeculativeInfo
{
    /// <summary>Kernel Virtual Address shadowing is enabled.</summary>
    [OsqueryColumn("kva_shadow_enabled")]
    public int KvaShadowEnabled { get; set; }

    /// <summary>User pages are marked as global.</summary>
    [OsqueryColumn("kva_shadow_user_global")]
    public int KvaShadowUserGlobal { get; set; }

    /// <summary>Kernel VA PCID flushing optimization is enabled.</summary>
    [OsqueryColumn("kva_shadow_pcid")]
    public int KvaShadowPcid { get; set; }

    /// <summary>Kernel VA INVPCID is enabled.</summary>
    [OsqueryColumn("kva_shadow_inv_pcid")]
    public int KvaShadowInvPcid { get; set; }

    /// <summary>Branch Prediction mitigations are enabled.</summary>
    [OsqueryColumn("bp_mitigations")]
    public int BpMitigations { get; set; }

    /// <summary>Branch Predictions are disabled via system policy.</summary>
    [OsqueryColumn("bp_system_pol_disabled")]
    public int BpSystemPolDisabled { get; set; }

    /// <summary>Branch Predictions are disabled due to lack of microcode update.</summary>
    [OsqueryColumn("bp_microcode_disabled")]
    public int BpMicrocodeDisabled { get; set; }

    /// <summary>SPEC_CTRL MSR supported by CPU Microcode.</summary>
    [OsqueryColumn("cpu_spec_ctrl_supported")]
    public int CpuSpecCtrlSupported { get; set; }

    /// <summary>Windows uses IBRS.</summary>
    [OsqueryColumn("ibrs_support_enabled")]
    public int IbrsSupportEnabled { get; set; }

    /// <summary>Windows uses STIBP.</summary>
    [OsqueryColumn("stibp_support_enabled")]
    public int StibpSupportEnabled { get; set; }

    /// <summary>PRED_CMD MSR supported by CPU Microcode.</summary>
    [OsqueryColumn("cpu_pred_cmd_supported")]
    public int CpuPredCmdSupported { get; set; }
}
