// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Override keys, per user, for LaunchDaemons and Agents.
/// </summary>
[OsqueryTable("launchd_overrides")]
public class LaunchdOverride
{
    /// <summary>Daemon or agent service name</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Name of the override key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Overridden value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>User ID applied to the override, 0 applies to all</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Path to daemon or agent plist</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
