// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LaunchAgents and LaunchDaemons from default search paths.
/// </summary>
[OsqueryTable("launchd")]
public class Launchd
{
    /// <summary>Path to daemon or agent plist</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>File name of plist (used by launchd)</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Daemon or agent service name</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Path to target program</summary>
    [OsqueryColumn("program")]
    public string Program { get; set; } = "";

    /// <summary>Should the program run on launch load</summary>
    [OsqueryColumn("run_at_load")]
    public string RunAtLoad { get; set; } = "";

    /// <summary>Should the process be restarted if killed</summary>
    [OsqueryColumn("keep_alive")]
    public string KeepAlive { get; set; } = "";

    /// <summary>Deprecated key, replaced by keep_alive</summary>
    [OsqueryColumn("on_demand")]
    public string OnDemand { get; set; } = "";

    /// <summary>Skip loading this daemon or agent on boot</summary>
    [OsqueryColumn("disabled")]
    public string Disabled { get; set; } = "";

    /// <summary>Run this daemon or agent as this username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Run this daemon or agent as this group</summary>
    [OsqueryColumn("groupname")]
    public string Groupname { get; set; } = "";

    /// <summary>Pipe stdout to a target path</summary>
    [OsqueryColumn("stdout_path")]
    public string StdoutPath { get; set; } = "";

    /// <summary>Pipe stderr to a target path</summary>
    [OsqueryColumn("stderr_path")]
    public string StderrPath { get; set; } = "";

    /// <summary>Frequency to run in seconds</summary>
    [OsqueryColumn("start_interval")]
    public string StartInterval { get; set; } = "";

    /// <summary>Command line arguments passed to program</summary>
    [OsqueryColumn("program_arguments")]
    public string ProgramArguments { get; set; } = "";

    /// <summary>Key that launches daemon or agent if path is modified</summary>
    [OsqueryColumn("watch_paths")]
    public string WatchPaths { get; set; } = "";

    /// <summary>Similar to watch_paths but only with non-empty directories</summary>
    [OsqueryColumn("queue_directories")]
    public string QueueDirectories { get; set; } = "";

    /// <summary>Run this daemon or agent as it was launched from inetd</summary>
    [OsqueryColumn("inetd_compatibility")]
    public string InetdCompatibility { get; set; } = "";

    /// <summary>Run daemon or agent every time a filesystem is mounted</summary>
    [OsqueryColumn("start_on_mount")]
    public string StartOnMount { get; set; } = "";

    /// <summary>Key used to specify a directory to chroot to before launch</summary>
    [OsqueryColumn("root_directory")]
    public string RootDirectory { get; set; } = "";

    /// <summary>Key used to specify a directory to chdir to before launch</summary>
    [OsqueryColumn("working_directory")]
    public string WorkingDirectory { get; set; } = "";

    /// <summary>Key describes the intended purpose of the job</summary>
    [OsqueryColumn("process_type")]
    public string ProcessType { get; set; } = "";

}
