// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Reports the status of the Location Services feature of the OS.
/// </summary>
[OsqueryTable("location_services")]
public class LocationService
{
    /// <summary>1 if Location Services are enabled, else 0</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }
}
