// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Users with an active shell on the system.
/// </summary>
[OsqueryTable("logged_in_users")]
public class LoggedInUser
{
    /// <summary>Login type</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>User login name</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>Device name</summary>
    [OsqueryColumn("tty")]
    public string Tty { get; set; } = "";

    /// <summary>Remote hostname</summary>
    [OsqueryColumn("host")]
    public string Host { get; set; } = "";

    /// <summary>Time entry was made</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>The user's unique security identifier</summary>
    [OsqueryColumn("sid")]
    public string Sid { get; set; } = "";

    /// <summary>HKEY_USERS registry hive</summary>
    [OsqueryColumn("registry_hive")]
    public string RegistryHive { get; set; } = "";

}
