// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Details for logical drives on the system. A logical drive generally represents a single partition.
/// </summary>
[OsqueryTable("logical_drives")]
public class LogicalDrive
{
    /// <summary>The drive id, usually the drive name, e.g., 'C:'.</summary>
    [OsqueryColumn("device_id")]
    public string DeviceId { get; set; } = "";

    /// <summary>Deprecated (always 'Unknown').</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>The canonical description of the drive, e.g. 'Logical Fixed Disk', 'CD-ROM Disk'.</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>The amount of free space, in bytes, of the drive (-1 on failure).</summary>
    [OsqueryColumn("free_space")]
    public long FreeSpace { get; set; }

    /// <summary>The total amount of space, in bytes, of the drive (-1 on failure).</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>The file system of the drive.</summary>
    [OsqueryColumn("file_system")]
    public string FileSystem { get; set; } = "";

    /// <summary>True if Windows booted from this drive.</summary>
    [OsqueryColumn("boot_partition")]
    public int BootPartition { get; set; }
}
