// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Windows Logon Session.
/// </summary>
[OsqueryTable("logon_sessions")]
public class LogonSession
{
    /// <summary>A locally unique identifier (LUID) that identifies a logon session.</summary>
    [OsqueryColumn("logon_id")]
    public int LogonId { get; set; }

    /// <summary>The account name of the security principal that owns the logon session.</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>The name of the domain used to authenticate the owner of the logon session.</summary>
    [OsqueryColumn("logon_domain")]
    public string LogonDomain { get; set; } = "";

    /// <summary>The authentication package used to authenticate the owner of the logon session.</summary>
    [OsqueryColumn("authentication_package")]
    public string AuthenticationPackage { get; set; } = "";

    /// <summary>The logon method.</summary>
    [OsqueryColumn("logon_type")]
    public string LogonType { get; set; } = "";

    /// <summary>The Terminal Services session identifier.</summary>
    [OsqueryColumn("session_id")]
    public int SessionId { get; set; }

    /// <summary>The user's security identifier (SID).</summary>
    [OsqueryColumn("logon_sid")]
    public string LogonSid { get; set; } = "";

    /// <summary>The time the session owner logged on.</summary>
    [OsqueryColumn("logon_time")]
    public long LogonTime { get; set; }

    /// <summary>The name of the server used to authenticate the owner of the logon session.</summary>
    [OsqueryColumn("logon_server")]
    public string LogonServer { get; set; } = "";

    /// <summary>The DNS name for the owner of the logon session.</summary>
    [OsqueryColumn("dns_domain_name")]
    public string DnsDomainName { get; set; } = "";

    /// <summary>The user principal name (UPN) for the owner of the logon session.</summary>
    [OsqueryColumn("upn")]
    public string Upn { get; set; } = "";

    /// <summary>The script used for logging on.</summary>
    [OsqueryColumn("logon_script")]
    public string LogonScript { get; set; } = "";

    /// <summary>The home directory for the logon session.</summary>
    [OsqueryColumn("profile_path")]
    public string ProfilePath { get; set; } = "";

    /// <summary>The home directory for the logon session.</summary>
    [OsqueryColumn("home_directory")]
    public string HomeDirectory { get; set; } = "";

    /// <summary>The drive location of the home directory of the logon session.</summary>
    [OsqueryColumn("home_directory_drive")]
    public string HomeDirectoryDrive { get; set; } = "";
}
