// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD certificates information.
/// </summary>
[OsqueryTable("lxd_certificates")]
public class LxdCertificate
{
    /// <summary>Name of the certificate</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Type of the certificate</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>SHA256 hash of the certificate</summary>
    [OsqueryColumn("fingerprint")]
    public string Fingerprint { get; set; } = "";

    /// <summary>Certificate content</summary>
    [OsqueryColumn("certificate")]
    public string Certificate { get; set; } = "";

}
