// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD cluster information.
/// </summary>
[OsqueryTable("lxd_cluster")]
public class LxdCluster
{
    /// <summary>Name of the LXD server node</summary>
    [OsqueryColumn("server_name")]
    public string ServerName { get; set; } = "";

    /// <summary>Whether clustering enabled (1) or not (0) on this node</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>Type of configuration parameter for this node</summary>
    [OsqueryColumn("member_config_entity")]
    public string MemberConfigEntity { get; set; } = "";

    /// <summary>Name of configuration parameter</summary>
    [OsqueryColumn("member_config_name")]
    public string MemberConfigName { get; set; } = "";

    /// <summary>Config key</summary>
    [OsqueryColumn("member_config_key")]
    public string MemberConfigKey { get; set; } = "";

    /// <summary>Config value</summary>
    [OsqueryColumn("member_config_value")]
    public string MemberConfigValue { get; set; } = "";

    /// <summary>Config description</summary>
    [OsqueryColumn("member_config_description")]
    public string MemberConfigDescription { get; set; } = "";
}
