// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD instance configuration information.
/// </summary>
[OsqueryTable("lxd_instance_config")]
public class LxdInstanceConfig
{
    /// <summary>Instance name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Configuration parameter name</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Configuration parameter value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

}
