// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD images information.
/// </summary>
[OsqueryTable("lxd_images")]
public class LxdImage
{
    /// <summary>Image ID</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Target architecture for the image</summary>
    [OsqueryColumn("architecture")]
    public string Architecture { get; set; } = "";

    /// <summary>OS on which image is based</summary>
    [OsqueryColumn("os")]
    public string Os { get; set; } = "";

    /// <summary>OS release version on which the image is based</summary>
    [OsqueryColumn("release")]
    public string Release { get; set; } = "";

    /// <summary>Image description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Comma-separated list of image aliases</summary>
    [OsqueryColumn("aliases")]
    public string Aliases { get; set; } = "";

    /// <summary>Filename of the image file</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>Size of image in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Whether the image auto-updates (1) or not (0)</summary>
    [OsqueryColumn("auto_update")]
    public int AutoUpdate { get; set; }

    /// <summary>Whether image is cached (1) or not (0)</summary>
    [OsqueryColumn("cached")]
    public int Cached { get; set; }

    /// <summary>Whether image is public (1) or not (0)</summary>
    [OsqueryColumn("public")]
    public int @Public { get; set; }

    /// <summary>ISO time of image creation</summary>
    [OsqueryColumn("created_at")]
    public string CreatedAt { get; set; } = "";

    /// <summary>ISO time of image expiration</summary>
    [OsqueryColumn("expires_at")]
    public string ExpiresAt { get; set; } = "";

    /// <summary>ISO time of image upload</summary>
    [OsqueryColumn("uploaded_at")]
    public string UploadedAt { get; set; } = "";

    /// <summary>ISO time for the most recent use of this image in terms of container spawn</summary>
    [OsqueryColumn("last_used_at")]
    public string LastUsedAt { get; set; } = "";

    /// <summary>Server for image update</summary>
    [OsqueryColumn("update_source_server")]
    public string UpdateSourceServer { get; set; } = "";

    /// <summary>Protocol used for image information update and image import from source server</summary>
    [OsqueryColumn("update_source_protocol")]
    public string UpdateSourceProtocol { get; set; } = "";

    /// <summary>Certificate for update source server</summary>
    [OsqueryColumn("update_source_certificate")]
    public string UpdateSourceCertificate { get; set; } = "";

    /// <summary>Alias of image at update source server</summary>
    [OsqueryColumn("update_source_alias")]
    public string UpdateSourceAlias { get; set; } = "";
}
