// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD instance devices information.
/// </summary>
[OsqueryTable("lxd_instance_devices")]
public class LxdInstanceDevice
{
    /// <summary>Instance name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Name of the device</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>Device type</summary>
    [OsqueryColumn("device_type")]
    public string DeviceType { get; set; } = "";

    /// <summary>Device info param name</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Device info param value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

}
