// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD network information.
/// </summary>
[OsqueryTable("lxd_networks")]
public class LxdNetwork
{
    /// <summary>Name of the network</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Type of network</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>1 if network created by LXD, 0 otherwise</summary>
    [OsqueryColumn("managed")]
    public int Managed { get; set; }

    /// <summary>IPv4 address</summary>
    [OsqueryColumn("ipv4_address")]
    public string Ipv4Address { get; set; } = "";

    /// <summary>IPv6 address</summary>
    [OsqueryColumn("ipv6_address")]
    public string Ipv6Address { get; set; } = "";

    /// <summary>URLs for containers using this network</summary>
    [OsqueryColumn("used_by")]
    public string UsedBy { get; set; } = "";

    /// <summary>Number of bytes received on this network</summary>
    [OsqueryColumn("bytes_received")]
    public long BytesReceived { get; set; }

    /// <summary>Number of bytes sent on this network</summary>
    [OsqueryColumn("bytes_sent")]
    public long BytesSent { get; set; }

    /// <summary>Number of packets received on this network</summary>
    [OsqueryColumn("packets_received")]
    public long PacketsReceived { get; set; }

    /// <summary>Number of packets sent on this network</summary>
    [OsqueryColumn("packets_sent")]
    public long PacketsSent { get; set; }

    /// <summary>Hardware address for this network</summary>
    [OsqueryColumn("hwaddr")]
    public string Hwaddr { get; set; } = "";

    /// <summary>Network status</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>MTU size</summary>
    [OsqueryColumn("mtu")]
    public int Mtu { get; set; }

}
