// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// LXD storage pool information.
/// </summary>
[OsqueryTable("lxd_storage_pools")]
public class LxdStoragePool
{
    /// <summary>Name of the storage pool</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Storage driver</summary>
    [OsqueryColumn("driver")]
    public string Driver { get; set; } = "";

    /// <summary>Storage pool source</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Size of the storage pool</summary>
    [OsqueryColumn("size")]
    public string Size { get; set; } = "";

    /// <summary>Storage space used in bytes</summary>
    [OsqueryColumn("space_used")]
    public long SpaceUsed { get; set; }

    /// <summary>Total available storage space in bytes for this storage pool</summary>
    [OsqueryColumn("space_total")]
    public long SpaceTotal { get; set; }

    /// <summary>Number of inodes used</summary>
    [OsqueryColumn("inodes_used")]
    public long InodesUsed { get; set; }

    /// <summary>Total number of inodes available in this storage pool</summary>
    [OsqueryColumn("inodes_total")]
    public long InodesTotal { get; set; }
}
