// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Magic number recognition library table.
/// </summary>
[OsqueryTable("magic")]
public class Magic
{
    /// <summary>Absolute path to target file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Colon(:) separated list of files where the magic db file can be found. By default one of the following is used: /usr/share/file/magic/magic, /usr/share/misc/magic or /usr/share/misc/magic.mgc</summary>
    [OsqueryColumn("magic_db_files")]
    public string MagicDbFiles { get; set; } = "";

    /// <summary>Magic number data from libmagic</summary>
    [OsqueryColumn("data")]
    public string Data { get; set; } = "";

    /// <summary>MIME type data from libmagic</summary>
    [OsqueryColumn("mime_type")]
    public string MimeType { get; set; } = "";

    /// <summary>MIME encoding data from libmagic</summary>
    [OsqueryColumn("mime_encoding")]
    public string MimeEncoding { get; set; } = "";
}
