// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// The managed configuration policies from AD, MDM, MCX, etc.
/// </summary>
[OsqueryTable("managed_policies")]
public class ManagedPolicy
{
    /// <summary>System or manager-chosen domain key</summary>
    [OsqueryColumn("domain")]
    public string Domain { get; set; } = "";

    /// <summary>Optional UUID assigned to policy set</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Policy key name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Policy value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>Policy applies only this user</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>1 if policy was loaded manually, otherwise 0</summary>
    [OsqueryColumn("manual")]
    public int Manual { get; set; }
}
