// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Software RAID array settings.
/// </summary>
[OsqueryTable("md_devices")]
public class MdDevice
{
    /// <summary>md device name</summary>
    [OsqueryColumn("device_name")]
    public string DeviceName { get; set; } = "";

    /// <summary>Current state of the array</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>Current raid level of the array</summary>
    [OsqueryColumn("raid_level")]
    public int RaidLevel { get; set; }

    /// <summary>size of the array in blocks</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>chunk size in bytes</summary>
    [OsqueryColumn("chunk_size")]
    public long ChunkSize { get; set; }

    /// <summary>Number of configured RAID disks in array</summary>
    [OsqueryColumn("raid_disks")]
    public int RaidDisks { get; set; }

    /// <summary>Number of partitions or disk devices to comprise the array</summary>
    [OsqueryColumn("nr_raid_disks")]
    public int NrRaidDisks { get; set; }

    /// <summary>Number of working disks in array</summary>
    [OsqueryColumn("working_disks")]
    public int WorkingDisks { get; set; }

    /// <summary>Number of active disks in array</summary>
    [OsqueryColumn("active_disks")]
    public int ActiveDisks { get; set; }

    /// <summary>Number of failed disks in array</summary>
    [OsqueryColumn("failed_disks")]
    public int FailedDisks { get; set; }

    /// <summary>Number of idle disks in array</summary>
    [OsqueryColumn("spare_disks")]
    public int SpareDisks { get; set; }

    /// <summary>State of the superblock</summary>
    [OsqueryColumn("superblock_state")]
    public string SuperblockState { get; set; } = "";

    /// <summary>Version of the superblock</summary>
    [OsqueryColumn("superblock_version")]
    public string SuperblockVersion { get; set; } = "";

    /// <summary>Unix timestamp of last update</summary>
    [OsqueryColumn("superblock_update_time")]
    public long SuperblockUpdateTime { get; set; }

    /// <summary>Pages allocated in in-memory bitmap, if enabled</summary>
    [OsqueryColumn("bitmap_on_mem")]
    public string BitmapOnMem { get; set; } = "";

    /// <summary>Bitmap chunk size</summary>
    [OsqueryColumn("bitmap_chunk_size")]
    public string BitmapChunkSize { get; set; } = "";

    /// <summary>External referenced bitmap file</summary>
    [OsqueryColumn("bitmap_external_file")]
    public string BitmapExternalFile { get; set; } = "";

    /// <summary>Progress of the recovery activity</summary>
    [OsqueryColumn("recovery_progress")]
    public string RecoveryProgress { get; set; } = "";

    /// <summary>Estimated duration of recovery activity</summary>
    [OsqueryColumn("recovery_finish")]
    public string RecoveryFinish { get; set; } = "";

    /// <summary>Speed of recovery activity</summary>
    [OsqueryColumn("recovery_speed")]
    public string RecoverySpeed { get; set; } = "";

    /// <summary>Progress of the resync activity</summary>
    [OsqueryColumn("resync_progress")]
    public string ResyncProgress { get; set; } = "";

    /// <summary>Estimated duration of resync activity</summary>
    [OsqueryColumn("resync_finish")]
    public string ResyncFinish { get; set; } = "";

    /// <summary>Speed of resync activity</summary>
    [OsqueryColumn("resync_speed")]
    public string ResyncSpeed { get; set; } = "";

    /// <summary>Progress of the reshape activity</summary>
    [OsqueryColumn("reshape_progress")]
    public string ReshapeProgress { get; set; } = "";

    /// <summary>Estimated duration of reshape activity</summary>
    [OsqueryColumn("reshape_finish")]
    public string ReshapeFinish { get; set; } = "";

    /// <summary>Speed of reshape activity</summary>
    [OsqueryColumn("reshape_speed")]
    public string ReshapeSpeed { get; set; } = "";

    /// <summary>Progress of the check array activity</summary>
    [OsqueryColumn("check_array_progress")]
    public string CheckArrayProgress { get; set; } = "";

    /// <summary>Estimated duration of the check array activity</summary>
    [OsqueryColumn("check_array_finish")]
    public string CheckArrayFinish { get; set; } = "";

    /// <summary>Speed of the check array activity</summary>
    [OsqueryColumn("check_array_speed")]
    public string CheckArraySpeed { get; set; } = "";

    /// <summary>Unused devices</summary>
    [OsqueryColumn("unused_devices")]
    public string UnusedDevices { get; set; } = "";

    /// <summary>Other information associated with array from /proc/mdstat</summary>
    [OsqueryColumn("other")]
    public string Other { get; set; } = "";

}
