// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Drive devices used for Software RAID.
/// </summary>
[OsqueryTable("md_drives")]
public class MdDrive
{
    /// <summary>md device name</summary>
    [OsqueryColumn("md_device_name")]
    public string MdDeviceName { get; set; } = "";

    /// <summary>Drive device name</summary>
    [OsqueryColumn("drive_name")]
    public string DriveName { get; set; } = "";

    /// <summary>Slot position of disk</summary>
    [OsqueryColumn("slot")]
    public int Slot { get; set; }

    /// <summary>State of the drive</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

}
