// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Run searches against the spotlight database.
/// </summary>
[OsqueryTable("mdfind")]
public class Mdfind
{
    /// <summary>Path of the file returned from spotlight</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The query that was run to find the file</summary>
    [OsqueryColumn("query")]
    public string Query { get; set; } = "";

}
