// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Query file metadata in the Spotlight database.
/// </summary>
[OsqueryTable("mdls")]
public class Mdl
{
    /// <summary>Path of the file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Name of the metadata key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Value stored in the metadata key</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>CoreFoundation type of data stored in value</summary>
    [OsqueryColumn("valuetype")]
    public string Valuetype { get; set; } = "";
}
