// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Data associated for address mapping of physical memory devices.
/// </summary>
[OsqueryTable("memory_device_mapped_addresses")]
public class MemoryDeviceMappedAddress
{
    /// <summary>Handle, or instance number, associated with the structure</summary>
    [OsqueryColumn("handle")]
    public string Handle { get; set; } = "";

    /// <summary>Handle of the memory device structure associated with this structure</summary>
    [OsqueryColumn("memory_device_handle")]
    public string MemoryDeviceHandle { get; set; } = "";

    /// <summary>Handle of the memory array mapped address to which this device range is mapped to</summary>
    [OsqueryColumn("memory_array_mapped_address_handle")]
    public string MemoryArrayMappedAddressHandle { get; set; } = "";

    /// <summary>Physical stating address, in kilobytes, of a range of memory mapped to physical memory array</summary>
    [OsqueryColumn("starting_address")]
    public string StartingAddress { get; set; } = "";

    /// <summary>Physical ending address of last kilobyte of a range of memory mapped to physical memory array</summary>
    [OsqueryColumn("ending_address")]
    public string EndingAddress { get; set; } = "";

    /// <summary>Identifies the position of the referenced memory device in a row of the address partition</summary>
    [OsqueryColumn("partition_row_position")]
    public int PartitionRowPosition { get; set; }

    /// <summary>The position of the device in a interleave, i.e. 0 indicates non-interleave, 1 indicates 1st interleave, 2 indicates 2nd interleave, etc.</summary>
    [OsqueryColumn("interleave_position")]
    public int InterleavePosition { get; set; }

    /// <summary>The max number of consecutive rows from memory device that are accessed in a single interleave transfer; 0 indicates device is non-interleave</summary>
    [OsqueryColumn("interleave_data_depth")]
    public int InterleaveDataDepth { get; set; }

}
