// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Main memory information in bytes.
/// </summary>
[OsqueryTable("memory_info")]
public class MemoryInfo
{
    /// <summary>Total amount of physical RAM, in bytes</summary>
    [OsqueryColumn("memory_total")]
    public long MemoryTotal { get; set; }

    /// <summary>The amount of physical RAM, in bytes, left unused by the system</summary>
    [OsqueryColumn("memory_free")]
    public long MemoryFree { get; set; }

    /// <summary>The amount of physical RAM, in bytes, available for starting new applications, without swapping</summary>
    [OsqueryColumn("memory_available")]
    public long MemoryAvailable { get; set; }

    /// <summary>The amount of physical RAM, in bytes, used for file buffers</summary>
    [OsqueryColumn("buffers")]
    public long Buffers { get; set; }

    /// <summary>The amount of physical RAM, in bytes, used as cache memory</summary>
    [OsqueryColumn("cached")]
    public long Cached { get; set; }

    /// <summary>The amount of swap, in bytes, used as cache memory</summary>
    [OsqueryColumn("swap_cached")]
    public long SwapCached { get; set; }

    /// <summary>The total amount of buffer or page cache memory, in bytes, that is in active use</summary>
    [OsqueryColumn("active")]
    public long Active { get; set; }

    /// <summary>The total amount of buffer or page cache memory, in bytes, that are free and available</summary>
    [OsqueryColumn("inactive")]
    public long Inactive { get; set; }

    /// <summary>The total amount of swap available, in bytes</summary>
    [OsqueryColumn("swap_total")]
    public long SwapTotal { get; set; }

    /// <summary>The total amount of swap free, in bytes</summary>
    [OsqueryColumn("swap_free")]
    public long SwapFree { get; set; }

}
