// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Data associated with collection of memory devices that operate to form a memory address.
/// </summary>
[OsqueryTable("memory_arrays")]
public class MemoryArray
{
    /// <summary>Handle, or instance number, associated with the array</summary>
    [OsqueryColumn("handle")]
    public string Handle { get; set; } = "";

    /// <summary>Physical location of the memory array</summary>
    [OsqueryColumn("location")]
    public string Location { get; set; } = "";

    /// <summary>Function for which the array is used</summary>
    [OsqueryColumn("use")]
    public string Use { get; set; } = "";

    /// <summary>Primary hardware error correction or detection method supported</summary>
    [OsqueryColumn("memory_error_correction")]
    public string MemoryErrorCorrection { get; set; } = "";

    /// <summary>Maximum capacity of array in gigabytes</summary>
    [OsqueryColumn("max_capacity")]
    public int MaxCapacity { get; set; }

    /// <summary>Handle, or instance number, associated with any error that was detected for the array</summary>
    [OsqueryColumn("memory_error_info_handle")]
    public string MemoryErrorInfoHandle { get; set; } = "";

    /// <summary>Number of memory devices on array</summary>
    [OsqueryColumn("number_memory_devices")]
    public int NumberMemoryDevices { get; set; }

}
