// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// OS memory region map.
/// </summary>
[OsqueryTable("memory_map")]
public class MemoryMap
{
    /// <summary>Region name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Start address of memory region</summary>
    [OsqueryColumn("start")]
    public string Start { get; set; } = "";

    /// <summary>End address of memory region</summary>
    [OsqueryColumn("end")]
    public string End { get; set; } = "";

}
