// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Data associated with errors of a physical memory array.
/// </summary>
[OsqueryTable("memory_error_info")]
public class MemoryErrorInfo
{
    /// <summary>Handle, or instance number, associated with the structure</summary>
    [OsqueryColumn("handle")]
    public string Handle { get; set; } = "";

    /// <summary>type of error associated with current error status for array or device</summary>
    [OsqueryColumn("error_type")]
    public string ErrorType { get; set; } = "";

    /// <summary>Granularity to which the error can be resolved</summary>
    [OsqueryColumn("error_granularity")]
    public string ErrorGranularity { get; set; } = "";

    /// <summary>Memory access operation that caused the error</summary>
    [OsqueryColumn("error_operation")]
    public string ErrorOperation { get; set; } = "";

    /// <summary>Vendor specific ECC syndrome or CRC data associated with the erroneous access</summary>
    [OsqueryColumn("vendor_syndrome")]
    public string VendorSyndrome { get; set; } = "";

    /// <summary>32 bit physical address of the error based on the addressing of the bus to which the memory array is connected</summary>
    [OsqueryColumn("memory_array_error_address")]
    public string MemoryArrayErrorAddress { get; set; } = "";

    /// <summary>32 bit physical address of the error relative to the start of the failing memory address, in bytes</summary>
    [OsqueryColumn("device_error_address")]
    public string DeviceErrorAddress { get; set; } = "";

    /// <summary>Range, in bytes, within which this error can be determined, when an error address is given</summary>
    [OsqueryColumn("error_resolution")]
    public string ErrorResolution { get; set; } = "";

}
