// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Physical memory device (type 17) information retrieved from SMBIOS.
/// </summary>
[OsqueryTable("memory_devices")]
public class MemoryDevice
{
    /// <summary>Handle, or instance number, associated with the structure in SMBIOS</summary>
    [OsqueryColumn("handle")]
    public string Handle { get; set; } = "";

    /// <summary>The memory array that the device is attached to</summary>
    [OsqueryColumn("array_handle")]
    public string ArrayHandle { get; set; } = "";

    /// <summary>Implementation form factor for this memory device</summary>
    [OsqueryColumn("form_factor")]
    public string FormFactor { get; set; } = "";

    /// <summary>Total width, in bits, of this memory device, including any check or error-correction bits</summary>
    [OsqueryColumn("total_width")]
    public int TotalWidth { get; set; }

    /// <summary>Data width, in bits, of this memory device</summary>
    [OsqueryColumn("data_width")]
    public int DataWidth { get; set; }

    /// <summary>Size of memory device in Megabyte</summary>
    [OsqueryColumn("size")]
    public int Size { get; set; }

    /// <summary>Identifies if memory device is one of a set of devices.  A value of 0 indicates no set affiliation.</summary>
    [OsqueryColumn("set")]
    public int Set { get; set; }

    /// <summary>String number of the string that identifies the physically-labeled socket or board position where the memory device is located</summary>
    [OsqueryColumn("device_locator")]
    public string DeviceLocator { get; set; } = "";

    /// <summary>String number of the string that identifies the physically-labeled bank where the memory device is located</summary>
    [OsqueryColumn("bank_locator")]
    public string BankLocator { get; set; } = "";

    /// <summary>Type of memory used</summary>
    [OsqueryColumn("memory_type")]
    public string MemoryType { get; set; } = "";

    /// <summary>Additional details for memory device</summary>
    [OsqueryColumn("memory_type_details")]
    public string MemoryTypeDetails { get; set; } = "";

    /// <summary>Max speed of memory device in megatransfers per second (MT/s)</summary>
    [OsqueryColumn("max_speed")]
    public int MaxSpeed { get; set; }

    /// <summary>Configured speed of memory device in megatransfers per second (MT/s)</summary>
    [OsqueryColumn("configured_clock_speed")]
    public int ConfiguredClockSpeed { get; set; }

    /// <summary>Manufacturer ID string</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>Serial number of memory device</summary>
    [OsqueryColumn("serial_number")]
    public string SerialNumber { get; set; } = "";

    /// <summary>Manufacturer specific asset tag of memory device</summary>
    [OsqueryColumn("asset_tag")]
    public string AssetTag { get; set; } = "";

    /// <summary>Manufacturer specific serial number of memory device</summary>
    [OsqueryColumn("part_number")]
    public string PartNumber { get; set; } = "";

    /// <summary>Minimum operating voltage of device in millivolts</summary>
    [OsqueryColumn("min_voltage")]
    public int MinVoltage { get; set; }

    /// <summary>Maximum operating voltage of device in millivolts</summary>
    [OsqueryColumn("max_voltage")]
    public int MaxVoltage { get; set; }

    /// <summary>Configured operating voltage of device in millivolts</summary>
    [OsqueryColumn("configured_voltage")]
    public int ConfiguredVoltage { get; set; }

}
