// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// System mounted devices and filesystems (not process specific).
/// </summary>
[OsqueryTable("mounts")]
public class Mount
{
    /// <summary>Mounted device</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>Mounted device alias</summary>
    [OsqueryColumn("device_alias")]
    public string DeviceAlias { get; set; } = "";

    /// <summary>Mounted device path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Mounted device type</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Block size in bytes</summary>
    [OsqueryColumn("blocks_size")]
    public long BlocksSize { get; set; }

    /// <summary>Mounted device used blocks</summary>
    [OsqueryColumn("blocks")]
    public long Blocks { get; set; }

    /// <summary>Mounted device blocks available to root users, a superset of blocks_available</summary>
    [OsqueryColumn("blocks_free")]
    public long BlocksFree { get; set; }

    /// <summary>Mounted device blocks available to non-root users</summary>
    [OsqueryColumn("blocks_available")]
    public long BlocksAvailable { get; set; }

    /// <summary>Mounted device used inodes</summary>
    [OsqueryColumn("inodes")]
    public long Inodes { get; set; }

    /// <summary>Mounted device free inodes</summary>
    [OsqueryColumn("inodes_free")]
    public long InodesFree { get; set; }

    /// <summary>Mounted device flags</summary>
    [OsqueryColumn("flags")]
    public string Flags { get; set; } = "";
}
