// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Various pieces of data stored in the model specific register per processor. NOTE: the msr kernel module must be enabled, and osquery must be run as root.
/// </summary>
[OsqueryTable("msr")]
public class Msr
{
    /// <summary>The processor number as reported in /proc/cpuinfo</summary>
    [OsqueryColumn("processor_number")]
    public long ProcessorNumber { get; set; }

    /// <summary>Whether the turbo feature is disabled.</summary>
    [OsqueryColumn("turbo_disabled")]
    public long TurboDisabled { get; set; }

    /// <summary>The turbo feature ratio limit.</summary>
    [OsqueryColumn("turbo_ratio_limit")]
    public long TurboRatioLimit { get; set; }

    /// <summary>Platform information.</summary>
    [OsqueryColumn("platform_info")]
    public long PlatformInfo { get; set; }

    /// <summary>Performance setting for the processor.</summary>
    [OsqueryColumn("perf_ctl")]
    public long PerfCtl { get; set; }

    /// <summary>Performance status for the processor.</summary>
    [OsqueryColumn("perf_status")]
    public long PerfStatus { get; set; }

    /// <summary>Bitfield controlling enabled features.</summary>
    [OsqueryColumn("feature_control")]
    public long FeatureControl { get; set; }

    /// <summary>Run Time Average Power Limiting power limit.</summary>
    [OsqueryColumn("rapl_power_limit")]
    public long RaplPowerLimit { get; set; }

    /// <summary>Run Time Average Power Limiting energy status.</summary>
    [OsqueryColumn("rapl_energy_status")]
    public long RaplEnergyStatus { get; set; }

    /// <summary>Run Time Average Power Limiting power units.</summary>
    [OsqueryColumn("rapl_power_units")]
    public long RaplPowerUnits { get; set; }
}
