// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Node packages installed in a system.
/// </summary>
[OsqueryTable("npm_packages")]
public class NpmPackage
{
    /// <summary>Package display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package-supplied version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package-supplied description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Package-supplied author</summary>
    [OsqueryColumn("author")]
    public string Author { get; set; } = "";

    /// <summary>License under which package is launched</summary>
    [OsqueryColumn("license")]
    public string License { get; set; } = "";

    /// <summary>Package supplied homepage</summary>
    [OsqueryColumn("homepage")]
    public string Homepage { get; set; } = "";

    /// <summary>Path at which this module resides</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Directory where node_modules are located</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>Nesting depth of the package (0 = direct dependency)</summary>
    [OsqueryColumn("depth")]
    public int Depth { get; set; }

    /// <summary>Maximum depth to search for nested packages (default 100, -1 = unlimited)</summary>
    [OsqueryColumn("max_depth")]
    public int MaxDepth { get; set; }

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";
}
