// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Display basic NT domain information of a Windows machine.
/// </summary>
[OsqueryTable("ntdomains")]
public class Ntdomain
{
    /// <summary>The label by which the object is known.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The name of the site where the domain controller is configured.</summary>
    [OsqueryColumn("client_site_name")]
    public string ClientSiteName { get; set; } = "";

    /// <summary>The name of the site where the domain controller is located.</summary>
    [OsqueryColumn("dc_site_name")]
    public string DcSiteName { get; set; } = "";

    /// <summary>The name of the root of the DNS tree.</summary>
    [OsqueryColumn("dns_forest_name")]
    public string DnsForestName { get; set; } = "";

    /// <summary>The IP Address of the discovered domain controller..</summary>
    [OsqueryColumn("domain_controller_address")]
    public string DomainControllerAddress { get; set; } = "";

    /// <summary>The name of the discovered domain controller.</summary>
    [OsqueryColumn("domain_controller_name")]
    public string DomainControllerName { get; set; } = "";

    /// <summary>The name of the domain.</summary>
    [OsqueryColumn("domain_name")]
    public string DomainName { get; set; } = "";

    /// <summary>The current status of the domain object.</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";
}
