// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track time/action changes to files specified in configuration data.
/// </summary>
[OsqueryTable("ntfs_journal_events")]
public class NtfsJournalEvent
{
    /// <summary>Change action (Write, Delete, etc)</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>The category that the event originated from</summary>
    [OsqueryColumn("category")]
    public string Category { get; set; } = "";

    /// <summary>Old path (renames only)</summary>
    [OsqueryColumn("old_path")]
    public string OldPath { get; set; } = "";

    /// <summary>Path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Journal record timestamp</summary>
    [OsqueryColumn("record_timestamp")]
    public string RecordTimestamp { get; set; } = "";

    /// <summary>The update sequence number that identifies the journal record</summary>
    [OsqueryColumn("record_usn")]
    public string RecordUsn { get; set; } = "";

    /// <summary>The ordinal that associates a journal record with a filename</summary>
    [OsqueryColumn("node_ref_number")]
    public string NodeRefNumber { get; set; } = "";

    /// <summary>The ordinal that associates a journal record with a filename's parent directory</summary>
    [OsqueryColumn("parent_ref_number")]
    public string ParentRefNumber { get; set; } = "";

    /// <summary>The drive letter identifying the source journal</summary>
    [OsqueryColumn("drive_letter")]
    public string DriveLetter { get; set; } = "";

    /// <summary>File attributes</summary>
    [OsqueryColumn("file_attributes")]
    public string FileAttributes { get; set; } = "";

    /// <summary>Set to 1 if either path or old_path only contains the file or folder name</summary>
    [OsqueryColumn("partial")]
    public long Partial { get; set; }

    /// <summary>Time of file event</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

}
