// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve NTFS ACL permission information for files and directories.
/// </summary>
[OsqueryTable("ntfs_acl_permissions")]
public class NtfsAclPermission
{
    /// <summary>Path to the file or directory.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Type of access mode for the access control entry.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>User or group to which the ACE applies.</summary>
    [OsqueryColumn("principal")]
    public string Principal { get; set; } = "";

    /// <summary>Specific permissions that indicate the rights described by the ACE.</summary>
    [OsqueryColumn("access")]
    public string Access { get; set; } = "";

    /// <summary>The inheritance policy of the ACE.</summary>
    [OsqueryColumn("inherited_from")]
    public string InheritedFrom { get; set; } = "";
}
