// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// View recently opened Office documents.
/// </summary>
[OsqueryTable("office_mru")]
public class OfficeMru
{
    /// <summary>Associated Office application</summary>
    [OsqueryColumn("application")]
    public string Application { get; set; } = "";

    /// <summary>Office application version number</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>File path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Most recent opened time file was opened</summary>
    [OsqueryColumn("last_opened_time")]
    public long LastOpenedTime { get; set; }

    /// <summary>User SID</summary>
    [OsqueryColumn("sid")]
    public string Sid { get; set; } = "";
}
