// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// List of active osquery extensions.
/// </summary>
[OsqueryTable("osquery_extensions")]
public class OsqueryExtension
{
    /// <summary>The transient ID assigned for communication</summary>
    [OsqueryColumn("uuid")]
    public long Uuid { get; set; }

    /// <summary>Extension's name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Extension's version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>osquery SDK version used to build the extension</summary>
    [OsqueryColumn("sdk_version")]
    public string SdkVersion { get; set; } = "";

    /// <summary>Path of the extension's Thrift connection or library path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>SDK extension type: core, extension, or module</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";
}
