// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Top level information about the running version of osquery.
/// </summary>
[OsqueryTable("osquery_info")]
public class OsqueryInfo
{
    /// <summary>Process (or thread/handle) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>Unique ID provided by the system</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Unique, long-lived ID per instance of osquery</summary>
    [OsqueryColumn("instance_id")]
    public string InstanceId { get; set; } = "";

    /// <summary>osquery toolkit version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Hash of the working configuration state</summary>
    [OsqueryColumn("config_hash")]
    public string ConfigHash { get; set; } = "";

    /// <summary>1 if the config was loaded and considered valid, else 0</summary>
    [OsqueryColumn("config_valid")]
    public int ConfigValid { get; set; }

    /// <summary>osquery extensions status</summary>
    [OsqueryColumn("extensions")]
    public string Extensions { get; set; } = "";

    /// <summary>osquery toolkit build platform</summary>
    [OsqueryColumn("build_platform")]
    public string BuildPlatform { get; set; } = "";

    /// <summary>osquery toolkit platform distribution name (os version)</summary>
    [OsqueryColumn("build_distro")]
    public string BuildDistro { get; set; } = "";

    /// <summary>UNIX time in seconds when the process started</summary>
    [OsqueryColumn("start_time")]
    public int StartTime { get; set; }

    /// <summary>Process (or thread/handle) ID of optional watcher process</summary>
    [OsqueryColumn("watcher")]
    public int Watcher { get; set; }

    /// <summary>The osquery platform bitmask</summary>
    [OsqueryColumn("platform_mask")]
    public int PlatformMask { get; set; }
}
