// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Information about the event publishers and subscribers.
/// </summary>
[OsqueryTable("osquery_events")]
public class OsqueryEvent
{
    /// <summary>Event publisher or subscriber name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Name of the associated publisher</summary>
    [OsqueryColumn("publisher")]
    public string Publisher { get; set; } = "";

    /// <summary>Either publisher or subscriber</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Number of subscriptions the publisher received or subscriber used</summary>
    [OsqueryColumn("subscriptions")]
    public int Subscriptions { get; set; }

    /// <summary>Number of events emitted or received since osquery started</summary>
    [OsqueryColumn("events")]
    public int Events { get; set; }

    /// <summary>Publisher only: number of runloop restarts</summary>
    [OsqueryColumn("refreshes")]
    public int Refreshes { get; set; }

    /// <summary>1 if the publisher or subscriber is active else 0</summary>
    [OsqueryColumn("active")]
    public int Active { get; set; }

}
