// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Information about the current queries that are scheduled in osquery.
/// </summary>
[OsqueryTable("osquery_schedule")]
public class OsquerySchedule
{
    /// <summary>The given name for this query</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The exact query to run</summary>
    [OsqueryColumn("query")]
    public string Query { get; set; } = "";

    /// <summary>The interval in seconds to run this query, not an exact interval</summary>
    [OsqueryColumn("interval")]
    public int Interval { get; set; }

    /// <summary>Number of times the query was executed</summary>
    [OsqueryColumn("executions")]
    public long Executions { get; set; }

    /// <summary>UNIX time stamp in seconds of the last completed execution</summary>
    [OsqueryColumn("last_executed")]
    public long LastExecuted { get; set; }

    /// <summary>1 if the query is denylisted else 0</summary>
    [OsqueryColumn("denylisted")]
    public int Denylisted { get; set; }

    /// <summary>Cumulative total number of bytes generated by the resultant rows of the query</summary>
    [OsqueryColumn("output_size")]
    public long OutputSize { get; set; }

    /// <summary>Total wall time in seconds spent executing (deprecated), hidden=True</summary>
    [OsqueryColumn("wall_time")]
    public long WallTime { get; set; }

    /// <summary>Total wall time in milliseconds spent executing</summary>
    [OsqueryColumn("wall_time_ms")]
    public long WallTimeMs { get; set; }

    /// <summary>Wall time in milliseconds of the latest execution</summary>
    [OsqueryColumn("last_wall_time_ms")]
    public long LastWallTimeMs { get; set; }

    /// <summary>Total user time in milliseconds spent executing</summary>
    [OsqueryColumn("user_time")]
    public long UserTime { get; set; }

    /// <summary>User time in milliseconds of the latest execution</summary>
    [OsqueryColumn("last_user_time")]
    public long LastUserTime { get; set; }

    /// <summary>Total system time in milliseconds spent executing</summary>
    [OsqueryColumn("system_time")]
    public long SystemTime { get; set; }

    /// <summary>System time in milliseconds of the latest execution</summary>
    [OsqueryColumn("last_system_time")]
    public long LastSystemTime { get; set; }

    /// <summary>Average of the bytes of resident memory left allocated after collecting results</summary>
    [OsqueryColumn("average_memory")]
    public long AverageMemory { get; set; }

    /// <summary>Resident memory in bytes left allocated after collecting results of the latest execution</summary>
    [OsqueryColumn("last_memory")]
    public long LastMemory { get; set; }

}
