// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A single row containing the operating system name and version.
/// </summary>
[OsqueryTable("os_version")]
public class OsVersion
{
    /// <summary>Distribution or product name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Pretty, suitable for presentation, OS version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Major release version</summary>
    [OsqueryColumn("major")]
    public int Major { get; set; }

    /// <summary>Minor release version</summary>
    [OsqueryColumn("minor")]
    public int Minor { get; set; }

    /// <summary>Optional patch release</summary>
    [OsqueryColumn("patch")]
    public int Patch { get; set; }

    /// <summary>Optional build-specific or variant string</summary>
    [OsqueryColumn("build")]
    public string Build { get; set; } = "";

    /// <summary>OS Platform or ID</summary>
    [OsqueryColumn("platform")]
    public string Platform { get; set; } = "";

    /// <summary>Closely related platforms</summary>
    [OsqueryColumn("platform_like")]
    public string PlatformLike { get; set; } = "";

    /// <summary>OS version codename</summary>
    [OsqueryColumn("codename")]
    public string Codename { get; set; } = "";

    /// <summary>OS Architecture</summary>
    [OsqueryColumn("arch")]
    public string Arch { get; set; } = "";

    /// <summary>Optional extra release specification</summary>
    [OsqueryColumn("extra")]
    public string Extra { get; set; } = "";

    /// <summary>The install date of the OS.</summary>
    [OsqueryColumn("install_date")]
    public long InstallDate { get; set; }

    /// <summary>Update Build Revision, refers to the specific revision number of a Windows update</summary>
    [OsqueryColumn("revision")]
    public int Revision { get; set; }

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";
}
