// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS package receipt details.
/// </summary>
[OsqueryTable("package_receipts")]
public class PackageReceipt
{
    /// <summary>Package domain identifier</summary>
    [OsqueryColumn("package_id")]
    public string PackageId { get; set; } = "";

    /// <summary>Filename of original .pkg file</summary>
    [OsqueryColumn("package_filename")]
    public string PackageFilename { get; set; } = "";

    /// <summary>Installed package version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Optional relative install path on volume</summary>
    [OsqueryColumn("location")]
    public string Location { get; set; } = "";

    /// <summary>Timestamp of install time</summary>
    [OsqueryColumn("install_time")]
    public double InstallTime { get; set; }

    /// <summary>Name of installer process</summary>
    [OsqueryColumn("installer_name")]
    public string InstallerName { get; set; } = "";

    /// <summary>Path of receipt plist</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
