// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS package install history.
/// </summary>
[OsqueryTable("package_install_history")]
public class PackageInstallHistory
{
    /// <summary>Label packageIdentifiers</summary>
    [OsqueryColumn("package_id")]
    public string PackageId { get; set; } = "";

    /// <summary>Label date as UNIX timestamp</summary>
    [OsqueryColumn("time")]
    public int Time { get; set; }

    /// <summary>Package display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package display version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Install source: usually the installer process name</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Package content_type (optional)</summary>
    [OsqueryColumn("content_type")]
    public string ContentType { get; set; } = "";

}
