// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS package bill of materials (BOM) file list.
/// </summary>
[OsqueryTable("package_bom")]
public class PackageBom
{
    /// <summary>Package file or directory</summary>
    [OsqueryColumn("filepath")]
    public string Filepath { get; set; } = "";

    /// <summary>Expected user of file or directory</summary>
    [OsqueryColumn("uid")]
    public int Uid { get; set; }

    /// <summary>Expected group of file or directory</summary>
    [OsqueryColumn("gid")]
    public int Gid { get; set; }

    /// <summary>Expected permissions</summary>
    [OsqueryColumn("mode")]
    public int Mode { get; set; }

    /// <summary>Expected file size</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Timestamp the file was installed</summary>
    [OsqueryColumn("modified_time")]
    public int ModifiedTime { get; set; }

    /// <summary>Path of package bom</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
