// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// OpenDirectory account policies for macOS including password content, authentication, and password change policies.
/// </summary>
[OsqueryTable("password_policy")]
public class PasswordPolicy
{
    /// <summary>User ID for the policy, -1 for policies that are global</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Policy Identifier</summary>
    [OsqueryColumn("policy_identifier")]
    public string PolicyIdentifier { get; set; } = "";

    /// <summary>Policy content</summary>
    [OsqueryColumn("policy_content")]
    public string PolicyContent { get; set; } = "";

    /// <summary>Policy description</summary>
    [OsqueryColumn("policy_description")]
    public string PolicyDescription { get; set; } = "";

    /// <summary>Policy category: passwordPolicyAuthentication, passwordPolicyPasswordChange, or passwordPolicyPasswordContent</summary>
    [OsqueryColumn("policy_category")]
    public string PolicyCategory { get; set; } = "";

    /// <summary>Policy parameters serialized as JSON</summary>
    [OsqueryColumn("policy_parameters")]
    public string PolicyParameters { get; set; } = "";

}
