// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// PCI devices active on the host system.
/// </summary>
[OsqueryTable("pci_devices")]
public class PciDevice
{
    /// <summary>PCI Device used slot</summary>
    [OsqueryColumn("pci_slot")]
    public string PciSlot { get; set; } = "";

    /// <summary>PCI Device class</summary>
    [OsqueryColumn("pci_class")]
    public string PciClass { get; set; } = "";

    /// <summary>PCI Device used driver</summary>
    [OsqueryColumn("driver")]
    public string Driver { get; set; } = "";

    /// <summary>PCI Device vendor</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Hex encoded PCI Device vendor identifier</summary>
    [OsqueryColumn("vendor_id")]
    public string VendorId { get; set; } = "";

    /// <summary>PCI Device model</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>Hex encoded PCI Device model identifier</summary>
    [OsqueryColumn("model_id")]
    public string ModelId { get; set; } = "";

    /// <summary>PCI Device class ID in hex format</summary>
    [OsqueryColumn("pci_class_id")]
    public string PciClassId { get; set; } = "";

    /// <summary>PCI Device  subclass in hex format</summary>
    [OsqueryColumn("pci_subclass_id")]
    public string PciSubclassId { get; set; } = "";

    /// <summary>PCI Device subclass</summary>
    [OsqueryColumn("pci_subclass")]
    public string PciSubclass { get; set; } = "";

    /// <summary>Vendor ID of PCI device subsystem</summary>
    [OsqueryColumn("subsystem_vendor_id")]
    public string SubsystemVendorId { get; set; } = "";

    /// <summary>Vendor of PCI device subsystem</summary>
    [OsqueryColumn("subsystem_vendor")]
    public string SubsystemVendor { get; set; } = "";

    /// <summary>Model ID of PCI device subsystem</summary>
    [OsqueryColumn("subsystem_model_id")]
    public string SubsystemModelId { get; set; } = "";

    /// <summary>Device description of PCI device subsystem</summary>
    [OsqueryColumn("subsystem_model")]
    public string SubsystemModel { get; set; } = "";

}
