// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Provides provides raw data from performance counters that monitor hard or fixed disk drives on the system.
/// </summary>
[OsqueryTable("physical_disk_performance")]
public class PhysicalDiskPerformance
{
    /// <summary>Name of the physical disk</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Average number of bytes transferred from the disk during read operations</summary>
    [OsqueryColumn("avg_disk_bytes_per_read")]
    public long AvgDiskBytesPerRead { get; set; }

    /// <summary>Average number of bytes transferred to the disk during write operations</summary>
    [OsqueryColumn("avg_disk_bytes_per_write")]
    public long AvgDiskBytesPerWrite { get; set; }

    /// <summary>Average number of read requests that were queued for the selected disk during the sample interval</summary>
    [OsqueryColumn("avg_disk_read_queue_length")]
    public long AvgDiskReadQueueLength { get; set; }

    /// <summary>Average number of write requests that were queued for the selected disk during the sample interval</summary>
    [OsqueryColumn("avg_disk_write_queue_length")]
    public long AvgDiskWriteQueueLength { get; set; }

    /// <summary>Average time, in seconds, of a read operation of data from the disk</summary>
    [OsqueryColumn("avg_disk_sec_per_read")]
    public int AvgDiskSecPerRead { get; set; }

    /// <summary>Average time, in seconds, of a write operation of data to the disk</summary>
    [OsqueryColumn("avg_disk_sec_per_write")]
    public int AvgDiskSecPerWrite { get; set; }

    /// <summary>Number of requests outstanding on the disk at the time the performance data is collected</summary>
    [OsqueryColumn("current_disk_queue_length")]
    public int CurrentDiskQueueLength { get; set; }

    /// <summary>Percentage of elapsed time that the selected disk drive is busy servicing read requests</summary>
    [OsqueryColumn("percent_disk_read_time")]
    public long PercentDiskReadTime { get; set; }

    /// <summary>Percentage of elapsed time that the selected disk drive is busy servicing write requests</summary>
    [OsqueryColumn("percent_disk_write_time")]
    public long PercentDiskWriteTime { get; set; }

    /// <summary>Percentage of elapsed time that the selected disk drive is busy servicing read or write requests</summary>
    [OsqueryColumn("percent_disk_time")]
    public long PercentDiskTime { get; set; }

    /// <summary>Percentage of time during the sample interval that the disk was idle</summary>
    [OsqueryColumn("percent_idle_time")]
    public long PercentIdleTime { get; set; }
}
