// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Named and Anonymous pipes.
/// </summary>
[OsqueryTable("pipes")]
public class Pipe
{
    /// <summary>Process ID of the process to which the pipe belongs</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Name of the pipe</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Number of instances of the named pipe</summary>
    [OsqueryColumn("instances")]
    public int Instances { get; set; }

    /// <summary>The maximum number of instances creatable for this pipe</summary>
    [OsqueryColumn("max_instances")]
    public int MaxInstances { get; set; }

    /// <summary>The flags indicating whether this pipe connection is a server or client end, and if the pipe for sending messages or bytes</summary>
    [OsqueryColumn("flags")]
    public string Flags { get; set; } = "";

}
