// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Information about EFI/UEFI/ROM and platform/boot.
/// </summary>
[OsqueryTable("platform_info")]
public class PlatformInfo
{
    /// <summary>Platform code vendor</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Platform code version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Self-reported platform code update date</summary>
    [OsqueryColumn("date")]
    public string Date { get; set; } = "";

    /// <summary>BIOS major and minor revision</summary>
    [OsqueryColumn("revision")]
    public string Revision { get; set; } = "";

    /// <summary>Platform-specific additional information</summary>
    [OsqueryColumn("extra")]
    public string Extra { get; set; } = "";

    /// <summary>The type of firmware (uefi, bios, iboot, openfirmware, unknown).</summary>
    [OsqueryColumn("firmware_type")]
    public string FirmwareType { get; set; } = "";

    /// <summary>Relative address of firmware mapping</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";

    /// <summary>Size in bytes of firmware</summary>
    [OsqueryColumn("size")]
    public string Size { get; set; } = "";

    /// <summary>(Optional) size of firmware volume</summary>
    [OsqueryColumn("volume_size")]
    public int VolumeSize { get; set; }

}
