// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Read and parse a plist file.
/// </summary>
[OsqueryTable("plist")]
public class Plist
{
    /// <summary>Preference top-level key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Intermediate key path, includes lists/dicts</summary>
    [OsqueryColumn("subkey")]
    public string Subkey { get; set; } = "";

    /// <summary>String value of most CF types</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>(required) read preferences from a plist</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";
}
