// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A summary about portage configurations like keywords, mask and unmask.
/// </summary>
[OsqueryTable("portage_keywords")]
public class PortageKeyword
{
    /// <summary>Package name</summary>
    [OsqueryColumn("package")]
    public string Package { get; set; } = "";

    /// <summary>The version which are affected by the use flags, empty means all</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The keyword applied to the package</summary>
    [OsqueryColumn("keyword")]
    public string Keyword { get; set; } = "";

    /// <summary>If the package is masked</summary>
    [OsqueryColumn("mask")]
    public int Mask { get; set; }

    /// <summary>If the package is unmasked</summary>
    [OsqueryColumn("unmask")]
    public int Unmask { get; set; }
}
