// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// List of currently installed packages.
/// </summary>
[OsqueryTable("portage_packages")]
public class PortagePackage
{
    /// <summary>Package name</summary>
    [OsqueryColumn("package")]
    public string Package { get; set; } = "";

    /// <summary>The version which are affected by the use flags, empty means all</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The slot used by package</summary>
    [OsqueryColumn("slot")]
    public string Slot { get; set; } = "";

    /// <summary>Unix time when package was built</summary>
    [OsqueryColumn("build_time")]
    public long BuildTime { get; set; }

    /// <summary>From which repository the ebuild was used</summary>
    [OsqueryColumn("repository")]
    public string Repository { get; set; } = "";

    /// <summary>The eapi for the ebuild</summary>
    [OsqueryColumn("eapi")]
    public long Eapi { get; set; }

    /// <summary>The size of the package</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>If package is in the world file</summary>
    [OsqueryColumn("world")]
    public int World { get; set; }
}
