// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// List of enabled portage USE values for specific package.
/// </summary>
[OsqueryTable("portage_use")]
public class PortageUse
{
    /// <summary>Package name</summary>
    [OsqueryColumn("package")]
    public string Package { get; set; } = "";

    /// <summary>The version of the installed package</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>USE flag which has been enabled for package</summary>
    [OsqueryColumn("use")]
    public string Use { get; set; } = "";
}
