// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Machine power (currents, voltages, wattages, etc) sensors.
/// </summary>
[OsqueryTable("power_sensors")]
public class PowerSensor
{
    /// <summary>The SMC key on macOS</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>The sensor category: currents, voltage, wattage</summary>
    [OsqueryColumn("category")]
    public string Category { get; set; } = "";

    /// <summary>Name of power source</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Power in Watts</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

}
