// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Powershell script blocks reconstructed to their full script content, this table requires script block logging to be enabled.
/// </summary>
[OsqueryTable("powershell_events")]
public class PowershellEvent
{
    /// <summary>Timestamp the event was received by the osquery event publisher</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>System time at which the Powershell script event occurred</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>The unique GUID of the powershell script to which this block belongs</summary>
    [OsqueryColumn("script_block_id")]
    public string ScriptBlockId { get; set; } = "";

    /// <summary>The total number of script blocks for this script</summary>
    [OsqueryColumn("script_block_count")]
    public int ScriptBlockCount { get; set; }

    /// <summary>The text content of the Powershell script</summary>
    [OsqueryColumn("script_text")]
    public string ScriptText { get; set; } = "";

    /// <summary>The name of the Powershell script</summary>
    [OsqueryColumn("script_name")]
    public string ScriptName { get; set; } = "";

    /// <summary>The path for the Powershell script</summary>
    [OsqueryColumn("script_path")]
    public string ScriptPath { get; set; } = "";

    /// <summary>How similar the Powershell script is to a provided 'normal' character frequency</summary>
    [OsqueryColumn("cosine_similarity")]
    public double CosineSimilarity { get; set; }
}
