// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS defaults and managed preferences.
/// </summary>
[OsqueryTable("preferences")]
public class Preference
{
    /// <summary>Application ID usually in com.name.product format</summary>
    [OsqueryColumn("domain")]
    public string Domain { get; set; } = "";

    /// <summary>Preference top-level key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Intemediate key path, includes lists/dicts</summary>
    [OsqueryColumn("subkey")]
    public string Subkey { get; set; } = "";

    /// <summary>String value of most CF types</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>1 if the value is forced/managed, else 0</summary>
    [OsqueryColumn("forced")]
    public int Forced { get; set; }

    /// <summary>(optional) read preferences for a specific user</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>'current' or 'any' host, where 'current' takes precedence</summary>
    [OsqueryColumn("host")]
    public string Host { get; set; } = "";
}
