// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Process memory mapped files and pseudo device/regions.
/// </summary>
[OsqueryTable("process_memory_map")]
public class ProcessMemoryMap
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>Virtual start address (hex)</summary>
    [OsqueryColumn("start")]
    public string Start { get; set; } = "";

    /// <summary>Virtual end address (hex)</summary>
    [OsqueryColumn("end")]
    public string End { get; set; } = "";

    /// <summary>r=read, w=write, x=execute, p=private (cow)</summary>
    [OsqueryColumn("permissions")]
    public string Permissions { get; set; } = "";

    /// <summary>Offset into mapped path</summary>
    [OsqueryColumn("offset")]
    public long Offset { get; set; }

    /// <summary>MA:MI Major/minor device ID</summary>
    [OsqueryColumn("device")]
    public string Device { get; set; } = "";

    /// <summary>Mapped path inode, 0 means uninitialized (BSS)</summary>
    [OsqueryColumn("inode")]
    public int Inode { get; set; }

    /// <summary>Path to mapped file or mapped type</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>1 If path is a pseudo path, else 0</summary>
    [OsqueryColumn("pseudo")]
    public int Pseudo { get; set; }

}
