// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Windows process execution events.
/// </summary>
[OsqueryTable("process_etw_events")]
public class ProcessEtwEvent
{
    /// <summary>Event Type (ProcessStart, ProcessStop)</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Parent Process ID</summary>
    [OsqueryColumn("ppid")]
    public long Ppid { get; set; }

    /// <summary>Session ID</summary>
    [OsqueryColumn("session_id")]
    public int SessionId { get; set; }

    /// <summary>Process Flags</summary>
    [OsqueryColumn("flags")]
    public int Flags { get; set; }

    /// <summary>Exit Code - Present only on ProcessStop events</summary>
    [OsqueryColumn("exit_code")]
    public int ExitCode { get; set; }

    /// <summary>Path of executed binary</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Command Line</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>User rights - primary token username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Primary token elevation type - Present only on ProcessStart events</summary>
    [OsqueryColumn("token_elevation_type")]
    public string TokenElevationType { get; set; } = "";

    /// <summary>Primary token elevation status - Present only on ProcessStart events</summary>
    [OsqueryColumn("token_elevation_status")]
    public int TokenElevationStatus { get; set; }

    /// <summary>Primary token mandatory label sid - Present only on ProcessStart events</summary>
    [OsqueryColumn("mandatory_label")]
    public string MandatoryLabel { get; set; } = "";

    /// <summary>Event timestamp in DATETIME format</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>Event timestamp in Windows format</summary>
    [OsqueryColumn("time_windows")]
    public long TimeWindows { get; set; }

    /// <summary>Event timestamp in Unix format</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public int Eid { get; set; }

    /// <summary>Process ID of the process reporting the event</summary>
    [OsqueryColumn("header_pid")]
    public long HeaderPid { get; set; }

    /// <summary>Process Sequence Number - Present only on ProcessStart events</summary>
    [OsqueryColumn("process_sequence_number")]
    public long ProcessSequenceNumber { get; set; }

    /// <summary>Parent Process Sequence Number - Present only on ProcessStart events</summary>
    [OsqueryColumn("parent_process_sequence_number")]
    public long ParentProcessSequenceNumber { get; set; }
}
