// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Linux namespaces for processes running on the host system.
/// </summary>
[OsqueryTable("process_namespaces")]
public class ProcessNamespace
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>cgroup namespace inode</summary>
    [OsqueryColumn("cgroup_namespace")]
    public string CgroupNamespace { get; set; } = "";

    /// <summary>ipc namespace inode</summary>
    [OsqueryColumn("ipc_namespace")]
    public string IpcNamespace { get; set; } = "";

    /// <summary>mnt namespace inode</summary>
    [OsqueryColumn("mnt_namespace")]
    public string MntNamespace { get; set; } = "";

    /// <summary>net namespace inode</summary>
    [OsqueryColumn("net_namespace")]
    public string NetNamespace { get; set; } = "";

    /// <summary>pid namespace inode</summary>
    [OsqueryColumn("pid_namespace")]
    public string PidNamespace { get; set; } = "";

    /// <summary>user namespace inode</summary>
    [OsqueryColumn("user_namespace")]
    public string UserNamespace { get; set; } = "";

    /// <summary>uts namespace inode</summary>
    [OsqueryColumn("uts_namespace")]
    public string UtsNamespace { get; set; } = "";

}
