// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A key/value table of environment variables for each process.
/// </summary>
[OsqueryTable("process_envs")]
public class ProcessEnv
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>Environment variable name</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Environment variable value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";
}
