// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Enumerate open handles for a specified process.
/// </summary>
[OsqueryTable("process_open_handles")]
public class ProcessOpenHandle
{
    /// <summary>The process identifier that owns the handle.</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>The handle value</summary>
    [OsqueryColumn("value")]
    public long Value { get; set; }

    /// <summary>The type of object referenced by the handle.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>The access permissions of the object referenced by the handle.</summary>
    [OsqueryColumn("access")]
    public string Access { get; set; } = "";

    /// <summary>The value of the object referenced by the handle.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Object handle attributes.</summary>
    [OsqueryColumn("attributes")]
    public string Attributes { get; set; } = "";

    /// <summary>Handle Count.</summary>
    [OsqueryColumn("count")]
    public long Count { get; set; }

    /// <summary>Raw Pointer/Reference Count. Meaning varies, consult Windows docs.</summary>
    [OsqueryColumn("raw_pointer_count")]
    public long RawPointerCount { get; set; }

    /// <summary>Error Stage.</summary>
    [OsqueryColumn("error_stage")]
    public string ErrorStage { get; set; } = "";

    /// <summary>Error Code.</summary>
    [OsqueryColumn("error_code")]
    public long ErrorCode { get; set; }
}
