// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Processes which have open network sockets on the system.
/// </summary>
[OsqueryTable("process_open_sockets")]
public class ProcessOpenSocket
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>Socket file descriptor number</summary>
    [OsqueryColumn("fd")]
    public long Fd { get; set; }

    /// <summary>Socket handle or inode number</summary>
    [OsqueryColumn("socket")]
    public long Socket { get; set; }

    /// <summary>Network protocol (IPv4, IPv6)</summary>
    [OsqueryColumn("family")]
    public int Family { get; set; }

    /// <summary>Transport protocol (TCP/UDP)</summary>
    [OsqueryColumn("protocol")]
    public int Protocol { get; set; }

    /// <summary>Socket local address</summary>
    [OsqueryColumn("local_address")]
    public string LocalAddress { get; set; } = "";

    /// <summary>Socket remote address</summary>
    [OsqueryColumn("remote_address")]
    public string RemoteAddress { get; set; } = "";

    /// <summary>Socket local port</summary>
    [OsqueryColumn("local_port")]
    public int LocalPort { get; set; }

    /// <summary>Socket remote port</summary>
    [OsqueryColumn("remote_port")]
    public int RemotePort { get; set; }

    /// <summary>For UNIX sockets (family=AF_UNIX), the domain path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>TCP socket state</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>The inode number of the network namespace</summary>
    [OsqueryColumn("net_namespace")]
    public string NetNamespace { get; set; } = "";
}
