// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track time/action process executions.
/// </summary>
[OsqueryTable("process_events")]
public class ProcessEvent
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Path of executed file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>File mode permissions</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Command line arguments (argv)</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>Actual size (bytes) of command line arguments</summary>
    [OsqueryColumn("cmdline_size")]
    public long CmdlineSize { get; set; }

    /// <summary>Environment variables delimited by spaces</summary>
    [OsqueryColumn("env")]
    public string Env { get; set; } = "";

    /// <summary>Number of environment variables</summary>
    [OsqueryColumn("env_count")]
    public long EnvCount { get; set; }

    /// <summary>Actual size (bytes) of environment list</summary>
    [OsqueryColumn("env_size")]
    public long EnvSize { get; set; }

    /// <summary>The process current working directory</summary>
    [OsqueryColumn("cwd")]
    public string Cwd { get; set; } = "";

    /// <summary>Audit User ID at process start</summary>
    [OsqueryColumn("auid")]
    public long Auid { get; set; }

    /// <summary>User ID at process start</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Effective user ID at process start</summary>
    [OsqueryColumn("euid")]
    public long Euid { get; set; }

    /// <summary>Group ID at process start</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Effective group ID at process start</summary>
    [OsqueryColumn("egid")]
    public long Egid { get; set; }

    /// <summary>File owner user ID</summary>
    [OsqueryColumn("owner_uid")]
    public long OwnerUid { get; set; }

    /// <summary>File owner group ID</summary>
    [OsqueryColumn("owner_gid")]
    public long OwnerGid { get; set; }

    /// <summary>File last access in UNIX time</summary>
    [OsqueryColumn("atime")]
    public long Atime { get; set; }

    /// <summary>File modification in UNIX time</summary>
    [OsqueryColumn("mtime")]
    public long Mtime { get; set; }

    /// <summary>File last metadata change in UNIX time</summary>
    [OsqueryColumn("ctime")]
    public long Ctime { get; set; }

    /// <summary>File creation in UNIX time</summary>
    [OsqueryColumn("btime")]
    public long Btime { get; set; }

    /// <summary>List of structures that overflowed</summary>
    [OsqueryColumn("overflows")]
    public string Overflows { get; set; } = "";

    /// <summary>Process parent's PID, or -1 if cannot be determined.</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Time of execution in system uptime</summary>
    [OsqueryColumn("uptime")]
    public long Uptime { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

    /// <summary>OpenBSM Attribute: Status of the process</summary>
    [OsqueryColumn("status")]
    public long Status { get; set; }

    /// <summary>Filesystem user ID at process start</summary>
    [OsqueryColumn("fsuid")]
    public long Fsuid { get; set; }

    /// <summary>Saved user ID at process start</summary>
    [OsqueryColumn("suid")]
    public long Suid { get; set; }

    /// <summary>Filesystem group ID at process start</summary>
    [OsqueryColumn("fsgid")]
    public long Fsgid { get; set; }

    /// <summary>Saved group ID at process start</summary>
    [OsqueryColumn("sgid")]
    public long Sgid { get; set; }

    /// <summary>Syscall name: fork, vfork, clone, execve, execveat</summary>
    [OsqueryColumn("syscall")]
    public string Syscall { get; set; } = "";

}
