// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Pipes and partner processes for each process.
/// </summary>
[OsqueryTable("process_open_pipes")]
public class ProcessOpenPipe
{
    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>File descriptor</summary>
    [OsqueryColumn("fd")]
    public long Fd { get; set; }

    /// <summary>Pipe open mode (r/w)</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Pipe inode number</summary>
    [OsqueryColumn("inode")]
    public long Inode { get; set; }

    /// <summary>Pipe Type: named vs unnamed/anonymous</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Process ID of partner process sharing a particular pipe</summary>
    [OsqueryColumn("partner_pid")]
    public long PartnerPid { get; set; }

    /// <summary>File descriptor of shared pipe at partner's end</summary>
    [OsqueryColumn("partner_fd")]
    public long PartnerFd { get; set; }

    /// <summary>Mode of shared pipe at partner's end</summary>
    [OsqueryColumn("partner_mode")]
    public string PartnerMode { get; set; } = "";
}
