// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A File Integrity Monitor implementation using the audit service.
/// </summary>
[OsqueryTable("process_file_events")]
public class ProcessFileEvent
{
    /// <summary>Operation type</summary>
    [OsqueryColumn("operation")]
    public string Operation { get; set; } = "";

    /// <summary>Process ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Parent process ID</summary>
    [OsqueryColumn("ppid")]
    public long Ppid { get; set; }

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>The executable path</summary>
    [OsqueryColumn("executable")]
    public string Executable { get; set; } = "";

    /// <summary>True if this is a partial event (i.e.: this process existed before we started osquery)</summary>
    [OsqueryColumn("partial")]
    public string Partial { get; set; } = "";

    /// <summary>The current working directory of the process</summary>
    [OsqueryColumn("cwd")]
    public string Cwd { get; set; } = "";

    /// <summary>The path associated with the event</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The canonical path associated with the event</summary>
    [OsqueryColumn("dest_path")]
    public string DestPath { get; set; } = "";

    /// <summary>The uid of the process performing the action</summary>
    [OsqueryColumn("uid")]
    public string Uid { get; set; } = "";

    /// <summary>The gid of the process performing the action</summary>
    [OsqueryColumn("gid")]
    public string Gid { get; set; } = "";

    /// <summary>Audit user ID of the process using the file</summary>
    [OsqueryColumn("auid")]
    public string Auid { get; set; } = "";

    /// <summary>Effective user ID of the process using the file</summary>
    [OsqueryColumn("euid")]
    public string Euid { get; set; } = "";

    /// <summary>Effective group ID of the process using the file</summary>
    [OsqueryColumn("egid")]
    public string Egid { get; set; } = "";

    /// <summary>Filesystem user ID of the process using the file</summary>
    [OsqueryColumn("fsuid")]
    public string Fsuid { get; set; } = "";

    /// <summary>Filesystem group ID of the process using the file</summary>
    [OsqueryColumn("fsgid")]
    public string Fsgid { get; set; } = "";

    /// <summary>Saved user ID of the process using the file</summary>
    [OsqueryColumn("suid")]
    public string Suid { get; set; } = "";

    /// <summary>Saved group ID of the process using the file</summary>
    [OsqueryColumn("sgid")]
    public string Sgid { get; set; } = "";

    /// <summary>Time of execution in system uptime</summary>
    [OsqueryColumn("uptime")]
    public long Uptime { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";
}
