// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// All running processes on the host system.
/// </summary>
[OsqueryTable("processes")]
public class Process
{
    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>The process path or shorthand argv[0]</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Path to executed binary</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Complete argv</summary>
    [OsqueryColumn("cmdline")]
    public string Cmdline { get; set; } = "";

    /// <summary>Process state</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Process current working directory</summary>
    [OsqueryColumn("cwd")]
    public string Cwd { get; set; } = "";

    /// <summary>Process virtual root directory</summary>
    [OsqueryColumn("root")]
    public string Root { get; set; } = "";

    /// <summary>Unsigned user ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Unsigned group ID</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>Unsigned effective user ID</summary>
    [OsqueryColumn("euid")]
    public long Euid { get; set; }

    /// <summary>Unsigned effective group ID</summary>
    [OsqueryColumn("egid")]
    public long Egid { get; set; }

    /// <summary>Unsigned saved user ID</summary>
    [OsqueryColumn("suid")]
    public long Suid { get; set; }

    /// <summary>Unsigned saved group ID</summary>
    [OsqueryColumn("sgid")]
    public long Sgid { get; set; }

    /// <summary>The process path exists yes=1, no=0, unknown=-1</summary>
    [OsqueryColumn("on_disk")]
    public int OnDisk { get; set; }

    /// <summary>Bytes of unpageable memory used by process</summary>
    [OsqueryColumn("wired_size")]
    public long WiredSize { get; set; }

    /// <summary>Bytes of private memory used by process</summary>
    [OsqueryColumn("resident_size")]
    public long ResidentSize { get; set; }

    /// <summary>Total virtual memory size (Linux, Windows) or 'footprint' (macOS)</summary>
    [OsqueryColumn("total_size")]
    public long TotalSize { get; set; }

    /// <summary>CPU time in milliseconds spent in user space</summary>
    [OsqueryColumn("user_time")]
    public long UserTime { get; set; }

    /// <summary>CPU time in milliseconds spent in kernel space</summary>
    [OsqueryColumn("system_time")]
    public long SystemTime { get; set; }

    /// <summary>Bytes read from disk</summary>
    [OsqueryColumn("disk_bytes_read")]
    public long DiskBytesRead { get; set; }

    /// <summary>Bytes written to disk</summary>
    [OsqueryColumn("disk_bytes_written")]
    public long DiskBytesWritten { get; set; }

    /// <summary>Process start time in seconds since Epoch, in case of error -1</summary>
    [OsqueryColumn("start_time")]
    public long StartTime { get; set; }

    /// <summary>Process parent's PID</summary>
    [OsqueryColumn("parent")]
    public long Parent { get; set; }

    /// <summary>Process group</summary>
    [OsqueryColumn("pgroup")]
    public long Pgroup { get; set; }

    /// <summary>Number of threads used by process</summary>
    [OsqueryColumn("threads")]
    public int Threads { get; set; }

    /// <summary>Process nice level (-20 to 20, default 0)</summary>
    [OsqueryColumn("nice")]
    public int Nice { get; set; }

    /// <summary>Process uses elevated token yes=1, no=0</summary>
    [OsqueryColumn("elevated_token")]
    public int ElevatedToken { get; set; }

    /// <summary>Process is secure (IUM) yes=1, no=0</summary>
    [OsqueryColumn("secure_process")]
    public int SecureProcess { get; set; }

    /// <summary>The protection type of the process</summary>
    [OsqueryColumn("protection_type")]
    public string ProtectionType { get; set; } = "";

    /// <summary>Process is virtual (e.g. System, Registry, vmmem) yes=1, no=0</summary>
    [OsqueryColumn("virtual_process")]
    public int VirtualProcess { get; set; }

    /// <summary>Elapsed time in seconds this process has been running.</summary>
    [OsqueryColumn("elapsed_time")]
    public long ElapsedTime { get; set; }

    /// <summary>Total number of handles that the process has open. This number is the sum of the handles currently opened by each thread in the process.</summary>
    [OsqueryColumn("handle_count")]
    public long HandleCount { get; set; }

    /// <summary>Returns elapsed time that all of the threads of this process used the processor to execute instructions in 100 nanoseconds ticks.</summary>
    [OsqueryColumn("percent_processor_time")]
    public long PercentProcessorTime { get; set; }

    /// <summary>A 64bit pid that is never reused. Returns -1 if we couldn't gather them from the system.</summary>
    [OsqueryColumn("upid")]
    public long Upid { get; set; }

    /// <summary>The 64bit parent pid that is never reused. Returns -1 if we couldn't gather them from the system.</summary>
    [OsqueryColumn("uppid")]
    public long Uppid { get; set; }

    /// <summary>Indicates the specific processor designed for installation.</summary>
    [OsqueryColumn("cpu_type")]
    public int CpuType { get; set; }

    /// <summary>Indicates the specific processor on which an entry may be used.</summary>
    [OsqueryColumn("cpu_subtype")]
    public int CpuSubtype { get; set; }

    /// <summary>Indicates whether the process is running under the Rosetta Translation Environment, yes=1, no=0, error=-1.</summary>
    [OsqueryColumn("translated")]
    public int Translated { get; set; }

    /// <summary>The full hierarchical path of the process's control group</summary>
    [OsqueryColumn("cgroup_path")]
    public string CgroupPath { get; set; } = "";

}
