// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Represents products as they are installed by Windows Installer. A product generally correlates to one installation package on Windows. Some fields may be blank as Windows installation details are left to the discretion of the product author.
/// </summary>
[OsqueryTable("programs")]
public class Program
{
    /// <summary>Commonly used product name.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Product version information.</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>The installation location directory of the product.</summary>
    [OsqueryColumn("install_location")]
    public string InstallLocation { get; set; } = "";

    /// <summary>The installation source of the product.</summary>
    [OsqueryColumn("install_source")]
    public string InstallSource { get; set; } = "";

    /// <summary>The language of the product.</summary>
    [OsqueryColumn("language")]
    public string Language { get; set; } = "";

    /// <summary>Name of the product supplier.</summary>
    [OsqueryColumn("publisher")]
    public string Publisher { get; set; } = "";

    /// <summary>Path and filename of the uninstaller.</summary>
    [OsqueryColumn("uninstall_string")]
    public string UninstallString { get; set; } = "";

    /// <summary>Date that this product was installed on the system. </summary>
    [OsqueryColumn("install_date")]
    public string InstallDate { get; set; } = "";

    /// <summary>Product identification such as a serial number on software, or a die number on a hardware chip.</summary>
    [OsqueryColumn("identifying_number")]
    public string IdentifyingNumber { get; set; } = "";

    /// <summary>A combination of PackageName and PublisherHash that is used to uniquely identify applications across versions and architectures.</summary>
    [OsqueryColumn("package_family_name")]
    public string PackageFamilyName { get; set; } = "";

    /// <summary>Specific to MSI applications, a GUID used to identify a product suite across multiple versions.</summary>
    [OsqueryColumn("upgrade_code")]
    public string UpgradeCode { get; set; } = "";
}
