// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Python packages installed in a system. NOTE: when querying on windows, even without a users cross join, all user installed python packages will be returned. This special behavior is to not break original functionality.
/// </summary>
[OsqueryTable("python_packages")]
public class PythonPackage
{
    /// <summary>Package display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The local user that owns the python package</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Package-supplied version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package-supplied summary</summary>
    [OsqueryColumn("summary")]
    public string Summary { get; set; } = "";

    /// <summary>Optional package author</summary>
    [OsqueryColumn("author")]
    public string Author { get; set; } = "";

    /// <summary>License under which package is launched</summary>
    [OsqueryColumn("license")]
    public string License { get; set; } = "";

    /// <summary>Path at which this module resides</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Directory where Python modules are located</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
