// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Files and thumbnails within macOS's Quicklook Cache.
/// </summary>
[OsqueryTable("quicklook_cache")]
public class QuicklookCache
{
    /// <summary>Path of file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Quicklook file rowid key</summary>
    [OsqueryColumn("rowid")]
    public int Rowid { get; set; }

    /// <summary>Quicklook file fs_id key</summary>
    [OsqueryColumn("fs_id")]
    public string FsId { get; set; } = "";

    /// <summary>Parsed volume ID from fs_id</summary>
    [OsqueryColumn("volume_id")]
    public int VolumeId { get; set; }

    /// <summary>Parsed file ID (inode) from fs_id</summary>
    [OsqueryColumn("inode")]
    public int Inode { get; set; }

    /// <summary>Parsed version date field</summary>
    [OsqueryColumn("mtime")]
    public int Mtime { get; set; }

    /// <summary>Parsed version size field</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Parsed version 'gen' field</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Apple date format for last thumbnail cache hit</summary>
    [OsqueryColumn("last_hit_date")]
    public int LastHitDate { get; set; }

    /// <summary>Number of cache hits on thumbnail</summary>
    [OsqueryColumn("hit_count")]
    public string HitCount { get; set; } = "";

    /// <summary>Thumbnail icon mode</summary>
    [OsqueryColumn("icon_mode")]
    public long IconMode { get; set; }

    /// <summary>Path to cache data</summary>
    [OsqueryColumn("cache_path")]
    public string CachePath { get; set; } = "";

}
