// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Recently files (as displayed in Start Menu or File Explorer).
/// </summary>
[OsqueryTable("recent_files")]
public class RecentFile
{
    /// <summary>The local user ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>The name of the file</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>The full path of the file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Display type for the file</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Last modification time of the shortcut (usually corresponds to last opened time for the file)</summary>
    [OsqueryColumn("mtime")]
    public long Mtime { get; set; }

    /// <summary>Path to the shortcut where Windows stores the recent file data</summary>
    [OsqueryColumn("shortcut_path")]
    public string ShortcutPath { get; set; } = "";

}
