// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// The active route table for the host system.
/// </summary>
[OsqueryTable("routes")]
public class Route
{
    /// <summary>Destination IP address</summary>
    [OsqueryColumn("destination")]
    public string Destination { get; set; } = "";

    /// <summary>Netmask length</summary>
    [OsqueryColumn("netmask")]
    public int Netmask { get; set; }

    /// <summary>Route gateway</summary>
    [OsqueryColumn("gateway")]
    public string Gateway { get; set; } = "";

    /// <summary>Route source</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Flags to describe route</summary>
    [OsqueryColumn("flags")]
    public int Flags { get; set; }

    /// <summary>Route local interface</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>Maximum Transmission Unit for the route</summary>
    [OsqueryColumn("mtu")]
    public int Mtu { get; set; }

    /// <summary>Cost of route. Lowest is preferred</summary>
    [OsqueryColumn("metric")]
    public int Metric { get; set; }

    /// <summary>Type of route</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Max hops expected</summary>
    [OsqueryColumn("hopcount")]
    public int Hopcount { get; set; }

}
