// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Installed files from RPM packages that are currently installed on the system.
/// </summary>
[OsqueryTable("rpm_package_files")]
public class RpmPackageFile
{
    /// <summary>RPM package name</summary>
    [OsqueryColumn("package")]
    public string Package { get; set; } = "";

    /// <summary>File path within the package</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>File default username from info DB</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>File default groupname from info DB</summary>
    [OsqueryColumn("groupname")]
    public string Groupname { get; set; } = "";

    /// <summary>File permissions mode from info DB</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";

    /// <summary>Expected file size in bytes from RPM info DB</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>SHA256 file digest from RPM info DB</summary>
    [OsqueryColumn("sha256")]
    public string Sha256 { get; set; } = "";

}
