// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// RPM packages that are currently installed on the host system.
/// </summary>
[OsqueryTable("rpm_packages")]
public class RpmPackage
{
    /// <summary>RPM package name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Package version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Package release</summary>
    [OsqueryColumn("release")]
    public string Release { get; set; } = "";

    /// <summary>Source RPM package name (optional)</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Package size in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>SHA1 hash of the package contents</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>Architecture(s) supported</summary>
    [OsqueryColumn("arch")]
    public string Arch { get; set; } = "";

    /// <summary>Package epoch value</summary>
    [OsqueryColumn("epoch")]
    public int Epoch { get; set; }

    /// <summary>When the package was installed</summary>
    [OsqueryColumn("install_time")]
    public int InstallTime { get; set; }

    /// <summary>Package vendor</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Package group</summary>
    [OsqueryColumn("package_group")]
    public string PackageGroup { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>Mount namespace id</summary>
    [OsqueryColumn("mount_namespace_id")]
    public string MountNamespaceId { get; set; } = "";

}
