// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS applications currently running on the host system.
/// </summary>
[OsqueryTable("running_apps")]
public class RunningApp
{
    /// <summary>The pid of the application</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>The bundle identifier of the application</summary>
    [OsqueryColumn("bundle_identifier")]
    public string BundleIdentifier { get; set; } = "";

    /// <summary>(DEPRECATED)</summary>
    [OsqueryColumn("is_active")]
    public int IsActive { get; set; }
}
