// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Safari browser extension details for all users. This table requires Full Disk Access (FDA) permission.
/// </summary>
[OsqueryTable("safari_extensions")]
public class SafariExtension
{
    /// <summary>The local user that owns the extension</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Extension display name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Extension identifier</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Extension long version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Bundle SDK used to compile extension</summary>
    [OsqueryColumn("sdk")]
    public string Sdk { get; set; } = "";

    /// <summary>Optional extension description text</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Path to the Info.plist describing the extension</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The version of the build that identifies an iteration of the bundle</summary>
    [OsqueryColumn("bundle_version")]
    public string BundleVersion { get; set; } = "";

    /// <summary>A human-readable copyright notice for the bundle</summary>
    [OsqueryColumn("copyright")]
    public string Copyright { get; set; } = "";
}
