// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS application sandboxes container details.
/// </summary>
[OsqueryTable("sandboxes")]
public class Sandboxe
{
    /// <summary>UTI-format bundle or label ID</summary>
    [OsqueryColumn("label")]
    public string Label { get; set; } = "";

    /// <summary>Sandbox owner</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>Application sandboxings enabled on container</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>Sandbox-specific identifier</summary>
    [OsqueryColumn("build_id")]
    public string BuildId { get; set; } = "";

    /// <summary>Application bundle used by the sandbox</summary>
    [OsqueryColumn("bundle_path")]
    public string BundlePath { get; set; } = "";

    /// <summary>Path to sandbox container directory</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
