// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists all of the tasks in the Windows task scheduler.
/// </summary>
[OsqueryTable("scheduled_tasks")]
public class ScheduledTask
{
    /// <summary>Name of the scheduled task</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Actions executed by the scheduled task</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>Path to the executable to be run</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Whether or not the scheduled task is enabled</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>State of the scheduled task</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Whether or not the task is visible in the UI</summary>
    [OsqueryColumn("hidden")]
    public int Hidden { get; set; }

    /// <summary>Timestamp the task last ran</summary>
    [OsqueryColumn("last_run_time")]
    public long LastRunTime { get; set; }

    /// <summary>Timestamp the task is scheduled to run next</summary>
    [OsqueryColumn("next_run_time")]
    public long NextRunTime { get; set; }

    /// <summary>Exit status message of the last task run</summary>
    [OsqueryColumn("last_run_message")]
    public string LastRunMessage { get; set; } = "";

    /// <summary>Exit status code of the last task run</summary>
    [OsqueryColumn("last_run_code")]
    public string LastRunCode { get; set; } = "";

}
