// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Information on the security profile of a given system by listing the system Account and Audit Policies. This table mimics the exported securitypolicy output from the secedit tool.
/// </summary>
[OsqueryTable("security_profile_info")]
public class SecurityProfileInfo
{
    /// <summary>Determines the minimum number of days that a password must be used before the user can change it</summary>
    [OsqueryColumn("minimum_password_age")]
    public int MinimumPasswordAge { get; set; }

    /// <summary>Determines the maximum number of days that a password can be used before the client requires the user to change it</summary>
    [OsqueryColumn("maximum_password_age")]
    public int MaximumPasswordAge { get; set; }

    /// <summary>Determines the least number of characters that can make up a password for a user account</summary>
    [OsqueryColumn("minimum_password_length")]
    public int MinimumPasswordLength { get; set; }

    /// <summary>Determines whether passwords must meet a series of strong-password guidelines</summary>
    [OsqueryColumn("password_complexity")]
    public int PasswordComplexity { get; set; }

    /// <summary>Number of unique new passwords that must be associated with a user account before an old password can be reused</summary>
    [OsqueryColumn("password_history_size")]
    public int PasswordHistorySize { get; set; }

    /// <summary>Number of failed logon attempts after which a user account MUST be locked out</summary>
    [OsqueryColumn("lockout_bad_count")]
    public int LockoutBadCount { get; set; }

    /// <summary>Determines if logon session is required to change the password</summary>
    [OsqueryColumn("logon_to_change_password")]
    public int LogonToChangePassword { get; set; }

    /// <summary>Determines whether SMB client sessions with the SMB server will be forcibly disconnected when the client's logon hours expire</summary>
    [OsqueryColumn("force_logoff_when_expire")]
    public int ForceLogoffWhenExpire { get; set; }

    /// <summary>Determines the name of the Administrator account on the local computer</summary>
    [OsqueryColumn("new_administrator_name")]
    public string NewAdministratorName { get; set; } = "";

    /// <summary>Determines the name of the Guest account on the local computer</summary>
    [OsqueryColumn("new_guest_name")]
    public string NewGuestName { get; set; } = "";

    /// <summary>Determines whether passwords MUST be stored by using reversible encryption</summary>
    [OsqueryColumn("clear_text_password")]
    public int ClearTextPassword { get; set; }

    /// <summary>Determines if an anonymous user is allowed to query the local LSA policy</summary>
    [OsqueryColumn("lsa_anonymous_name_lookup")]
    public int LsaAnonymousNameLookup { get; set; }

    /// <summary>Determines whether the Administrator account on the local computer is enabled</summary>
    [OsqueryColumn("enable_admin_account")]
    public int EnableAdminAccount { get; set; }

    /// <summary>Determines whether the Guest account on the local computer is enabled</summary>
    [OsqueryColumn("enable_guest_account")]
    public int EnableGuestAccount { get; set; }

    /// <summary>Determines whether the operating system MUST audit System Change, System Startup, System Shutdown, Authentication Component Load, and Loss or Excess of Security events</summary>
    [OsqueryColumn("audit_system_events")]
    public int AuditSystemEvents { get; set; }

    /// <summary>Determines whether the operating system MUST audit each instance of a user attempt to log on or log off this computer</summary>
    [OsqueryColumn("audit_logon_events")]
    public int AuditLogonEvents { get; set; }

    /// <summary>Determines whether the operating system MUST audit each instance of user attempts to access a non-Active Directory object that has its own SACL specified</summary>
    [OsqueryColumn("audit_object_access")]
    public int AuditObjectAccess { get; set; }

    /// <summary>Determines whether the operating system MUST audit each instance of user attempts to exercise a user right</summary>
    [OsqueryColumn("audit_privilege_use")]
    public int AuditPrivilegeUse { get; set; }

    /// <summary>Determines whether the operating system MUST audit each instance of user attempts to change user rights assignment policy, audit policy, account policy, or trust policy</summary>
    [OsqueryColumn("audit_policy_change")]
    public int AuditPolicyChange { get; set; }

    /// <summary>Determines whether the operating system MUST audit each event of account management on a computer</summary>
    [OsqueryColumn("audit_account_manage")]
    public int AuditAccountManage { get; set; }

    /// <summary>Determines whether the operating system MUST audit process-related events</summary>
    [OsqueryColumn("audit_process_tracking")]
    public int AuditProcessTracking { get; set; }

    /// <summary>Determines whether the operating system MUST audit each instance of user attempts to access an Active Directory object that has its own system access control list (SACL) specified</summary>
    [OsqueryColumn("audit_ds_access")]
    public int AuditDsAccess { get; set; }

    /// <summary>Determines whether the operating system MUST audit each time this computer validates the credentials of an account</summary>
    [OsqueryColumn("audit_account_logon")]
    public int AuditAccountLogon { get; set; }

}
