// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// X.509 certificates from UEFI Secure Boot signature databases (db and dbx EFI variables). Useful for monitoring CA expiry and adoption of updated certificates (e.g. Microsoft UEFI CA 2023).
/// </summary>
[OsqueryTable("secureboot_certificates")]
public class SecurebootCertificate
{
    /// <summary>Certificate CommonName</summary>
    [OsqueryColumn("common_name")]
    public string CommonName { get; set; } = "";

    /// <summary>Certificate subject distinguished name</summary>
    [OsqueryColumn("subject")]
    public string Subject { get; set; } = "";

    /// <summary>Certificate issuer distinguished name</summary>
    [OsqueryColumn("issuer")]
    public string Issuer { get; set; } = "";

    /// <summary>Lower bound of valid date</summary>
    [OsqueryColumn("not_valid_before")]
    public string NotValidBefore { get; set; } = "";

    /// <summary>Certificate expiration date</summary>
    [OsqueryColumn("not_valid_after")]
    public string NotValidAfter { get; set; } = "";

    /// <summary>SHA1 hash of the raw certificate contents</summary>
    [OsqueryColumn("sha1")]
    public string Sha1 { get; set; } = "";

    /// <summary>Certificate serial number</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>1 if the certificate is in the dbx revocation list, 0 if it is in the db allowlist</summary>
    [OsqueryColumn("revoked")]
    public int Revoked { get; set; }

    /// <summary>Path to the EFI variable file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>1 if the certificate is a CA, 0 otherwise</summary>
    [OsqueryColumn("is_ca")]
    public int IsCa { get; set; }

    /// <summary>1 if the certificate is self-signed, 0 otherwise</summary>
    [OsqueryColumn("self_signed")]
    public int SelfSigned { get; set; }

    /// <summary>Certificate key usage extension string</summary>
    [OsqueryColumn("key_usage")]
    public string KeyUsage { get; set; } = "";

    /// <summary>Authority Key Identifier (AKI)</summary>
    [OsqueryColumn("authority_key_id")]
    public string AuthorityKeyId { get; set; } = "";

    /// <summary>Subject Key Identifier (SKI)</summary>
    [OsqueryColumn("subject_key_id")]
    public string SubjectKeyId { get; set; } = "";

    /// <summary>Algorithm used to sign the certificate</summary>
    [OsqueryColumn("signing_algorithm")]
    public string SigningAlgorithm { get; set; } = "";

    /// <summary>Public key algorithm</summary>
    [OsqueryColumn("key_algorithm")]
    public string KeyAlgorithm { get; set; } = "";

    /// <summary>Public key size in bits</summary>
    [OsqueryColumn("key_strength")]
    public string KeyStrength { get; set; } = "";

}
