// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Secure Boot UEFI Settings.
/// </summary>
[OsqueryTable("secureboot")]
public class Secureboot
{
    /// <summary>Whether secure boot is enabled</summary>
    [OsqueryColumn("secure_boot")]
    public int SecureBoot { get; set; }

    /// <summary>(Intel) Secure mode: 0 disabled, 1 full security, 2 medium security</summary>
    [OsqueryColumn("secure_mode")]
    public int SecureMode { get; set; }

    /// <summary>(Apple Silicon) Human-readable description: 'Full Security', 'Reduced Security', or 'Permissive Security'</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>(Apple Silicon) Allow user management of kernel extensions from identified developers (1 if allowed)</summary>
    [OsqueryColumn("kernel_extensions")]
    public int KernelExtensions { get; set; }

    /// <summary>(Apple Silicon) Allow remote (MDM) management of kernel extensions and automatic software updates (1 if allowed)</summary>
    [OsqueryColumn("mdm_operations")]
    public int MdmOperations { get; set; }

    /// <summary>Whether setup mode is enabled</summary>
    [OsqueryColumn("setup_mode")]
    public int SetupMode { get; set; }

}
