// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track active SELinux settings.
/// </summary>
[OsqueryTable("selinux_settings")]
public class SelinuxSetting
{
    /// <summary>Where the key is located inside the SELinuxFS mount point.</summary>
    [OsqueryColumn("scope")]
    public string Scope { get; set; } = "";

    /// <summary>Key or class name.</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Active value.</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

}
