// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists all installed Windows services and their relevant data.
/// </summary>
[OsqueryTable("services")]
public class Service
{
    /// <summary>Service name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Service Type: OWN_PROCESS, SHARE_PROCESS and maybe Interactive (can interact with the desktop)</summary>
    [OsqueryColumn("service_type")]
    public string ServiceType { get; set; } = "";

    /// <summary>Service Display name</summary>
    [OsqueryColumn("display_name")]
    public string DisplayName { get; set; } = "";

    /// <summary>Service Current status: STOPPED, START_PENDING, STOP_PENDING, RUNNING, CONTINUE_PENDING, PAUSE_PENDING, PAUSED</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>the Process ID of the service</summary>
    [OsqueryColumn("pid")]
    public int Pid { get; set; }

    /// <summary>Service start type: BOOT_START, SYSTEM_START, AUTO_START, DEMAND_START, DISABLED</summary>
    [OsqueryColumn("start_type")]
    public string StartType { get; set; } = "";

    /// <summary>The error code that the service uses to report an error that occurs when it is starting or stopping</summary>
    [OsqueryColumn("win32_exit_code")]
    public int Win32ExitCode { get; set; }

    /// <summary>The service-specific error code that the service returns when an error occurs while the service is starting or stopping</summary>
    [OsqueryColumn("service_exit_code")]
    public int ServiceExitCode { get; set; }

    /// <summary>Path to Service Executable</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Path to ServiceDll</summary>
    [OsqueryColumn("module_path")]
    public string ModulePath { get; set; } = "";

    /// <summary>Service Description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>The name of the account that the service process will be logged on as when it runs. This name can be of the form Domain\UserName. If the account belongs to the built-in domain, the name can be of the form .\UserName.</summary>
    [OsqueryColumn("user_account")]
    public string UserAccount { get; set; } = "";

}
