// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Local system users encrypted passwords and related information. Please note, that you usually need superuser rights to access `/etc/shadow`.
/// </summary>
[OsqueryTable("shadow")]
public class Shadow
{
    /// <summary>Password status</summary>
    [OsqueryColumn("password_status")]
    public string PasswordStatus { get; set; } = "";

    /// <summary>Password hashing algorithm</summary>
    [OsqueryColumn("hash_alg")]
    public string HashAlg { get; set; } = "";

    /// <summary>Date of last password change (starting from UNIX epoch date)</summary>
    [OsqueryColumn("last_change")]
    public long LastChange { get; set; }

    /// <summary>Minimal number of days between password changes</summary>
    [OsqueryColumn("min")]
    public long Min { get; set; }

    /// <summary>Maximum number of days between password changes</summary>
    [OsqueryColumn("max")]
    public long Max { get; set; }

    /// <summary>Number of days before password expires to warn user about it</summary>
    [OsqueryColumn("warning")]
    public long Warning { get; set; }

    /// <summary>Number of days after password expires until account is blocked</summary>
    [OsqueryColumn("inactive")]
    public long Inactive { get; set; }

    /// <summary>Number of days since UNIX epoch date until account is disabled</summary>
    [OsqueryColumn("expire")]
    public long Expire { get; set; }

    /// <summary>Reserved</summary>
    [OsqueryColumn("flag")]
    public long Flag { get; set; }

    /// <summary>Username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

}
