// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Displays shared resources on a computer system running Windows. This may be a disk drive, printer, interprocess communication, or other sharable device.
/// </summary>
[OsqueryTable("shared_resources")]
public class SharedResource
{
    /// <summary>A textual description of the object</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Indicates when the object was installed. Lack of a value does not indicate that the object is not installed.</summary>
    [OsqueryColumn("install_date")]
    public string InstallDate { get; set; } = "";

    /// <summary>String that indicates the current status of the object.</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>Number of concurrent users for this resource has been limited. If True, the value in the MaximumAllowed property is ignored.</summary>
    [OsqueryColumn("allow_maximum")]
    public int AllowMaximum { get; set; }

    /// <summary>Limit on the maximum number of users allowed to use this resource concurrently. The value is only valid if the AllowMaximum property is set to FALSE.</summary>
    [OsqueryColumn("maximum_allowed")]
    public long MaximumAllowed { get; set; }

    /// <summary>Alias given to a path set up as a share on a computer system running Windows.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Local path of the Windows share.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Type of resource being shared. Types include: disk drives, print queues, interprocess communications (IPC), and general devices.</summary>
    [OsqueryColumn("type")]
    public long Type { get; set; }

    /// <summary>Human readable value for the 'type' column</summary>
    [OsqueryColumn("type_name")]
    public string TypeName { get; set; } = "";
}
