// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Folders available to others via SMB or AFP.
/// </summary>
[OsqueryTable("shared_folders")]
public class SharedFolder
{
    /// <summary>The shared name of the folder as it appears to other users</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Absolute path of shared folder on the local system</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

}
