// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS Sharing preferences.
/// </summary>
[OsqueryTable("sharing_preferences")]
public class SharingPreference
{
    /// <summary>1 If screen sharing is enabled else 0</summary>
    [OsqueryColumn("screen_sharing")]
    public int ScreenSharing { get; set; }

    /// <summary>1 If file sharing is enabled else 0</summary>
    [OsqueryColumn("file_sharing")]
    public int FileSharing { get; set; }

    /// <summary>1 If printer sharing is enabled else 0</summary>
    [OsqueryColumn("printer_sharing")]
    public int PrinterSharing { get; set; }

    /// <summary>1 If remote login is enabled else 0</summary>
    [OsqueryColumn("remote_login")]
    public int RemoteLogin { get; set; }

    /// <summary>1 If remote management is enabled else 0</summary>
    [OsqueryColumn("remote_management")]
    public int RemoteManagement { get; set; }

    /// <summary>1 If remote apple events are enabled else 0</summary>
    [OsqueryColumn("remote_apple_events")]
    public int RemoteAppleEvents { get; set; }

    /// <summary>1 If internet sharing is enabled else 0</summary>
    [OsqueryColumn("internet_sharing")]
    public int InternetSharing { get; set; }

    /// <summary>1 If bluetooth sharing is enabled for any user else 0</summary>
    [OsqueryColumn("bluetooth_sharing")]
    public int BluetoothSharing { get; set; }

    /// <summary>1 If CD or DVD sharing is enabled else 0</summary>
    [OsqueryColumn("disc_sharing")]
    public int DiscSharing { get; set; }

    /// <summary>1 If content caching is enabled else 0</summary>
    [OsqueryColumn("content_caching")]
    public int ContentCaching { get; set; }
}
