// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// OS shared memory regions.
/// </summary>
[OsqueryTable("shared_memory")]
public class SharedMemory
{
    /// <summary>Shared memory segment ID</summary>
    [OsqueryColumn("shmid")]
    public int Shmid { get; set; }

    /// <summary>User ID of owning process</summary>
    [OsqueryColumn("owner_uid")]
    public long OwnerUid { get; set; }

    /// <summary>User ID of creator process</summary>
    [OsqueryColumn("creator_uid")]
    public long CreatorUid { get; set; }

    /// <summary>Process ID to last use the segment</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Process ID that created the segment</summary>
    [OsqueryColumn("creator_pid")]
    public long CreatorPid { get; set; }

    /// <summary>Attached time</summary>
    [OsqueryColumn("atime")]
    public long Atime { get; set; }

    /// <summary>Detached time</summary>
    [OsqueryColumn("dtime")]
    public long Dtime { get; set; }

    /// <summary>Changed time</summary>
    [OsqueryColumn("ctime")]
    public long Ctime { get; set; }

    /// <summary>Memory segment permissions</summary>
    [OsqueryColumn("permissions")]
    public string Permissions { get; set; } = "";

    /// <summary>Size in bytes</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>Number of attached processes</summary>
    [OsqueryColumn("attached")]
    public int Attached { get; set; }

    /// <summary>Destination/attach status</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>1 if segment is locked else 0</summary>
    [OsqueryColumn("locked")]
    public int Locked { get; set; }
}
