// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Shows directories accessed via Windows Explorer.
/// </summary>
[OsqueryTable("shellbags")]
public class Shellbag
{
    /// <summary>User SID</summary>
    [OsqueryColumn("sid")]
    public string Sid { get; set; } = "";

    /// <summary>Shellbags source Registry file</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Directory name.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Directory Modified time.</summary>
    [OsqueryColumn("modified_time")]
    public long ModifiedTime { get; set; }

    /// <summary>Directory Created time.</summary>
    [OsqueryColumn("created_time")]
    public long CreatedTime { get; set; }

    /// <summary>Directory Accessed time.</summary>
    [OsqueryColumn("accessed_time")]
    public long AccessedTime { get; set; }

    /// <summary>Directory master file table entry.</summary>
    [OsqueryColumn("mft_entry")]
    public long MftEntry { get; set; }

    /// <summary>Directory master file table sequence.</summary>
    [OsqueryColumn("mft_sequence")]
    public int MftSequence { get; set; }
}
