// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A line-delimited (command) table of per-user .*_history data.
/// </summary>
[OsqueryTable("shell_history")]
public class ShellHistory
{
    /// <summary>Shell history owner</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Entry timestamp. It could be absent, default value is 0.</summary>
    [OsqueryColumn("time")]
    public int Time { get; set; }

    /// <summary>Unparsed date/line/command history line</summary>
    [OsqueryColumn("command")]
    public string Command { get; set; } = "";

    /// <summary>Path to the .*_history for this user</summary>
    [OsqueryColumn("history_file")]
    public string HistoryFile { get; set; } = "";

}
