// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Application Compatibility Cache, contains artifacts of execution.
/// </summary>
[OsqueryTable("shimcache")]
public class Shimcache
{
    /// <summary>Execution order.</summary>
    [OsqueryColumn("entry")]
    public int Entry { get; set; }

    /// <summary>This is the path to the executed file.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>File Modified time.</summary>
    [OsqueryColumn("modified_time")]
    public int ModifiedTime { get; set; }

    /// <summary>Boolean Execution flag, 1 for execution, 0 for no execution, -1 for missing (this flag does not exist on Windows 10 and higher).</summary>
    [OsqueryColumn("execution_flag")]
    public int ExecutionFlag { get; set; }

}
