// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// File (executable, bundle, installer, disk) code signing status.
/// </summary>
[OsqueryTable("signature")]
public class Signature
{
    /// <summary>Must provide a path or directory</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Set to 1 to also hash resources, or 0 otherwise. Default is 1</summary>
    [OsqueryColumn("hash_resources")]
    public int HashResources { get; set; }

    /// <summary>Set to 1 to also hash the executable, or 0 otherwise. Default is 1</summary>
    [OsqueryColumn("hash_executable")]
    public int HashExecutable { get; set; }

    /// <summary>If applicable, the arch of the signed code</summary>
    [OsqueryColumn("arch")]
    public string Arch { get; set; } = "";

    /// <summary>1 If the file is signed else 0</summary>
    [OsqueryColumn("signed")]
    public int Signed { get; set; }

    /// <summary>The signing identifier sealed into the signature</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Hash of the application Code Directory</summary>
    [OsqueryColumn("cdhash")]
    public string Cdhash { get; set; } = "";

    /// <summary>The team signing identifier sealed into the signature</summary>
    [OsqueryColumn("team_identifier")]
    public string TeamIdentifier { get; set; } = "";

    /// <summary>Certificate Common Name</summary>
    [OsqueryColumn("authority")]
    public string Authority { get; set; } = "";

    /// <summary>JSON representation of the code signing entitlements</summary>
    [OsqueryColumn("entitlements")]
    public string Entitlements { get; set; } = "";
}
