// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Apple's System Integrity Protection (rootless) status.
/// </summary>
[OsqueryTable("sip_config")]
public class SipConfig
{
    /// <summary>The System Integrity Protection config flag</summary>
    [OsqueryColumn("config_flag")]
    public string ConfigFlag { get; set; } = "";

    /// <summary>1 if this configuration is enabled, otherwise 0</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>1 if this configuration is enabled, otherwise 0</summary>
    [OsqueryColumn("enabled_nvram")]
    public int EnabledNvram { get; set; }

}
