// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// BIOS (DMI) structure common details and content.
/// </summary>
[OsqueryTable("smbios_tables")]
public class SmbiosTable
{
    /// <summary>Table entry number</summary>
    [OsqueryColumn("number")]
    public int Number { get; set; }

    /// <summary>Table entry type</summary>
    [OsqueryColumn("type")]
    public int Type { get; set; }

    /// <summary>Table entry description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Table entry handle</summary>
    [OsqueryColumn("handle")]
    public int Handle { get; set; }

    /// <summary>Header size in bytes</summary>
    [OsqueryColumn("header_size")]
    public int HeaderSize { get; set; }

    /// <summary>Table entry size in bytes</summary>
    [OsqueryColumn("size")]
    public int Size { get; set; }

    /// <summary>MD5 hash of table entry</summary>
    [OsqueryColumn("md5")]
    public string Md5 { get; set; } = "";

}
