// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Apple's system management controller keys.
/// </summary>
[OsqueryTable("smc_keys")]
public class SmcKey
{
    /// <summary>4-character key</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>SMC-reported type literal type</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Reported size of data in bytes</summary>
    [OsqueryColumn("size")]
    public int Size { get; set; }

    /// <summary>A type-encoded representation of the key value</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";

    /// <summary>1 if this key is normally hidden, otherwise 0</summary>
    [OsqueryColumn("hidden")]
    public int Hidden { get; set; }
}
