// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track network socket bind, connect, and accepts.
/// </summary>
[OsqueryTable("socket_events")]
public class SocketEvent
{
    /// <summary>The socket action (bind, connect, accept)</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Path of executed file</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The file description for the process socket</summary>
    [OsqueryColumn("fd")]
    public string Fd { get; set; } = "";

    /// <summary>Audit User ID</summary>
    [OsqueryColumn("auid")]
    public long Auid { get; set; }

    /// <summary>The Internet protocol family ID</summary>
    [OsqueryColumn("family")]
    public int Family { get; set; }

    /// <summary>The network protocol ID</summary>
    [OsqueryColumn("protocol")]
    public int Protocol { get; set; }

    /// <summary>Local address associated with socket</summary>
    [OsqueryColumn("local_address")]
    public string LocalAddress { get; set; } = "";

    /// <summary>Remote address associated with socket</summary>
    [OsqueryColumn("remote_address")]
    public string RemoteAddress { get; set; } = "";

    /// <summary>Local network protocol port number</summary>
    [OsqueryColumn("local_port")]
    public int LocalPort { get; set; }

    /// <summary>Remote network protocol port number</summary>
    [OsqueryColumn("remote_port")]
    public int RemotePort { get; set; }

    /// <summary>The local path (UNIX domain socket only)</summary>
    [OsqueryColumn("socket")]
    public string Socket { get; set; } = "";

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Time of execution in system uptime</summary>
    [OsqueryColumn("uptime")]
    public long Uptime { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

    /// <summary>Deprecated. Use the 'status' column instead</summary>
    [OsqueryColumn("success")]
    public int Success { get; set; }

    /// <summary>Either 'succeeded', 'failed', 'in_progress' (connect() on non-blocking socket) or 'no_client' (null accept() on non-blocking socket)</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

}
