// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A table of parsed ssh_configs.
/// </summary>
[OsqueryTable("ssh_configs")]
public class SshConfig
{
    /// <summary>The local owner of the ssh_config file</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>The host or match block</summary>
    [OsqueryColumn("block")]
    public string Block { get; set; } = "";

    /// <summary>The option and value</summary>
    [OsqueryColumn("option")]
    public string Option { get; set; } = "";

    /// <summary>Path to the ssh_config file</summary>
    [OsqueryColumn("ssh_config_file")]
    public string SshConfigFile { get; set; } = "";
}
