// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Applications and binaries set as startup items.
/// </summary>
[OsqueryTable("startup_items")]
public class StartupItem
{
    /// <summary>Name of startup item</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Path of startup item</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Arguments provided to startup executable</summary>
    [OsqueryColumn("args")]
    public string Args { get; set; } = "";

    /// <summary>Type of startup item. On macOS this can be app, agent (LaunchAgent), daemon (LaunchDaemon), login item, or user item.</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Directory containing startup item (on macOS, the subsystem providing it)</summary>
    [OsqueryColumn("source")]
    public string Source { get; set; } = "";

    /// <summary>Startup status. On Linux: enabled or disabled. On macOS: Combination of enabled, allowed, notified, and hidden. Apple does not seem to document these status values, but allowed seems to indicate whether it is enabled in System Settings.</summary>
    [OsqueryColumn("status")]
    public string Status { get; set; } = "";

    /// <summary>The user associated with the startup item</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

}
