// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// suid binaries in common locations.
/// </summary>
[OsqueryTable("suid_bin")]
public class SuidBin
{
    /// <summary>Binary path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Binary owner username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Binary owner group</summary>
    [OsqueryColumn("groupname")]
    public string Groupname { get; set; } = "";

    /// <summary>Binary permissions</summary>
    [OsqueryColumn("permissions")]
    public string Permissions { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
