// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// 
/// </summary>
[OsqueryTable("syslog_events")]
public class SyslogEvent
{
    /// <summary>Current unix epoch time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Time known to syslog</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>Hostname configured for syslog</summary>
    [OsqueryColumn("host")]
    public string Host { get; set; } = "";

    /// <summary>Syslog severity</summary>
    [OsqueryColumn("severity")]
    public int Severity { get; set; }

    /// <summary>Syslog facility</summary>
    [OsqueryColumn("facility")]
    public string Facility { get; set; } = "";

    /// <summary>The syslog tag</summary>
    [OsqueryColumn("tag")]
    public string Tag { get; set; } = "";

    /// <summary>The syslog message</summary>
    [OsqueryColumn("message")]
    public string Message { get; set; } = "";

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

}
