// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS (>= 10.15) system extension table.
/// </summary>
[OsqueryTable("system_extensions")]
public class SystemExtension
{
    /// <summary>Original path of system extension</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Extension unique id</summary>
    [OsqueryColumn("UUID")]
    public string UUID { get; set; } = "";

    /// <summary>System extension state</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Identifier name</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>System extension version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>System extension category</summary>
    [OsqueryColumn("category")]
    public string Category { get; set; } = "";

    /// <summary>System extension bundle path</summary>
    [OsqueryColumn("bundle_path")]
    public string BundlePath { get; set; } = "";

    /// <summary>Signing team ID</summary>
    [OsqueryColumn("team")]
    public string Team { get; set; } = "";

    /// <summary>1 if managed by MDM system extension payload configuration, 0 otherwise</summary>
    [OsqueryColumn("mdm_managed")]
    public int MdmManaged { get; set; }

}
