// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track systemd units.
/// </summary>
[OsqueryTable("systemd_units")]
public class SystemdUnit
{
    /// <summary>Unique unit identifier</summary>
    [OsqueryColumn("id")]
    public string Id { get; set; } = "";

    /// <summary>Unit description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Reflects whether the unit definition was properly loaded</summary>
    [OsqueryColumn("load_state")]
    public string LoadState { get; set; } = "";

    /// <summary>The high-level unit activation state, i.e. generalization of SUB</summary>
    [OsqueryColumn("active_state")]
    public string ActiveState { get; set; } = "";

    /// <summary>The low-level unit activation state, values depend on unit type</summary>
    [OsqueryColumn("sub_state")]
    public string SubState { get; set; } = "";

    /// <summary>Whether the unit file is enabled, e.g. `enabled`, `masked`, `disabled`, etc</summary>
    [OsqueryColumn("unit_file_state")]
    public string UnitFileState { get; set; } = "";

    /// <summary>The name of another unit that this unit follows in state</summary>
    [OsqueryColumn("following")]
    public string Following { get; set; } = "";

    /// <summary>The object path for this unit</summary>
    [OsqueryColumn("object_path")]
    public string ObjectPath { get; set; } = "";

    /// <summary>Next queued job id</summary>
    [OsqueryColumn("job_id")]
    public long JobId { get; set; }

    /// <summary>Job type</summary>
    [OsqueryColumn("job_type")]
    public string JobType { get; set; } = "";

    /// <summary>The object path for the job</summary>
    [OsqueryColumn("job_path")]
    public string JobPath { get; set; } = "";

    /// <summary>The unit file path this unit was read from, if there is any</summary>
    [OsqueryColumn("fragment_path")]
    public string FragmentPath { get; set; } = "";

    /// <summary>The configured user, if any</summary>
    [OsqueryColumn("user")]
    public string User { get; set; } = "";

    /// <summary>Path to the (possibly generated) unit configuration file</summary>
    [OsqueryColumn("source_path")]
    public string SourcePath { get; set; } = "";

}
