// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// sysctl names, values, and settings information.
/// </summary>
[OsqueryTable("system_controls")]
public class SystemControl
{
    /// <summary>Full sysctl MIB name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Control MIB</summary>
    [OsqueryColumn("oid")]
    public string Oid { get; set; } = "";

    /// <summary>Subsystem ID, control type</summary>
    [OsqueryColumn("subsystem")]
    public string Subsystem { get; set; } = "";

    /// <summary>Value of setting</summary>
    [OsqueryColumn("current_value")]
    public string CurrentValue { get; set; } = "";

    /// <summary>The MIB value set in /etc/sysctl.conf</summary>
    [OsqueryColumn("config_value")]
    public string ConfigValue { get; set; } = "";

    /// <summary>Data type</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Specific attribute of opaque type</summary>
    [OsqueryColumn("field_name")]
    public string FieldName { get; set; } = "";
}
