// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Query system_profiler data types and return the full result as JSON. Returns only the data types specified in the constraints. See available data types with `system_profiler -listDataTypes`.
/// </summary>
[OsqueryTable("system_profiler")]
public class SystemProfiler
{
    /// <summary>The system profiler data type (e.g., SPHardwareDataType)</summary>
    [OsqueryColumn("data_type")]
    public string DataType { get; set; } = "";

    /// <summary>A JSON representation of the full result dictionary for the data type</summary>
    [OsqueryColumn("value")]
    public string Value { get; set; } = "";
}
