// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Machine's temperature sensors.
/// </summary>
[OsqueryTable("temperature_sensors")]
public class TemperatureSensor
{
    /// <summary>The SMC key on macOS</summary>
    [OsqueryColumn("key")]
    public string Key { get; set; } = "";

    /// <summary>Name of temperature source</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Temperature in Celsius</summary>
    [OsqueryColumn("celsius")]
    public double Celsius { get; set; }

    /// <summary>Temperature in Fahrenheit</summary>
    [OsqueryColumn("fahrenheit")]
    public double Fahrenheit { get; set; }
}
