// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track current date and time in UTC.
/// </summary>
[OsqueryTable("time")]
public class Time
{
    /// <summary>Current weekday in UTC</summary>
    [OsqueryColumn("weekday")]
    public string Weekday { get; set; } = "";

    /// <summary>Current year in UTC</summary>
    [OsqueryColumn("year")]
    public int Year { get; set; }

    /// <summary>Current month in UTC</summary>
    [OsqueryColumn("month")]
    public int Month { get; set; }

    /// <summary>Current day in UTC</summary>
    [OsqueryColumn("day")]
    public int Day { get; set; }

    /// <summary>Current hour in UTC</summary>
    [OsqueryColumn("hour")]
    public int Hour { get; set; }

    /// <summary>Current minutes in UTC</summary>
    [OsqueryColumn("minutes")]
    public int Minutes { get; set; }

    /// <summary>Current seconds in UTC</summary>
    [OsqueryColumn("seconds")]
    public int Seconds { get; set; }

    /// <summary>Timezone for reported time (hardcoded to UTC)</summary>
    [OsqueryColumn("timezone")]
    public string Timezone { get; set; } = "";

    /// <summary>Current local timezone in of the system</summary>
    [OsqueryColumn("local_timezone")]
    public string LocalTimezone { get; set; } = "";

    /// <summary>Current UNIX time in UTC</summary>
    [OsqueryColumn("unix_time")]
    public int UnixTime { get; set; }

    /// <summary>Current timestamp (log format) in UTC</summary>
    [OsqueryColumn("timestamp")]
    public string Timestamp { get; set; } = "";

    /// <summary>Current date and time (ISO format) in UTC</summary>
    [OsqueryColumn("datetime")]
    public string Datetime { get; set; } = "";

    /// <summary>Current time (ISO format) in UTC</summary>
    [OsqueryColumn("iso_8601")]
    public string Iso8601 { get; set; } = "";

    /// <summary>Timestamp value in 100 nanosecond units</summary>
    [OsqueryColumn("win_timestamp")]
    public long WinTimestamp { get; set; }

}
