// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Locations backed up to using Time Machine. This table requires Full Disk Access (FDA) permission.
/// </summary>
[OsqueryTable("time_machine_destinations")]
public class TimeMachineDestination
{
    /// <summary>Human readable name of drive</summary>
    [OsqueryColumn("alias")]
    public string Alias { get; set; } = "";

    /// <summary>Time Machine destination ID</summary>
    [OsqueryColumn("destination_id")]
    public string DestinationId { get; set; } = "";

    /// <summary>Consistency scan date</summary>
    [OsqueryColumn("consistency_scan_date")]
    public int ConsistencyScanDate { get; set; }

    /// <summary>Root UUID of backup volume</summary>
    [OsqueryColumn("root_volume_uuid")]
    public string RootVolumeUuid { get; set; } = "";

    /// <summary>Bytes available on volume</summary>
    [OsqueryColumn("bytes_available")]
    public int BytesAvailable { get; set; }

    /// <summary>Bytes used on volume</summary>
    [OsqueryColumn("bytes_used")]
    public int BytesUsed { get; set; }

    /// <summary>Last known encrypted state</summary>
    [OsqueryColumn("encryption")]
    public string Encryption { get; set; } = "";

}
