// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// A table that lists the TPM related information.
/// </summary>
[OsqueryTable("tpm_info")]
public class TpmInfo
{
    /// <summary>TPM is activated</summary>
    [OsqueryColumn("activated")]
    public int Activated { get; set; }

    /// <summary>TPM is enabled</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>TPM is owned</summary>
    [OsqueryColumn("owned")]
    public int Owned { get; set; }

    /// <summary>TPM version</summary>
    [OsqueryColumn("manufacturer_version")]
    public string ManufacturerVersion { get; set; } = "";

    /// <summary>TPM manufacturers ID</summary>
    [OsqueryColumn("manufacturer_id")]
    public int ManufacturerId { get; set; }

    /// <summary>TPM manufacturers name</summary>
    [OsqueryColumn("manufacturer_name")]
    public string ManufacturerName { get; set; } = "";

    /// <summary>Product name of the TPM</summary>
    [OsqueryColumn("product_name")]
    public string ProductName { get; set; } = "";

    /// <summary>Version of the Physical Presence Interface</summary>
    [OsqueryColumn("physical_presence_version")]
    public string PhysicalPresenceVersion { get; set; } = "";

    /// <summary>Trusted Computing Group specification that the TPM supports</summary>
    [OsqueryColumn("spec_version")]
    public string SpecVersion { get; set; } = "";
}
