// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// System resource usage limits.
/// </summary>
[OsqueryTable("ulimit_info")]
public class UlimitInfo
{
    /// <summary>System resource to be limited</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Current limit value</summary>
    [OsqueryColumn("soft_limit")]
    public string SoftLimit { get; set; } = "";

    /// <summary>Maximum limit value</summary>
    [OsqueryColumn("hard_limit")]
    public string HardLimit { get; set; } = "";

}
