// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Queries the OSLog framework for entries in the system log. The maximum number of rows returned is limited for performance issues. Use timestamp > or >= constraints to optimize query performance. This table introduces a new idiom for extracting sequential data in batches using multiple queries, ordered by timestamp. To trigger it, the user should include the condition "timestamp > -1", and the table will handle pagination. Note that the saved pagination counter is incremented globally across all queries and table invocations within a query. To avoid multiple table invocations within a query, use only AND and = constraints in WHERE clause.
/// </summary>
[OsqueryTable("unified_log")]
public class UnifiedLog
{
    /// <summary>unix timestamp associated with the entry</summary>
    [OsqueryColumn("timestamp")]
    public long Timestamp { get; set; }

    /// <summary>floating point timestamp associated with the entry</summary>
    [OsqueryColumn("timestamp_double")]
    public string TimestampDouble { get; set; } = "";

    /// <summary>the storage category for the entry</summary>
    [OsqueryColumn("storage")]
    public int Storage { get; set; }

    /// <summary>composed message</summary>
    [OsqueryColumn("message")]
    public string Message { get; set; } = "";

    /// <summary>the activity ID associate with the entry</summary>
    [OsqueryColumn("activity")]
    public long Activity { get; set; }

    /// <summary>the name of the process that made the entry</summary>
    [OsqueryColumn("process")]
    public string Process { get; set; } = "";

    /// <summary>the pid of the process that made the entry</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>the name of the binary image that made the entry</summary>
    [OsqueryColumn("sender")]
    public string Sender { get; set; } = "";

    /// <summary>the tid of the thread that made the entry</summary>
    [OsqueryColumn("tid")]
    public long Tid { get; set; }

    /// <summary>the category of the os_log_t used</summary>
    [OsqueryColumn("category")]
    public string Category { get; set; } = "";

    /// <summary>the subsystem of the os_log_t used</summary>
    [OsqueryColumn("subsystem")]
    public string Subsystem { get; set; } = "";

    /// <summary>the severity level of the entry (undefined, debug, info, default, error, fault)</summary>
    [OsqueryColumn("level")]
    public string Level { get; set; } = "";

    /// <summary>the max number of rows returned (defaults to 100)</summary>
    [OsqueryColumn("max_rows")]
    public int MaxRows { get; set; }

    /// <summary>predicate to search (see `log help predicates`), note that this is merged into the predicate created from the column constraints</summary>
    [OsqueryColumn("predicate")]
    public string Predicate { get; set; } = "";

}
