// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track time passed since last boot. Some systems track this as calendar time, some as runtime.
/// </summary>
[OsqueryTable("uptime")]
public class Uptime
{
    /// <summary>Days of uptime</summary>
    [OsqueryColumn("days")]
    public int Days { get; set; }

    /// <summary>Hours of uptime</summary>
    [OsqueryColumn("hours")]
    public int Hours { get; set; }

    /// <summary>Minutes of uptime</summary>
    [OsqueryColumn("minutes")]
    public int Minutes { get; set; }

    /// <summary>Seconds of uptime</summary>
    [OsqueryColumn("seconds")]
    public int Seconds { get; set; }

    /// <summary>Total uptime seconds</summary>
    [OsqueryColumn("total_seconds")]
    public long TotalSeconds { get; set; }

}
