// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// USB devices that are actively plugged into the host system.
/// </summary>
[OsqueryTable("usb_devices")]
public class UsbDevice
{
    /// <summary>USB Device used address</summary>
    [OsqueryColumn("usb_address")]
    public int UsbAddress { get; set; }

    /// <summary>USB Device used port</summary>
    [OsqueryColumn("usb_port")]
    public int UsbPort { get; set; }

    /// <summary>USB Device vendor string</summary>
    [OsqueryColumn("vendor")]
    public string Vendor { get; set; } = "";

    /// <summary>Hex encoded USB Device vendor identifier</summary>
    [OsqueryColumn("vendor_id")]
    public string VendorId { get; set; } = "";

    /// <summary>USB Device version number</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>USB Device model string</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>Hex encoded USB Device model identifier</summary>
    [OsqueryColumn("model_id")]
    public string ModelId { get; set; } = "";

    /// <summary>USB Device serial connection</summary>
    [OsqueryColumn("serial")]
    public string Serial { get; set; } = "";

    /// <summary>USB Device class</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>USB Device subclass</summary>
    [OsqueryColumn("subclass")]
    public string Subclass { get; set; } = "";

    /// <summary>USB Device protocol</summary>
    [OsqueryColumn("protocol")]
    public string Protocol { get; set; } = "";

    /// <summary>1 If USB device is removable else 0</summary>
    [OsqueryColumn("removable")]
    public int Removable { get; set; }
}
