// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Local user accounts (including domain accounts that have logged on locally (Windows)).
/// </summary>
[OsqueryTable("users")]
public class User
{
    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Group ID (unsigned)</summary>
    [OsqueryColumn("gid")]
    public long Gid { get; set; }

    /// <summary>User ID as int64 signed (Apple)</summary>
    [OsqueryColumn("uid_signed")]
    public long UidSigned { get; set; }

    /// <summary>Default group ID as int64 signed (Apple)</summary>
    [OsqueryColumn("gid_signed")]
    public long GidSigned { get; set; }

    /// <summary>Username</summary>
    [OsqueryColumn("username")]
    public string Username { get; set; } = "";

    /// <summary>Optional user description</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>User's home directory</summary>
    [OsqueryColumn("directory")]
    public string Directory { get; set; } = "";

    /// <summary>User's configured default shell</summary>
    [OsqueryColumn("shell")]
    public string Shell { get; set; } = "";

    /// <summary>User's UUID (Apple) or SID (Windows)</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Whether the account is roaming (domain), local, or a system profile</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>IsHidden attribute set in OpenDirectory</summary>
    [OsqueryColumn("is_hidden")]
    public int IsHidden { get; set; }

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

    /// <summary>1 to include remote (LDAP/AD) accounts (default 0). Warning: without any uid/username filtering it may list whole LDAP directories</summary>
    [OsqueryColumn("include_remote")]
    public int IncludeRemote { get; set; }

}
