// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Track user events from the audit framework.
/// </summary>
[OsqueryTable("user_events")]
public class UserEvent
{
    /// <summary>User ID</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>Audit User ID</summary>
    [OsqueryColumn("auid")]
    public long Auid { get; set; }

    /// <summary>Process (or thread) ID</summary>
    [OsqueryColumn("pid")]
    public long Pid { get; set; }

    /// <summary>Message from the event</summary>
    [OsqueryColumn("message")]
    public string Message { get; set; } = "";

    /// <summary>The file description for the process socket</summary>
    [OsqueryColumn("type")]
    public int Type { get; set; }

    /// <summary>Supplied path from event</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The Internet protocol address or family ID</summary>
    [OsqueryColumn("address")]
    public string Address { get; set; } = "";

    /// <summary>The network protocol ID</summary>
    [OsqueryColumn("terminal")]
    public string Terminal { get; set; } = "";

    /// <summary>Time of execution in UNIX time</summary>
    [OsqueryColumn("time")]
    public long Time { get; set; }

    /// <summary>Time of execution in system uptime</summary>
    [OsqueryColumn("uptime")]
    public long Uptime { get; set; }

    /// <summary>Event ID</summary>
    [OsqueryColumn("eid")]
    public string Eid { get; set; } = "";

}
