// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Retrieve video card information of the machine.
/// </summary>
[OsqueryTable("video_info")]
public class VideoInfo
{
    /// <summary>The amount of bits per pixel to represent color.</summary>
    [OsqueryColumn("color_depth")]
    public int ColorDepth { get; set; }

    /// <summary>The driver of the device.</summary>
    [OsqueryColumn("driver")]
    public string Driver { get; set; } = "";

    /// <summary>The date listed on the installed driver.</summary>
    [OsqueryColumn("driver_date")]
    public long DriverDate { get; set; }

    /// <summary>The version of the installed driver.</summary>
    [OsqueryColumn("driver_version")]
    public string DriverVersion { get; set; } = "";

    /// <summary>The manufacturer of the gpu.</summary>
    [OsqueryColumn("manufacturer")]
    public string Manufacturer { get; set; } = "";

    /// <summary>The model of the gpu.</summary>
    [OsqueryColumn("model")]
    public string Model { get; set; } = "";

    /// <summary>The series of the gpu.</summary>
    [OsqueryColumn("series")]
    public string Series { get; set; } = "";

    /// <summary>The current resolution of the display.</summary>
    [OsqueryColumn("video_mode")]
    public string VideoMode { get; set; } = "";

}
