// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Darwin Virtual Memory statistics.
/// </summary>
[OsqueryTable("virtual_memory_info")]
public class VirtualMemoryInfo
{
    /// <summary>Total number of free pages.</summary>
    [OsqueryColumn("free")]
    public long Free { get; set; }

    /// <summary>Total number of active pages.</summary>
    [OsqueryColumn("active")]
    public long Active { get; set; }

    /// <summary>Total number of inactive pages.</summary>
    [OsqueryColumn("inactive")]
    public long Inactive { get; set; }

    /// <summary>Total number of speculative pages.</summary>
    [OsqueryColumn("speculative")]
    public long Speculative { get; set; }

    /// <summary>Total number of throttled pages.</summary>
    [OsqueryColumn("throttled")]
    public long Throttled { get; set; }

    /// <summary>Total number of wired down pages.</summary>
    [OsqueryColumn("wired")]
    public long Wired { get; set; }

    /// <summary>Total number of purgeable pages.</summary>
    [OsqueryColumn("purgeable")]
    public long Purgeable { get; set; }

    /// <summary>Total number of calls to vm_faults.</summary>
    [OsqueryColumn("faults")]
    public long Faults { get; set; }

    /// <summary>Total number of copy-on-write pages.</summary>
    [OsqueryColumn("copy")]
    public long Copy { get; set; }

    /// <summary>Total number of zero filled pages.</summary>
    [OsqueryColumn("zero_fill")]
    public long ZeroFill { get; set; }

    /// <summary>Total number of reactivated pages.</summary>
    [OsqueryColumn("reactivated")]
    public long Reactivated { get; set; }

    /// <summary>Total number of purged pages.</summary>
    [OsqueryColumn("purged")]
    public long Purged { get; set; }

    /// <summary>Total number of file backed pages.</summary>
    [OsqueryColumn("file_backed")]
    public long FileBacked { get; set; }

    /// <summary>Total number of anonymous pages.</summary>
    [OsqueryColumn("anonymous")]
    public long Anonymous { get; set; }

    /// <summary>Total number of uncompressed pages.</summary>
    [OsqueryColumn("uncompressed")]
    public long Uncompressed { get; set; }

    /// <summary>The number of pages used to store compressed VM pages.</summary>
    [OsqueryColumn("compressor")]
    public long Compressor { get; set; }

    /// <summary>The total number of pages that have been decompressed by the VM compressor.</summary>
    [OsqueryColumn("decompressed")]
    public long Decompressed { get; set; }

    /// <summary>The total number of pages that have been compressed by the VM compressor.</summary>
    [OsqueryColumn("compressed")]
    public long Compressed { get; set; }

    /// <summary>The total number of requests for pages from a pager.</summary>
    [OsqueryColumn("page_ins")]
    public long PageIns { get; set; }

    /// <summary>Total number of pages paged out.</summary>
    [OsqueryColumn("page_outs")]
    public long PageOuts { get; set; }

    /// <summary>The total number of compressed pages that have been swapped out to disk.</summary>
    [OsqueryColumn("swap_ins")]
    public long SwapIns { get; set; }

    /// <summary>The total number of compressed pages that have been swapped back in from disk.</summary>
    [OsqueryColumn("swap_outs")]
    public long SwapOuts { get; set; }

}
