// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists all vscode extensions.
/// </summary>
[OsqueryTable("vscode_extensions")]
public class VscodeExtension
{
    /// <summary>Extension Name</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Extension UUID</summary>
    [OsqueryColumn("uuid")]
    public string Uuid { get; set; } = "";

    /// <summary>Extension version</summary>
    [OsqueryColumn("version")]
    public string Version { get; set; } = "";

    /// <summary>Extension path</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>Publisher Name</summary>
    [OsqueryColumn("publisher")]
    public string Publisher { get; set; } = "";

    /// <summary>Publisher ID</summary>
    [OsqueryColumn("publisher_id")]
    public string PublisherId { get; set; } = "";

    /// <summary>Installed Timestamp</summary>
    [OsqueryColumn("installed_at")]
    public long InstalledAt { get; set; }

    /// <summary>Pre release version</summary>
    [OsqueryColumn("prerelease")]
    public int Prerelease { get; set; }

    /// <summary>The local user that owns the plugin</summary>
    [OsqueryColumn("uid")]
    public long Uid { get; set; }

    /// <summary>The VSCode edition (vscode, vscode_insiders, vscodium, vscodium_insiders, cursor, windsurf, trae)</summary>
    [OsqueryColumn("vscode_edition")]
    public string VscodeEdition { get; set; } = "";

}
