// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS known/remembered Wi-Fi networks list.
/// </summary>
[OsqueryTable("wifi_networks")]
public class WifiNetwork
{
    /// <summary>SSID octets of the network</summary>
    [OsqueryColumn("ssid")]
    public string Ssid { get; set; } = "";

    /// <summary>Name of the network</summary>
    [OsqueryColumn("network_name")]
    public string NetworkName { get; set; } = "";

    /// <summary>Type of security on this network</summary>
    [OsqueryColumn("security_type")]
    public string SecurityType { get; set; } = "";

    /// <summary>Last time this network was connected to as a unix_time (max of last_connected_automatic and last_connected_manual, if available)</summary>
    [OsqueryColumn("last_connected")]
    public int LastConnected { get; set; }

    /// <summary>Last time this network was automatically connected to by the system as a unix_time</summary>
    [OsqueryColumn("last_connected_automatic")]
    public int LastConnectedAutomatic { get; set; }

    /// <summary>Last time this network was manually connected to by the user as a unix_time</summary>
    [OsqueryColumn("last_connected_manual")]
    public int LastConnectedManual { get; set; }

    /// <summary>1 if Passpoint is supported, 0 otherwise</summary>
    [OsqueryColumn("passpoint")]
    public int Passpoint { get; set; }

    /// <summary>1 if network is possibly a hidden network, 0 otherwise</summary>
    [OsqueryColumn("possibly_hidden")]
    public int PossiblyHidden { get; set; }

    /// <summary>1 if roaming is supported, 0 otherwise</summary>
    [OsqueryColumn("roaming")]
    public int Roaming { get; set; }

    /// <summary>Describe the roaming profile, usually one of Single, Dual  or Multi</summary>
    [OsqueryColumn("roaming_profile")]
    public string RoamingProfile { get; set; } = "";

    /// <summary>1 if auto login is enabled, 0 otherwise</summary>
    [OsqueryColumn("auto_login")]
    public int AutoLogin { get; set; }

    /// <summary>1 if this network is temporarily disabled, 0 otherwise</summary>
    [OsqueryColumn("temporarily_disabled")]
    public int TemporarilyDisabled { get; set; }

    /// <summary>1 if this network is disabled, 0 otherwise</summary>
    [OsqueryColumn("disabled")]
    public int Disabled { get; set; }

    /// <summary>Shows why this network was added, via menubar or command line or something else </summary>
    [OsqueryColumn("add_reason")]
    public string AddReason { get; set; } = "";

    /// <summary>Time this network was added as a unix_time</summary>
    [OsqueryColumn("added_at")]
    public int AddedAt { get; set; }

    /// <summary>1 if this network has a captive portal, 0 otherwise</summary>
    [OsqueryColumn("captive_portal")]
    public int CaptivePortal { get; set; }

    /// <summary>Time this network logged in to a captive portal as unix_time</summary>
    [OsqueryColumn("captive_login_date")]
    public int CaptiveLoginDate { get; set; }

    /// <summary>1 if this network was previously a captive network, 0 otherwise</summary>
    [OsqueryColumn("was_captive_network")]
    public int WasCaptiveNetwork { get; set; }

    /// <summary>1 if this network set to join automatically, 0 otherwise</summary>
    [OsqueryColumn("auto_join")]
    public int AutoJoin { get; set; }

    /// <summary>1 if this network is a personal hotspot, 0 otherwise</summary>
    [OsqueryColumn("personal_hotspot")]
    public int PersonalHotspot { get; set; }
}
