// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// macOS current WiFi status. This table requires Full Disk Access (FDA) permission to retrieve network_name.
/// </summary>
[OsqueryTable("wifi_status")]
public class WifiStatus
{
    /// <summary>Name of the interface</summary>
    [OsqueryColumn("interface")]
    public string @Interface { get; set; } = "";

    /// <summary>SSID octets of the network</summary>
    [OsqueryColumn("ssid")]
    public string Ssid { get; set; } = "";

    /// <summary>The current basic service set identifier</summary>
    [OsqueryColumn("bssid")]
    public string Bssid { get; set; } = "";

    /// <summary>Name of the network</summary>
    [OsqueryColumn("network_name")]
    public string NetworkName { get; set; } = "";

    /// <summary>The country code (ISO/IEC 3166-1:1997) for the network</summary>
    [OsqueryColumn("country_code")]
    public string CountryCode { get; set; } = "";

    /// <summary>Type of security on this network</summary>
    [OsqueryColumn("security_type")]
    public string SecurityType { get; set; } = "";

    /// <summary>The current received signal strength indication (dbm)</summary>
    [OsqueryColumn("rssi")]
    public int Rssi { get; set; }

    /// <summary>The current noise measurement (dBm)</summary>
    [OsqueryColumn("noise")]
    public int Noise { get; set; }

    /// <summary>Channel number</summary>
    [OsqueryColumn("channel")]
    public int Channel { get; set; }

    /// <summary>Channel width</summary>
    [OsqueryColumn("channel_width")]
    public int ChannelWidth { get; set; }

    /// <summary>Channel band</summary>
    [OsqueryColumn("channel_band")]
    public int ChannelBand { get; set; }

    /// <summary>The current transmit rate</summary>
    [OsqueryColumn("transmit_rate")]
    public string TransmitRate { get; set; } = "";

    /// <summary>The current operating mode for the Wi-Fi interface</summary>
    [OsqueryColumn("mode")]
    public string Mode { get; set; } = "";
}
