// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists named Windows objects in the default object directories, across all terminal services sessions.  Example Windows object types include Mutexes, Events, Jobs and Semaphors.
/// </summary>
[OsqueryTable("winbaseobj")]
public class Winbaseobj
{
    /// <summary>Terminal Services Session Id</summary>
    [OsqueryColumn("session_id")]
    public int SessionId { get; set; }

    /// <summary>Object Name</summary>
    [OsqueryColumn("object_name")]
    public string ObjectName { get; set; } = "";

    /// <summary>Object Type</summary>
    [OsqueryColumn("object_type")]
    public string ObjectType { get; set; } = "";

}
