// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Run searches against the Windows system index database using Advanced Query Syntax. See https://learn.microsoft.com/en-us/windows/win32/search/-search-3x-advancedquerysyntax for details.
/// </summary>
[OsqueryTable("windows_search")]
public class WindowsSearch
{
    /// <summary>The name of the item</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>The full path of the item.</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>The item size in bytes.</summary>
    [OsqueryColumn("size")]
    public long Size { get; set; }

    /// <summary>The unix timestamp of when the item was created.</summary>
    [OsqueryColumn("date_created")]
    public int DateCreated { get; set; }

    /// <summary>The unix timestamp of when the item was last modified</summary>
    [OsqueryColumn("date_modified")]
    public int DateModified { get; set; }

    /// <summary>The owner of the item</summary>
    [OsqueryColumn("owner")]
    public string Owner { get; set; } = "";

    /// <summary>The item type</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Additional property values JSON</summary>
    [OsqueryColumn("properties")]
    public string Properties { get; set; } = "";

    /// <summary>Windows search query</summary>
    [OsqueryColumn("query")]
    public string Query { get; set; } = "";

    /// <summary>Sort for windows api</summary>
    [OsqueryColumn("sort")]
    public string Sort { get; set; } = "";

    /// <summary>Maximum number of results returned by windows api, set to -1 for unlimited</summary>
    [OsqueryColumn("max_results")]
    public int MaxResults { get; set; }

    /// <summary>Comma separated list of columns to include in properties JSON</summary>
    [OsqueryColumn("additional_properties")]
    public string AdditionalProperties { get; set; } = "";
}
