// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Enumeration of registered Windows security products. Note: Not compatible with Windows Server.
/// </summary>
[OsqueryTable("windows_security_products")]
public class WindowsSecurityProduct
{
    /// <summary>Type of security product</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Name of product</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>State of protection</summary>
    [OsqueryColumn("state")]
    public string State { get; set; } = "";

    /// <summary>Timestamp for the product state</summary>
    [OsqueryColumn("state_timestamp")]
    public string StateTimestamp { get; set; } = "";

    /// <summary>Remediation path</summary>
    [OsqueryColumn("remediation_path")]
    public string RemediationPath { get; set; } = "";

    /// <summary>1 if product signatures are up to date, else 0</summary>
    [OsqueryColumn("signatures_up_to_date")]
    public int SignaturesUpToDate { get; set; }
}
