// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists names and installation states of windows features. Maps to Win32_OptionalFeature WMI class.
/// </summary>
[OsqueryTable("windows_optional_features")]
public class WindowsOptionalFeature
{
    /// <summary>Name of the feature</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Caption of feature in settings UI</summary>
    [OsqueryColumn("caption")]
    public string Caption { get; set; } = "";

    /// <summary>Installation state value. 1 == Enabled, 2 == Disabled, 3 == Absent</summary>
    [OsqueryColumn("state")]
    public int State { get; set; }

    /// <summary>Installation state name. 'Enabled','Disabled','Absent'</summary>
    [OsqueryColumn("statename")]
    public string Statename { get; set; } = "";
}
