// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Provides the list of Windows firewall rules.
/// </summary>
[OsqueryTable("windows_firewall_rules")]
public class WindowsFirewallRule
{
    /// <summary>Friendly name of the rule</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Friendly name of the application to which the rule applies</summary>
    [OsqueryColumn("app_name")]
    public string AppName { get; set; } = "";

    /// <summary>Action for the rule or default setting</summary>
    [OsqueryColumn("action")]
    public string Action { get; set; } = "";

    /// <summary>1 if the rule is enabled</summary>
    [OsqueryColumn("enabled")]
    public int Enabled { get; set; }

    /// <summary>Group to which an individual rule belongs</summary>
    [OsqueryColumn("grouping")]
    public string Grouping { get; set; } = "";

    /// <summary>Direction of traffic for which the rule applies</summary>
    [OsqueryColumn("direction")]
    public string Direction { get; set; } = "";

    /// <summary>IP protocol of the rule</summary>
    [OsqueryColumn("protocol")]
    public string Protocol { get; set; } = "";

    /// <summary>Local addresses for the rule</summary>
    [OsqueryColumn("local_addresses")]
    public string LocalAddresses { get; set; } = "";

    /// <summary>Remote addresses for the rule</summary>
    [OsqueryColumn("remote_addresses")]
    public string RemoteAddresses { get; set; } = "";

    /// <summary>Local ports for the rule</summary>
    [OsqueryColumn("local_ports")]
    public string LocalPorts { get; set; } = "";

    /// <summary>Remote ports for the rule</summary>
    [OsqueryColumn("remote_ports")]
    public string RemotePorts { get; set; } = "";

    /// <summary>ICMP types and codes for the rule</summary>
    [OsqueryColumn("icmp_types_codes")]
    public string IcmpTypesCodes { get; set; } = "";

    /// <summary>1 if the rule profile type is domain</summary>
    [OsqueryColumn("profile_domain")]
    public int ProfileDomain { get; set; }

    /// <summary>1 if the rule profile type is private</summary>
    [OsqueryColumn("profile_private")]
    public int ProfilePrivate { get; set; }

    /// <summary>1 if the rule profile type is public</summary>
    [OsqueryColumn("profile_public")]
    public int ProfilePublic { get; set; }

    /// <summary>Service name property of the application</summary>
    [OsqueryColumn("service_name")]
    public string ServiceName { get; set; } = "";
}
