// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// WMI CommandLineEventConsumer, which can be used for persistence on Windows. See https://www.blackhat.com/docs/us-15/materials/us-15-Graeber-Abusing-Windows-Management-Instrumentation-WMI-To-Build-A-Persistent%20Asynchronous-And-Fileless-Backdoor-wp.pdf for more details.
/// </summary>
[OsqueryTable("wmi_cli_event_consumers")]
public class WmiCliEventConsumer
{
    /// <summary>The WMI namespace where the consumer was found.</summary>
    [OsqueryColumn("namespace")]
    public string @Namespace { get; set; } = "";

    /// <summary>Unique name of a consumer.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Standard string template that specifies the process to be started. This property can be NULL, and the ExecutablePath property is used as the command line.</summary>
    [OsqueryColumn("command_line_template")]
    public string CommandLineTemplate { get; set; } = "";

    /// <summary>Module to execute. The string can specify the full path and file name of the module to execute, or it can specify a partial name. If a partial name is specified, the current drive and current directory are assumed.</summary>
    [OsqueryColumn("executable_path")]
    public string ExecutablePath { get; set; } = "";

    /// <summary>The name of the class.</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>Relative path to the class or instance.</summary>
    [OsqueryColumn("relative_path")]
    public string RelativePath { get; set; } = "";
}
