// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists WMI event filters.
/// </summary>
[OsqueryTable("wmi_event_filters")]
public class WmiEventFilter
{
    /// <summary>The WMI namespace where the filter was found.</summary>
    [OsqueryColumn("namespace")]
    public string @Namespace { get; set; } = "";

    /// <summary>Unique identifier of an event filter.</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Windows Management Instrumentation Query Language (WQL) event query that specifies the set of events for consumer notification, and the specific conditions for notification.</summary>
    [OsqueryColumn("query")]
    public string Query { get; set; } = "";

    /// <summary>Query language that the query is written in.</summary>
    [OsqueryColumn("query_language")]
    public string QueryLanguage { get; set; } = "";

    /// <summary>The name of the class.</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>Relative path to the class or instance.</summary>
    [OsqueryColumn("relative_path")]
    public string RelativePath { get; set; } = "";

}
