// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Lists the relationship between event consumers and filters.
/// </summary>
[OsqueryTable("wmi_filter_consumer_binding")]
public class WmiFilterConsumerBinding
{
    /// <summary>The WMI namespace where the binding was found.</summary>
    [OsqueryColumn("namespace")]
    public string @Namespace { get; set; } = "";

    /// <summary>Reference to an instance of __EventConsumer that represents the object path to a logical consumer, the recipient of an event.</summary>
    [OsqueryColumn("consumer")]
    public string Consumer { get; set; } = "";

    /// <summary>Reference to an instance of __EventFilter that represents the object path to an event filter which is a query that specifies the type of event to be received.</summary>
    [OsqueryColumn("filter")]
    public string Filter { get; set; } = "";

    /// <summary>The name of the class.</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>Relative path to the class or instance.</summary>
    [OsqueryColumn("relative_path")]
    public string RelativePath { get; set; } = "";
}
