// <auto-generated>
// This file was generated by generate_tables.py from the osquery table specs.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// WMI ActiveScriptEventConsumer, which can be used for persistence on Windows. See https://www.blackhat.com/docs/us-15/materials/us-15-Graeber-Abusing-Windows-Management-Instrumentation-WMI-To-Build-A-Persistent%20Asynchronous-And-Fileless-Backdoor-wp.pdf for more details.
/// </summary>
[OsqueryTable("wmi_script_event_consumers")]
public class WmiScriptEventConsumer
{
    /// <summary>The WMI namespace where the consumer was found.</summary>
    [OsqueryColumn("namespace")]
    public string @Namespace { get; set; } = "";

    /// <summary>Unique identifier for the event consumer. </summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Name of the scripting engine to use, for example, 'VBScript'. This property cannot be NULL.</summary>
    [OsqueryColumn("scripting_engine")]
    public string ScriptingEngine { get; set; } = "";

    /// <summary>Name of the file from which the script text is read, intended as an alternative to specifying the text of the script in the ScriptText property.</summary>
    [OsqueryColumn("script_file_name")]
    public string ScriptFileName { get; set; } = "";

    /// <summary>Text of the script that is expressed in a language known to the scripting engine. This property must be NULL if the ScriptFileName property is not NULL.</summary>
    [OsqueryColumn("script_text")]
    public string ScriptText { get; set; } = "";

    /// <summary>The name of the class.</summary>
    [OsqueryColumn("class")]
    public string @Class { get; set; } = "";

    /// <summary>Relative path to the class or instance.</summary>
    [OsqueryColumn("relative_path")]
    public string RelativePath { get; set; } = "";
}
