// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Database of the machine's XProtect signatures.
/// </summary>
[OsqueryTable("xprotect_entries")]
public class XprotectEntry
{
    /// <summary>Description of XProtected malware</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Launch services content type</summary>
    [OsqueryColumn("launch_type")]
    public string LaunchType { get; set; } = "";

    /// <summary>XProtect identity (SHA1) of content</summary>
    [OsqueryColumn("identity")]
    public string Identity { get; set; } = "";

    /// <summary>Use this file name to match</summary>
    [OsqueryColumn("filename")]
    public string Filename { get; set; } = "";

    /// <summary>Use this file type to match</summary>
    [OsqueryColumn("filetype")]
    public string Filetype { get; set; } = "";

    /// <summary>Match any of the identities/patterns for this XProtect name</summary>
    [OsqueryColumn("optional")]
    public int Optional { get; set; }

    /// <summary>Uses a match pattern instead of identity</summary>
    [OsqueryColumn("uses_pattern")]
    public int UsesPattern { get; set; }

}
