// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Database of the machine's XProtect browser-related signatures.
/// </summary>
[OsqueryTable("xprotect_meta")]
public class XprotectMeta
{
    /// <summary>Browser plugin or extension identifier</summary>
    [OsqueryColumn("identifier")]
    public string Identifier { get; set; } = "";

    /// <summary>Either plugin or extension</summary>
    [OsqueryColumn("type")]
    public string Type { get; set; } = "";

    /// <summary>Developer identity (SHA1) of extension</summary>
    [OsqueryColumn("developer_id")]
    public string DeveloperId { get; set; } = "";

    /// <summary>The minimum allowed plugin version.</summary>
    [OsqueryColumn("min_version")]
    public string MinVersion { get; set; } = "";

}
