// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Triggers one-off YARA query for files at the specified path. Additionally requires one of `sig_group`, `sigfile`, or `sigrule`.
/// </summary>
[OsqueryTable("yara_file")]
public class YaraFile
{
    /// <summary>The path scanned</summary>
    [OsqueryColumn("path")]
    public string Path { get; set; } = "";

    /// <summary>List of YARA matches</summary>
    [OsqueryColumn("matches")]
    public string Matches { get; set; } = "";

    /// <summary>Number of YARA matches</summary>
    [OsqueryColumn("count")]
    public int Count { get; set; }

    /// <summary>Signature group used</summary>
    [OsqueryColumn("sig_group")]
    public string SigGroup { get; set; } = "";

    /// <summary>Signature file used</summary>
    [OsqueryColumn("sigfile")]
    public string Sigfile { get; set; } = "";

    /// <summary>Signature strings used</summary>
    [OsqueryColumn("sigrule")]
    public string Sigrule { get; set; } = "";

    /// <summary>Matching strings</summary>
    [OsqueryColumn("strings")]
    public string Strings { get; set; } = "";

    /// <summary>Matching tags</summary>
    [OsqueryColumn("tags")]
    public string Tags { get; set; } = "";

    /// <summary>Signature url</summary>
    [OsqueryColumn("sigurl")]
    public string Sigurl { get; set; } = "";

    /// <summary>Pids that contain a namespace</summary>
    [OsqueryColumn("pid_with_namespace")]
    public int PidWithNamespace { get; set; }

}
