// <auto-generated>
// This file was generated by Osquery.CodeGen from the osquery table schema.
// Do not edit manually. Re-run the generator to update.
// </auto-generated>

// Copyright (c) 2014-present, The osquery authors
//
// This source code is licensed as defined by the LICENSE file found in the
// root directory of this source tree.
//
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

namespace Osquery.Tables;

/// <summary>
/// Yandex.Cloud instance metadata.
/// </summary>
[OsqueryTable("ycloud_instance_metadata")]
public class YcloudInstanceMetadata
{
    /// <summary>Unique identifier for the VM</summary>
    [OsqueryColumn("instance_id")]
    public string InstanceId { get; set; } = "";

    /// <summary>Folder identifier for the VM</summary>
    [OsqueryColumn("folder_id")]
    public string FolderId { get; set; } = "";

    /// <summary>Cloud identifier for the VM</summary>
    [OsqueryColumn("cloud_id")]
    public string CloudId { get; set; } = "";

    /// <summary>Name of the VM</summary>
    [OsqueryColumn("name")]
    public string Name { get; set; } = "";

    /// <summary>Description of the VM</summary>
    [OsqueryColumn("description")]
    public string Description { get; set; } = "";

    /// <summary>Hostname of the VM</summary>
    [OsqueryColumn("hostname")]
    public string Hostname { get; set; } = "";

    /// <summary>Availability zone of the VM</summary>
    [OsqueryColumn("zone")]
    public string Zone { get; set; } = "";

    /// <summary>SSH public key. Only available if supplied at instance launch time</summary>
    [OsqueryColumn("ssh_public_key")]
    public string SshPublicKey { get; set; } = "";

    /// <summary>Indicates if serial port is enabled for the VM</summary>
    [OsqueryColumn("serial_port_enabled")]
    public string SerialPortEnabled { get; set; } = "";

    /// <summary>Endpoint used to fetch VM metadata</summary>
    [OsqueryColumn("metadata_endpoint")]
    public string MetadataEndpoint { get; set; } = "";

}
